// Code generated by ent, DO NOT EDIT.

package channel

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the channel type in the database.
	Label = "channel"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldIconURL holds the string denoting the icon_url field in the database.
	FieldIconURL = "icon_url"
	// FieldWebsiteURL holds the string denoting the website_url field in the database.
	FieldWebsiteURL = "website_url"
	// FieldBalanceURL holds the string denoting the balance_url field in the database.
	FieldBalanceURL = "balance_url"
	// FieldBalanceMethod holds the string denoting the balance_method field in the database.
	FieldBalanceMethod = "balance_method"
	// FieldBalanceHeaders holds the string denoting the balance_headers field in the database.
	FieldBalanceHeaders = "balance_headers"
	// FieldBalanceBody holds the string denoting the balance_body field in the database.
	FieldBalanceBody = "balance_body"
	// FieldBalancePath holds the string denoting the balance_path field in the database.
	FieldBalancePath = "balance_path"
	// FieldBalanceUnit holds the string denoting the balance_unit field in the database.
	FieldBalanceUnit = "balance_unit"
	// FieldCachedBalance holds the string denoting the cached_balance field in the database.
	FieldCachedBalance = "cached_balance"
	// FieldLastCheckAt holds the string denoting the last_check_at field in the database.
	FieldLastCheckAt = "last_check_at"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// Table holds the table name of the channel in the database.
	Table = "channels"
)

// Columns holds all SQL columns for channel fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldName,
	FieldDescription,
	FieldPlatform,
	FieldStatus,
	FieldIconURL,
	FieldWebsiteURL,
	FieldBalanceURL,
	FieldBalanceMethod,
	FieldBalanceHeaders,
	FieldBalanceBody,
	FieldBalancePath,
	FieldBalanceUnit,
	FieldCachedBalance,
	FieldLastCheckAt,
	FieldLastError,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// IconURLValidator is a validator for the "icon_url" field. It is called by the builders before save.
	IconURLValidator func(string) error
	// WebsiteURLValidator is a validator for the "website_url" field. It is called by the builders before save.
	WebsiteURLValidator func(string) error
	// BalanceURLValidator is a validator for the "balance_url" field. It is called by the builders before save.
	BalanceURLValidator func(string) error
	// DefaultBalanceMethod holds the default value on creation for the "balance_method" field.
	DefaultBalanceMethod string
	// BalanceMethodValidator is a validator for the "balance_method" field. It is called by the builders before save.
	BalanceMethodValidator func(string) error
	// BalancePathValidator is a validator for the "balance_path" field. It is called by the builders before save.
	BalancePathValidator func(string) error
	// DefaultBalanceUnit holds the default value on creation for the "balance_unit" field.
	DefaultBalanceUnit string
	// BalanceUnitValidator is a validator for the "balance_unit" field. It is called by the builders before save.
	BalanceUnitValidator func(string) error
)

// OrderOption defines the ordering options for the Channel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByIconURL orders the results by the icon_url field.
func ByIconURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIconURL, opts...).ToFunc()
}

// ByWebsiteURL orders the results by the website_url field.
func ByWebsiteURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebsiteURL, opts...).ToFunc()
}

// ByBalanceURL orders the results by the balance_url field.
func ByBalanceURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceURL, opts...).ToFunc()
}

// ByBalanceMethod orders the results by the balance_method field.
func ByBalanceMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceMethod, opts...).ToFunc()
}

// ByBalanceBody orders the results by the balance_body field.
func ByBalanceBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceBody, opts...).ToFunc()
}

// ByBalancePath orders the results by the balance_path field.
func ByBalancePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalancePath, opts...).ToFunc()
}

// ByBalanceUnit orders the results by the balance_unit field.
func ByBalanceUnit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceUnit, opts...).ToFunc()
}

// ByCachedBalance orders the results by the cached_balance field.
func ByCachedBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCachedBalance, opts...).ToFunc()
}

// ByLastCheckAt orders the results by the last_check_at field.
func ByLastCheckAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastCheckAt, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}
