-- 091_channel_balance.sql
-- 渠道余额查询配置和缓存字段

ALTER TABLE channels ADD COLUMN IF NOT EXISTS balance_url VARCHAR(500);
ALTER TABLE channels ADD COLUMN IF NOT EXISTS balance_method VARCHAR(10) DEFAULT 'GET';
ALTER TABLE channels ADD COLUMN IF NOT EXISTS balance_headers JSONB DEFAULT '{}';
ALTER TABLE channels ADD COLUMN IF NOT EXISTS balance_body TEXT DEFAULT '';
ALTER TABLE channels ADD COLUMN IF NOT EXISTS balance_path VARCHAR(200) DEFAULT '';
ALTER TABLE channels ADD COLUMN IF NOT EXISTS balance_unit VARCHAR(20) DEFAULT '$';
ALTER TABLE channels ADD COLUMN IF NOT EXISTS cached_balance DECIMAL(20,6);
ALTER TABLE channels ADD COLUMN IF NOT EXISTS last_check_at TIMESTAMPTZ;
ALTER TABLE channels ADD COLUMN IF NOT EXISTS last_error TEXT DEFAULT '';
