ALTER TABLE groups ADD COLUMN IF NOT EXISTS health_status VARCHAR(20) DEFAULT '';
ALTER TABLE groups ADD COLUMN IF NOT EXISTS healthy_accounts INT DEFAULT 0;
ALTER TABLE groups ADD COLUMN IF NOT EXISTS total_checked_accounts INT DEFAULT 0;
ALTER TABLE groups ADD COLUMN IF NOT EXISTS last_health_check_at TIMESTAMPTZ;
