// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/channel"
)

// ChannelCreate is the builder for creating a Channel entity.
type ChannelCreate struct {
	config
	mutation *ChannelMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChannelCreate) SetCreatedAt(v time.Time) *ChannelCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChannelCreate) SetNillableCreatedAt(v *time.Time) *ChannelCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChannelCreate) SetUpdatedAt(v time.Time) *ChannelCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChannelCreate) SetNillableUpdatedAt(v *time.Time) *ChannelCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ChannelCreate) SetDeletedAt(v time.Time) *ChannelCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ChannelCreate) SetNillableDeletedAt(v *time.Time) *ChannelCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ChannelCreate) SetName(v string) *ChannelCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ChannelCreate) SetDescription(v string) *ChannelCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ChannelCreate) SetNillableDescription(v *string) *ChannelCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *ChannelCreate) SetPlatform(v string) *ChannelCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_c *ChannelCreate) SetNillablePlatform(v *string) *ChannelCreate {
	if v != nil {
		_c.SetPlatform(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ChannelCreate) SetStatus(v string) *ChannelCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ChannelCreate) SetNillableStatus(v *string) *ChannelCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetIconURL sets the "icon_url" field.
func (_c *ChannelCreate) SetIconURL(v string) *ChannelCreate {
	_c.mutation.SetIconURL(v)
	return _c
}

// SetNillableIconURL sets the "icon_url" field if the given value is not nil.
func (_c *ChannelCreate) SetNillableIconURL(v *string) *ChannelCreate {
	if v != nil {
		_c.SetIconURL(*v)
	}
	return _c
}

// SetWebsiteURL sets the "website_url" field.
func (_c *ChannelCreate) SetWebsiteURL(v string) *ChannelCreate {
	_c.mutation.SetWebsiteURL(v)
	return _c
}

// SetNillableWebsiteURL sets the "website_url" field if the given value is not nil.
func (_c *ChannelCreate) SetNillableWebsiteURL(v *string) *ChannelCreate {
	if v != nil {
		_c.SetWebsiteURL(*v)
	}
	return _c
}

// SetBalanceURL sets the "balance_url" field.
func (_c *ChannelCreate) SetBalanceURL(v string) *ChannelCreate {
	_c.mutation.SetBalanceURL(v)
	return _c
}

// SetNillableBalanceURL sets the "balance_url" field if the given value is not nil.
func (_c *ChannelCreate) SetNillableBalanceURL(v *string) *ChannelCreate {
	if v != nil {
		_c.SetBalanceURL(*v)
	}
	return _c
}

// SetBalanceMethod sets the "balance_method" field.
func (_c *ChannelCreate) SetBalanceMethod(v string) *ChannelCreate {
	_c.mutation.SetBalanceMethod(v)
	return _c
}

// SetNillableBalanceMethod sets the "balance_method" field if the given value is not nil.
func (_c *ChannelCreate) SetNillableBalanceMethod(v *string) *ChannelCreate {
	if v != nil {
		_c.SetBalanceMethod(*v)
	}
	return _c
}

// SetBalanceHeaders sets the "balance_headers" field.
func (_c *ChannelCreate) SetBalanceHeaders(v map[string]string) *ChannelCreate {
	_c.mutation.SetBalanceHeaders(v)
	return _c
}

// SetBalanceBody sets the "balance_body" field.
func (_c *ChannelCreate) SetBalanceBody(v string) *ChannelCreate {
	_c.mutation.SetBalanceBody(v)
	return _c
}

// SetNillableBalanceBody sets the "balance_body" field if the given value is not nil.
func (_c *ChannelCreate) SetNillableBalanceBody(v *string) *ChannelCreate {
	if v != nil {
		_c.SetBalanceBody(*v)
	}
	return _c
}

// SetBalancePath sets the "balance_path" field.
func (_c *ChannelCreate) SetBalancePath(v string) *ChannelCreate {
	_c.mutation.SetBalancePath(v)
	return _c
}

// SetNillableBalancePath sets the "balance_path" field if the given value is not nil.
func (_c *ChannelCreate) SetNillableBalancePath(v *string) *ChannelCreate {
	if v != nil {
		_c.SetBalancePath(*v)
	}
	return _c
}

// SetBalanceUnit sets the "balance_unit" field.
func (_c *ChannelCreate) SetBalanceUnit(v string) *ChannelCreate {
	_c.mutation.SetBalanceUnit(v)
	return _c
}

// SetNillableBalanceUnit sets the "balance_unit" field if the given value is not nil.
func (_c *ChannelCreate) SetNillableBalanceUnit(v *string) *ChannelCreate {
	if v != nil {
		_c.SetBalanceUnit(*v)
	}
	return _c
}

// SetCachedBalance sets the "cached_balance" field.
func (_c *ChannelCreate) SetCachedBalance(v float64) *ChannelCreate {
	_c.mutation.SetCachedBalance(v)
	return _c
}

// SetNillableCachedBalance sets the "cached_balance" field if the given value is not nil.
func (_c *ChannelCreate) SetNillableCachedBalance(v *float64) *ChannelCreate {
	if v != nil {
		_c.SetCachedBalance(*v)
	}
	return _c
}

// SetLastCheckAt sets the "last_check_at" field.
func (_c *ChannelCreate) SetLastCheckAt(v time.Time) *ChannelCreate {
	_c.mutation.SetLastCheckAt(v)
	return _c
}

// SetNillableLastCheckAt sets the "last_check_at" field if the given value is not nil.
func (_c *ChannelCreate) SetNillableLastCheckAt(v *time.Time) *ChannelCreate {
	if v != nil {
		_c.SetLastCheckAt(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *ChannelCreate) SetLastError(v string) *ChannelCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *ChannelCreate) SetNillableLastError(v *string) *ChannelCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// Mutation returns the ChannelMutation object of the builder.
func (_c *ChannelCreate) Mutation() *ChannelMutation {
	return _c.mutation
}

// Save creates the Channel in the database.
func (_c *ChannelCreate) Save(ctx context.Context) (*Channel, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChannelCreate) SaveX(ctx context.Context) *Channel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChannelCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if channel.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized channel.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := channel.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if channel.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized channel.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := channel.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := channel.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.BalanceMethod(); !ok {
		v := channel.DefaultBalanceMethod
		_c.mutation.SetBalanceMethod(v)
	}
	if _, ok := _c.mutation.BalanceUnit(); !ok {
		v := channel.DefaultBalanceUnit
		_c.mutation.SetBalanceUnit(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChannelCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Channel.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Channel.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Channel.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := channel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Channel.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := channel.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Channel.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Channel.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := channel.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Channel.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.IconURL(); ok {
		if err := channel.IconURLValidator(v); err != nil {
			return &ValidationError{Name: "icon_url", err: fmt.Errorf(`ent: validator failed for field "Channel.icon_url": %w`, err)}
		}
	}
	if v, ok := _c.mutation.WebsiteURL(); ok {
		if err := channel.WebsiteURLValidator(v); err != nil {
			return &ValidationError{Name: "website_url", err: fmt.Errorf(`ent: validator failed for field "Channel.website_url": %w`, err)}
		}
	}
	if v, ok := _c.mutation.BalanceURL(); ok {
		if err := channel.BalanceURLValidator(v); err != nil {
			return &ValidationError{Name: "balance_url", err: fmt.Errorf(`ent: validator failed for field "Channel.balance_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BalanceMethod(); !ok {
		return &ValidationError{Name: "balance_method", err: errors.New(`ent: missing required field "Channel.balance_method"`)}
	}
	if v, ok := _c.mutation.BalanceMethod(); ok {
		if err := channel.BalanceMethodValidator(v); err != nil {
			return &ValidationError{Name: "balance_method", err: fmt.Errorf(`ent: validator failed for field "Channel.balance_method": %w`, err)}
		}
	}
	if v, ok := _c.mutation.BalancePath(); ok {
		if err := channel.BalancePathValidator(v); err != nil {
			return &ValidationError{Name: "balance_path", err: fmt.Errorf(`ent: validator failed for field "Channel.balance_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BalanceUnit(); !ok {
		return &ValidationError{Name: "balance_unit", err: errors.New(`ent: missing required field "Channel.balance_unit"`)}
	}
	if v, ok := _c.mutation.BalanceUnit(); ok {
		if err := channel.BalanceUnitValidator(v); err != nil {
			return &ValidationError{Name: "balance_unit", err: fmt.Errorf(`ent: validator failed for field "Channel.balance_unit": %w`, err)}
		}
	}
	return nil
}

func (_c *ChannelCreate) sqlSave(ctx context.Context) (*Channel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChannelCreate) createSpec() (*Channel, *sqlgraph.CreateSpec) {
	var (
		_node = &Channel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(channel.Table, sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(channel.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(channel.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(channel.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(channel.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(channel.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(channel.FieldPlatform, field.TypeString, value)
		_node.Platform = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(channel.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.IconURL(); ok {
		_spec.SetField(channel.FieldIconURL, field.TypeString, value)
		_node.IconURL = &value
	}
	if value, ok := _c.mutation.WebsiteURL(); ok {
		_spec.SetField(channel.FieldWebsiteURL, field.TypeString, value)
		_node.WebsiteURL = &value
	}
	if value, ok := _c.mutation.BalanceURL(); ok {
		_spec.SetField(channel.FieldBalanceURL, field.TypeString, value)
		_node.BalanceURL = &value
	}
	if value, ok := _c.mutation.BalanceMethod(); ok {
		_spec.SetField(channel.FieldBalanceMethod, field.TypeString, value)
		_node.BalanceMethod = value
	}
	if value, ok := _c.mutation.BalanceHeaders(); ok {
		_spec.SetField(channel.FieldBalanceHeaders, field.TypeJSON, value)
		_node.BalanceHeaders = value
	}
	if value, ok := _c.mutation.BalanceBody(); ok {
		_spec.SetField(channel.FieldBalanceBody, field.TypeString, value)
		_node.BalanceBody = &value
	}
	if value, ok := _c.mutation.BalancePath(); ok {
		_spec.SetField(channel.FieldBalancePath, field.TypeString, value)
		_node.BalancePath = &value
	}
	if value, ok := _c.mutation.BalanceUnit(); ok {
		_spec.SetField(channel.FieldBalanceUnit, field.TypeString, value)
		_node.BalanceUnit = value
	}
	if value, ok := _c.mutation.CachedBalance(); ok {
		_spec.SetField(channel.FieldCachedBalance, field.TypeFloat64, value)
		_node.CachedBalance = &value
	}
	if value, ok := _c.mutation.LastCheckAt(); ok {
		_spec.SetField(channel.FieldLastCheckAt, field.TypeTime, value)
		_node.LastCheckAt = &value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(channel.FieldLastError, field.TypeString, value)
		_node.LastError = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Channel.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChannelUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ChannelCreate) OnConflict(opts ...sql.ConflictOption) *ChannelUpsertOne {
	_c.conflict = opts
	return &ChannelUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Channel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChannelCreate) OnConflictColumns(columns ...string) *ChannelUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChannelUpsertOne{
		create: _c,
	}
}

type (
	// ChannelUpsertOne is the builder for "upsert"-ing
	//  one Channel node.
	ChannelUpsertOne struct {
		create *ChannelCreate
	}

	// ChannelUpsert is the "OnConflict" setter.
	ChannelUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ChannelUpsert) SetUpdatedAt(v time.Time) *ChannelUpsert {
	u.Set(channel.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChannelUpsert) UpdateUpdatedAt() *ChannelUpsert {
	u.SetExcluded(channel.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ChannelUpsert) SetDeletedAt(v time.Time) *ChannelUpsert {
	u.Set(channel.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ChannelUpsert) UpdateDeletedAt() *ChannelUpsert {
	u.SetExcluded(channel.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ChannelUpsert) ClearDeletedAt() *ChannelUpsert {
	u.SetNull(channel.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *ChannelUpsert) SetName(v string) *ChannelUpsert {
	u.Set(channel.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ChannelUpsert) UpdateName() *ChannelUpsert {
	u.SetExcluded(channel.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *ChannelUpsert) SetDescription(v string) *ChannelUpsert {
	u.Set(channel.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ChannelUpsert) UpdateDescription() *ChannelUpsert {
	u.SetExcluded(channel.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *ChannelUpsert) ClearDescription() *ChannelUpsert {
	u.SetNull(channel.FieldDescription)
	return u
}

// SetPlatform sets the "platform" field.
func (u *ChannelUpsert) SetPlatform(v string) *ChannelUpsert {
	u.Set(channel.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *ChannelUpsert) UpdatePlatform() *ChannelUpsert {
	u.SetExcluded(channel.FieldPlatform)
	return u
}

// ClearPlatform clears the value of the "platform" field.
func (u *ChannelUpsert) ClearPlatform() *ChannelUpsert {
	u.SetNull(channel.FieldPlatform)
	return u
}

// SetStatus sets the "status" field.
func (u *ChannelUpsert) SetStatus(v string) *ChannelUpsert {
	u.Set(channel.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChannelUpsert) UpdateStatus() *ChannelUpsert {
	u.SetExcluded(channel.FieldStatus)
	return u
}

// SetIconURL sets the "icon_url" field.
func (u *ChannelUpsert) SetIconURL(v string) *ChannelUpsert {
	u.Set(channel.FieldIconURL, v)
	return u
}

// UpdateIconURL sets the "icon_url" field to the value that was provided on create.
func (u *ChannelUpsert) UpdateIconURL() *ChannelUpsert {
	u.SetExcluded(channel.FieldIconURL)
	return u
}

// ClearIconURL clears the value of the "icon_url" field.
func (u *ChannelUpsert) ClearIconURL() *ChannelUpsert {
	u.SetNull(channel.FieldIconURL)
	return u
}

// SetWebsiteURL sets the "website_url" field.
func (u *ChannelUpsert) SetWebsiteURL(v string) *ChannelUpsert {
	u.Set(channel.FieldWebsiteURL, v)
	return u
}

// UpdateWebsiteURL sets the "website_url" field to the value that was provided on create.
func (u *ChannelUpsert) UpdateWebsiteURL() *ChannelUpsert {
	u.SetExcluded(channel.FieldWebsiteURL)
	return u
}

// ClearWebsiteURL clears the value of the "website_url" field.
func (u *ChannelUpsert) ClearWebsiteURL() *ChannelUpsert {
	u.SetNull(channel.FieldWebsiteURL)
	return u
}

// SetBalanceURL sets the "balance_url" field.
func (u *ChannelUpsert) SetBalanceURL(v string) *ChannelUpsert {
	u.Set(channel.FieldBalanceURL, v)
	return u
}

// UpdateBalanceURL sets the "balance_url" field to the value that was provided on create.
func (u *ChannelUpsert) UpdateBalanceURL() *ChannelUpsert {
	u.SetExcluded(channel.FieldBalanceURL)
	return u
}

// ClearBalanceURL clears the value of the "balance_url" field.
func (u *ChannelUpsert) ClearBalanceURL() *ChannelUpsert {
	u.SetNull(channel.FieldBalanceURL)
	return u
}

// SetBalanceMethod sets the "balance_method" field.
func (u *ChannelUpsert) SetBalanceMethod(v string) *ChannelUpsert {
	u.Set(channel.FieldBalanceMethod, v)
	return u
}

// UpdateBalanceMethod sets the "balance_method" field to the value that was provided on create.
func (u *ChannelUpsert) UpdateBalanceMethod() *ChannelUpsert {
	u.SetExcluded(channel.FieldBalanceMethod)
	return u
}

// SetBalanceHeaders sets the "balance_headers" field.
func (u *ChannelUpsert) SetBalanceHeaders(v map[string]string) *ChannelUpsert {
	u.Set(channel.FieldBalanceHeaders, v)
	return u
}

// UpdateBalanceHeaders sets the "balance_headers" field to the value that was provided on create.
func (u *ChannelUpsert) UpdateBalanceHeaders() *ChannelUpsert {
	u.SetExcluded(channel.FieldBalanceHeaders)
	return u
}

// ClearBalanceHeaders clears the value of the "balance_headers" field.
func (u *ChannelUpsert) ClearBalanceHeaders() *ChannelUpsert {
	u.SetNull(channel.FieldBalanceHeaders)
	return u
}

// SetBalanceBody sets the "balance_body" field.
func (u *ChannelUpsert) SetBalanceBody(v string) *ChannelUpsert {
	u.Set(channel.FieldBalanceBody, v)
	return u
}

// UpdateBalanceBody sets the "balance_body" field to the value that was provided on create.
func (u *ChannelUpsert) UpdateBalanceBody() *ChannelUpsert {
	u.SetExcluded(channel.FieldBalanceBody)
	return u
}

// ClearBalanceBody clears the value of the "balance_body" field.
func (u *ChannelUpsert) ClearBalanceBody() *ChannelUpsert {
	u.SetNull(channel.FieldBalanceBody)
	return u
}

// SetBalancePath sets the "balance_path" field.
func (u *ChannelUpsert) SetBalancePath(v string) *ChannelUpsert {
	u.Set(channel.FieldBalancePath, v)
	return u
}

// UpdateBalancePath sets the "balance_path" field to the value that was provided on create.
func (u *ChannelUpsert) UpdateBalancePath() *ChannelUpsert {
	u.SetExcluded(channel.FieldBalancePath)
	return u
}

// ClearBalancePath clears the value of the "balance_path" field.
func (u *ChannelUpsert) ClearBalancePath() *ChannelUpsert {
	u.SetNull(channel.FieldBalancePath)
	return u
}

// SetBalanceUnit sets the "balance_unit" field.
func (u *ChannelUpsert) SetBalanceUnit(v string) *ChannelUpsert {
	u.Set(channel.FieldBalanceUnit, v)
	return u
}

// UpdateBalanceUnit sets the "balance_unit" field to the value that was provided on create.
func (u *ChannelUpsert) UpdateBalanceUnit() *ChannelUpsert {
	u.SetExcluded(channel.FieldBalanceUnit)
	return u
}

// SetCachedBalance sets the "cached_balance" field.
func (u *ChannelUpsert) SetCachedBalance(v float64) *ChannelUpsert {
	u.Set(channel.FieldCachedBalance, v)
	return u
}

// UpdateCachedBalance sets the "cached_balance" field to the value that was provided on create.
func (u *ChannelUpsert) UpdateCachedBalance() *ChannelUpsert {
	u.SetExcluded(channel.FieldCachedBalance)
	return u
}

// AddCachedBalance adds v to the "cached_balance" field.
func (u *ChannelUpsert) AddCachedBalance(v float64) *ChannelUpsert {
	u.Add(channel.FieldCachedBalance, v)
	return u
}

// ClearCachedBalance clears the value of the "cached_balance" field.
func (u *ChannelUpsert) ClearCachedBalance() *ChannelUpsert {
	u.SetNull(channel.FieldCachedBalance)
	return u
}

// SetLastCheckAt sets the "last_check_at" field.
func (u *ChannelUpsert) SetLastCheckAt(v time.Time) *ChannelUpsert {
	u.Set(channel.FieldLastCheckAt, v)
	return u
}

// UpdateLastCheckAt sets the "last_check_at" field to the value that was provided on create.
func (u *ChannelUpsert) UpdateLastCheckAt() *ChannelUpsert {
	u.SetExcluded(channel.FieldLastCheckAt)
	return u
}

// ClearLastCheckAt clears the value of the "last_check_at" field.
func (u *ChannelUpsert) ClearLastCheckAt() *ChannelUpsert {
	u.SetNull(channel.FieldLastCheckAt)
	return u
}

// SetLastError sets the "last_error" field.
func (u *ChannelUpsert) SetLastError(v string) *ChannelUpsert {
	u.Set(channel.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *ChannelUpsert) UpdateLastError() *ChannelUpsert {
	u.SetExcluded(channel.FieldLastError)
	return u
}

// ClearLastError clears the value of the "last_error" field.
func (u *ChannelUpsert) ClearLastError() *ChannelUpsert {
	u.SetNull(channel.FieldLastError)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Channel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChannelUpsertOne) UpdateNewValues() *ChannelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(channel.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Channel.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChannelUpsertOne) Ignore() *ChannelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChannelUpsertOne) DoNothing() *ChannelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChannelCreate.OnConflict
// documentation for more info.
func (u *ChannelUpsertOne) Update(set func(*ChannelUpsert)) *ChannelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChannelUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChannelUpsertOne) SetUpdatedAt(v time.Time) *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChannelUpsertOne) UpdateUpdatedAt() *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ChannelUpsertOne) SetDeletedAt(v time.Time) *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ChannelUpsertOne) UpdateDeletedAt() *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ChannelUpsertOne) ClearDeletedAt() *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *ChannelUpsertOne) SetName(v string) *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ChannelUpsertOne) UpdateName() *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *ChannelUpsertOne) SetDescription(v string) *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ChannelUpsertOne) UpdateDescription() *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *ChannelUpsertOne) ClearDescription() *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.ClearDescription()
	})
}

// SetPlatform sets the "platform" field.
func (u *ChannelUpsertOne) SetPlatform(v string) *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *ChannelUpsertOne) UpdatePlatform() *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdatePlatform()
	})
}

// ClearPlatform clears the value of the "platform" field.
func (u *ChannelUpsertOne) ClearPlatform() *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.ClearPlatform()
	})
}

// SetStatus sets the "status" field.
func (u *ChannelUpsertOne) SetStatus(v string) *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChannelUpsertOne) UpdateStatus() *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateStatus()
	})
}

// SetIconURL sets the "icon_url" field.
func (u *ChannelUpsertOne) SetIconURL(v string) *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.SetIconURL(v)
	})
}

// UpdateIconURL sets the "icon_url" field to the value that was provided on create.
func (u *ChannelUpsertOne) UpdateIconURL() *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateIconURL()
	})
}

// ClearIconURL clears the value of the "icon_url" field.
func (u *ChannelUpsertOne) ClearIconURL() *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.ClearIconURL()
	})
}

// SetWebsiteURL sets the "website_url" field.
func (u *ChannelUpsertOne) SetWebsiteURL(v string) *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.SetWebsiteURL(v)
	})
}

// UpdateWebsiteURL sets the "website_url" field to the value that was provided on create.
func (u *ChannelUpsertOne) UpdateWebsiteURL() *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateWebsiteURL()
	})
}

// ClearWebsiteURL clears the value of the "website_url" field.
func (u *ChannelUpsertOne) ClearWebsiteURL() *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.ClearWebsiteURL()
	})
}

// SetBalanceURL sets the "balance_url" field.
func (u *ChannelUpsertOne) SetBalanceURL(v string) *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.SetBalanceURL(v)
	})
}

// UpdateBalanceURL sets the "balance_url" field to the value that was provided on create.
func (u *ChannelUpsertOne) UpdateBalanceURL() *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateBalanceURL()
	})
}

// ClearBalanceURL clears the value of the "balance_url" field.
func (u *ChannelUpsertOne) ClearBalanceURL() *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.ClearBalanceURL()
	})
}

// SetBalanceMethod sets the "balance_method" field.
func (u *ChannelUpsertOne) SetBalanceMethod(v string) *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.SetBalanceMethod(v)
	})
}

// UpdateBalanceMethod sets the "balance_method" field to the value that was provided on create.
func (u *ChannelUpsertOne) UpdateBalanceMethod() *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateBalanceMethod()
	})
}

// SetBalanceHeaders sets the "balance_headers" field.
func (u *ChannelUpsertOne) SetBalanceHeaders(v map[string]string) *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.SetBalanceHeaders(v)
	})
}

// UpdateBalanceHeaders sets the "balance_headers" field to the value that was provided on create.
func (u *ChannelUpsertOne) UpdateBalanceHeaders() *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateBalanceHeaders()
	})
}

// ClearBalanceHeaders clears the value of the "balance_headers" field.
func (u *ChannelUpsertOne) ClearBalanceHeaders() *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.ClearBalanceHeaders()
	})
}

// SetBalanceBody sets the "balance_body" field.
func (u *ChannelUpsertOne) SetBalanceBody(v string) *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.SetBalanceBody(v)
	})
}

// UpdateBalanceBody sets the "balance_body" field to the value that was provided on create.
func (u *ChannelUpsertOne) UpdateBalanceBody() *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateBalanceBody()
	})
}

// ClearBalanceBody clears the value of the "balance_body" field.
func (u *ChannelUpsertOne) ClearBalanceBody() *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.ClearBalanceBody()
	})
}

// SetBalancePath sets the "balance_path" field.
func (u *ChannelUpsertOne) SetBalancePath(v string) *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.SetBalancePath(v)
	})
}

// UpdateBalancePath sets the "balance_path" field to the value that was provided on create.
func (u *ChannelUpsertOne) UpdateBalancePath() *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateBalancePath()
	})
}

// ClearBalancePath clears the value of the "balance_path" field.
func (u *ChannelUpsertOne) ClearBalancePath() *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.ClearBalancePath()
	})
}

// SetBalanceUnit sets the "balance_unit" field.
func (u *ChannelUpsertOne) SetBalanceUnit(v string) *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.SetBalanceUnit(v)
	})
}

// UpdateBalanceUnit sets the "balance_unit" field to the value that was provided on create.
func (u *ChannelUpsertOne) UpdateBalanceUnit() *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateBalanceUnit()
	})
}

// SetCachedBalance sets the "cached_balance" field.
func (u *ChannelUpsertOne) SetCachedBalance(v float64) *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.SetCachedBalance(v)
	})
}

// AddCachedBalance adds v to the "cached_balance" field.
func (u *ChannelUpsertOne) AddCachedBalance(v float64) *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.AddCachedBalance(v)
	})
}

// UpdateCachedBalance sets the "cached_balance" field to the value that was provided on create.
func (u *ChannelUpsertOne) UpdateCachedBalance() *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateCachedBalance()
	})
}

// ClearCachedBalance clears the value of the "cached_balance" field.
func (u *ChannelUpsertOne) ClearCachedBalance() *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.ClearCachedBalance()
	})
}

// SetLastCheckAt sets the "last_check_at" field.
func (u *ChannelUpsertOne) SetLastCheckAt(v time.Time) *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.SetLastCheckAt(v)
	})
}

// UpdateLastCheckAt sets the "last_check_at" field to the value that was provided on create.
func (u *ChannelUpsertOne) UpdateLastCheckAt() *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateLastCheckAt()
	})
}

// ClearLastCheckAt clears the value of the "last_check_at" field.
func (u *ChannelUpsertOne) ClearLastCheckAt() *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.ClearLastCheckAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *ChannelUpsertOne) SetLastError(v string) *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *ChannelUpsertOne) UpdateLastError() *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *ChannelUpsertOne) ClearLastError() *ChannelUpsertOne {
	return u.Update(func(s *ChannelUpsert) {
		s.ClearLastError()
	})
}

// Exec executes the query.
func (u *ChannelUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChannelCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChannelUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChannelUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChannelUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChannelCreateBulk is the builder for creating many Channel entities in bulk.
type ChannelCreateBulk struct {
	config
	err      error
	builders []*ChannelCreate
	conflict []sql.ConflictOption
}

// Save creates the Channel entities in the database.
func (_c *ChannelCreateBulk) Save(ctx context.Context) ([]*Channel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Channel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChannelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChannelCreateBulk) SaveX(ctx context.Context) []*Channel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Channel.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChannelUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ChannelCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChannelUpsertBulk {
	_c.conflict = opts
	return &ChannelUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Channel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChannelCreateBulk) OnConflictColumns(columns ...string) *ChannelUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChannelUpsertBulk{
		create: _c,
	}
}

// ChannelUpsertBulk is the builder for "upsert"-ing
// a bulk of Channel nodes.
type ChannelUpsertBulk struct {
	create *ChannelCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Channel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChannelUpsertBulk) UpdateNewValues() *ChannelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(channel.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Channel.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChannelUpsertBulk) Ignore() *ChannelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChannelUpsertBulk) DoNothing() *ChannelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChannelCreateBulk.OnConflict
// documentation for more info.
func (u *ChannelUpsertBulk) Update(set func(*ChannelUpsert)) *ChannelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChannelUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChannelUpsertBulk) SetUpdatedAt(v time.Time) *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChannelUpsertBulk) UpdateUpdatedAt() *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ChannelUpsertBulk) SetDeletedAt(v time.Time) *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ChannelUpsertBulk) UpdateDeletedAt() *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ChannelUpsertBulk) ClearDeletedAt() *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *ChannelUpsertBulk) SetName(v string) *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ChannelUpsertBulk) UpdateName() *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *ChannelUpsertBulk) SetDescription(v string) *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ChannelUpsertBulk) UpdateDescription() *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *ChannelUpsertBulk) ClearDescription() *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.ClearDescription()
	})
}

// SetPlatform sets the "platform" field.
func (u *ChannelUpsertBulk) SetPlatform(v string) *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *ChannelUpsertBulk) UpdatePlatform() *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdatePlatform()
	})
}

// ClearPlatform clears the value of the "platform" field.
func (u *ChannelUpsertBulk) ClearPlatform() *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.ClearPlatform()
	})
}

// SetStatus sets the "status" field.
func (u *ChannelUpsertBulk) SetStatus(v string) *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChannelUpsertBulk) UpdateStatus() *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateStatus()
	})
}

// SetIconURL sets the "icon_url" field.
func (u *ChannelUpsertBulk) SetIconURL(v string) *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.SetIconURL(v)
	})
}

// UpdateIconURL sets the "icon_url" field to the value that was provided on create.
func (u *ChannelUpsertBulk) UpdateIconURL() *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateIconURL()
	})
}

// ClearIconURL clears the value of the "icon_url" field.
func (u *ChannelUpsertBulk) ClearIconURL() *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.ClearIconURL()
	})
}

// SetWebsiteURL sets the "website_url" field.
func (u *ChannelUpsertBulk) SetWebsiteURL(v string) *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.SetWebsiteURL(v)
	})
}

// UpdateWebsiteURL sets the "website_url" field to the value that was provided on create.
func (u *ChannelUpsertBulk) UpdateWebsiteURL() *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateWebsiteURL()
	})
}

// ClearWebsiteURL clears the value of the "website_url" field.
func (u *ChannelUpsertBulk) ClearWebsiteURL() *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.ClearWebsiteURL()
	})
}

// SetBalanceURL sets the "balance_url" field.
func (u *ChannelUpsertBulk) SetBalanceURL(v string) *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.SetBalanceURL(v)
	})
}

// UpdateBalanceURL sets the "balance_url" field to the value that was provided on create.
func (u *ChannelUpsertBulk) UpdateBalanceURL() *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateBalanceURL()
	})
}

// ClearBalanceURL clears the value of the "balance_url" field.
func (u *ChannelUpsertBulk) ClearBalanceURL() *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.ClearBalanceURL()
	})
}

// SetBalanceMethod sets the "balance_method" field.
func (u *ChannelUpsertBulk) SetBalanceMethod(v string) *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.SetBalanceMethod(v)
	})
}

// UpdateBalanceMethod sets the "balance_method" field to the value that was provided on create.
func (u *ChannelUpsertBulk) UpdateBalanceMethod() *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateBalanceMethod()
	})
}

// SetBalanceHeaders sets the "balance_headers" field.
func (u *ChannelUpsertBulk) SetBalanceHeaders(v map[string]string) *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.SetBalanceHeaders(v)
	})
}

// UpdateBalanceHeaders sets the "balance_headers" field to the value that was provided on create.
func (u *ChannelUpsertBulk) UpdateBalanceHeaders() *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateBalanceHeaders()
	})
}

// ClearBalanceHeaders clears the value of the "balance_headers" field.
func (u *ChannelUpsertBulk) ClearBalanceHeaders() *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.ClearBalanceHeaders()
	})
}

// SetBalanceBody sets the "balance_body" field.
func (u *ChannelUpsertBulk) SetBalanceBody(v string) *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.SetBalanceBody(v)
	})
}

// UpdateBalanceBody sets the "balance_body" field to the value that was provided on create.
func (u *ChannelUpsertBulk) UpdateBalanceBody() *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateBalanceBody()
	})
}

// ClearBalanceBody clears the value of the "balance_body" field.
func (u *ChannelUpsertBulk) ClearBalanceBody() *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.ClearBalanceBody()
	})
}

// SetBalancePath sets the "balance_path" field.
func (u *ChannelUpsertBulk) SetBalancePath(v string) *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.SetBalancePath(v)
	})
}

// UpdateBalancePath sets the "balance_path" field to the value that was provided on create.
func (u *ChannelUpsertBulk) UpdateBalancePath() *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateBalancePath()
	})
}

// ClearBalancePath clears the value of the "balance_path" field.
func (u *ChannelUpsertBulk) ClearBalancePath() *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.ClearBalancePath()
	})
}

// SetBalanceUnit sets the "balance_unit" field.
func (u *ChannelUpsertBulk) SetBalanceUnit(v string) *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.SetBalanceUnit(v)
	})
}

// UpdateBalanceUnit sets the "balance_unit" field to the value that was provided on create.
func (u *ChannelUpsertBulk) UpdateBalanceUnit() *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateBalanceUnit()
	})
}

// SetCachedBalance sets the "cached_balance" field.
func (u *ChannelUpsertBulk) SetCachedBalance(v float64) *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.SetCachedBalance(v)
	})
}

// AddCachedBalance adds v to the "cached_balance" field.
func (u *ChannelUpsertBulk) AddCachedBalance(v float64) *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.AddCachedBalance(v)
	})
}

// UpdateCachedBalance sets the "cached_balance" field to the value that was provided on create.
func (u *ChannelUpsertBulk) UpdateCachedBalance() *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateCachedBalance()
	})
}

// ClearCachedBalance clears the value of the "cached_balance" field.
func (u *ChannelUpsertBulk) ClearCachedBalance() *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.ClearCachedBalance()
	})
}

// SetLastCheckAt sets the "last_check_at" field.
func (u *ChannelUpsertBulk) SetLastCheckAt(v time.Time) *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.SetLastCheckAt(v)
	})
}

// UpdateLastCheckAt sets the "last_check_at" field to the value that was provided on create.
func (u *ChannelUpsertBulk) UpdateLastCheckAt() *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateLastCheckAt()
	})
}

// ClearLastCheckAt clears the value of the "last_check_at" field.
func (u *ChannelUpsertBulk) ClearLastCheckAt() *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.ClearLastCheckAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *ChannelUpsertBulk) SetLastError(v string) *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *ChannelUpsertBulk) UpdateLastError() *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *ChannelUpsertBulk) ClearLastError() *ChannelUpsertBulk {
	return u.Update(func(s *ChannelUpsert) {
		s.ClearLastError()
	})
}

// Exec executes the query.
func (u *ChannelUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChannelCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChannelCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChannelUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
