// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/chatconversation"
	"github.com/Wei-Shaw/sub2api/ent/chatmessage"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ChatConversationUpdate is the builder for updating ChatConversation entities.
type ChatConversationUpdate struct {
	config
	hooks    []Hook
	mutation *ChatConversationMutation
}

// Where appends a list predicates to the ChatConversationUpdate builder.
func (_u *ChatConversationUpdate) Where(ps ...predicate.ChatConversation) *ChatConversationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGuestToken sets the "guest_token" field.
func (_u *ChatConversationUpdate) SetGuestToken(v string) *ChatConversationUpdate {
	_u.mutation.SetGuestToken(v)
	return _u
}

// SetNillableGuestToken sets the "guest_token" field if the given value is not nil.
func (_u *ChatConversationUpdate) SetNillableGuestToken(v *string) *ChatConversationUpdate {
	if v != nil {
		_u.SetGuestToken(*v)
	}
	return _u
}

// ClearGuestToken clears the value of the "guest_token" field.
func (_u *ChatConversationUpdate) ClearGuestToken() *ChatConversationUpdate {
	_u.mutation.ClearGuestToken()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ChatConversationUpdate) SetUserID(v int64) *ChatConversationUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ChatConversationUpdate) SetNillableUserID(v *int64) *ChatConversationUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ChatConversationUpdate) AddUserID(v int64) *ChatConversationUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *ChatConversationUpdate) ClearUserID() *ChatConversationUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetVisitorName sets the "visitor_name" field.
func (_u *ChatConversationUpdate) SetVisitorName(v string) *ChatConversationUpdate {
	_u.mutation.SetVisitorName(v)
	return _u
}

// SetNillableVisitorName sets the "visitor_name" field if the given value is not nil.
func (_u *ChatConversationUpdate) SetNillableVisitorName(v *string) *ChatConversationUpdate {
	if v != nil {
		_u.SetVisitorName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ChatConversationUpdate) SetStatus(v string) *ChatConversationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ChatConversationUpdate) SetNillableStatus(v *string) *ChatConversationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAdminUnreadCount sets the "admin_unread_count" field.
func (_u *ChatConversationUpdate) SetAdminUnreadCount(v int) *ChatConversationUpdate {
	_u.mutation.ResetAdminUnreadCount()
	_u.mutation.SetAdminUnreadCount(v)
	return _u
}

// SetNillableAdminUnreadCount sets the "admin_unread_count" field if the given value is not nil.
func (_u *ChatConversationUpdate) SetNillableAdminUnreadCount(v *int) *ChatConversationUpdate {
	if v != nil {
		_u.SetAdminUnreadCount(*v)
	}
	return _u
}

// AddAdminUnreadCount adds value to the "admin_unread_count" field.
func (_u *ChatConversationUpdate) AddAdminUnreadCount(v int) *ChatConversationUpdate {
	_u.mutation.AddAdminUnreadCount(v)
	return _u
}

// SetLastMessageAt sets the "last_message_at" field.
func (_u *ChatConversationUpdate) SetLastMessageAt(v time.Time) *ChatConversationUpdate {
	_u.mutation.SetLastMessageAt(v)
	return _u
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_u *ChatConversationUpdate) SetNillableLastMessageAt(v *time.Time) *ChatConversationUpdate {
	if v != nil {
		_u.SetLastMessageAt(*v)
	}
	return _u
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (_u *ChatConversationUpdate) ClearLastMessageAt() *ChatConversationUpdate {
	_u.mutation.ClearLastMessageAt()
	return _u
}

// SetLastMessagePreview sets the "last_message_preview" field.
func (_u *ChatConversationUpdate) SetLastMessagePreview(v string) *ChatConversationUpdate {
	_u.mutation.SetLastMessagePreview(v)
	return _u
}

// SetNillableLastMessagePreview sets the "last_message_preview" field if the given value is not nil.
func (_u *ChatConversationUpdate) SetNillableLastMessagePreview(v *string) *ChatConversationUpdate {
	if v != nil {
		_u.SetLastMessagePreview(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChatConversationUpdate) SetUpdatedAt(v time.Time) *ChatConversationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddMessageIDs adds the "messages" edge to the ChatMessage entity by IDs.
func (_u *ChatConversationUpdate) AddMessageIDs(ids ...int64) *ChatConversationUpdate {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the ChatMessage entity.
func (_u *ChatConversationUpdate) AddMessages(v ...*ChatMessage) *ChatConversationUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the ChatConversationMutation object of the builder.
func (_u *ChatConversationUpdate) Mutation() *ChatConversationMutation {
	return _u.mutation
}

// ClearMessages clears all "messages" edges to the ChatMessage entity.
func (_u *ChatConversationUpdate) ClearMessages() *ChatConversationUpdate {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to ChatMessage entities by IDs.
func (_u *ChatConversationUpdate) RemoveMessageIDs(ids ...int64) *ChatConversationUpdate {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to ChatMessage entities.
func (_u *ChatConversationUpdate) RemoveMessages(v ...*ChatMessage) *ChatConversationUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChatConversationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatConversationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChatConversationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatConversationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChatConversationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := chatconversation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatConversationUpdate) check() error {
	if v, ok := _u.mutation.GuestToken(); ok {
		if err := chatconversation.GuestTokenValidator(v); err != nil {
			return &ValidationError{Name: "guest_token", err: fmt.Errorf(`ent: validator failed for field "ChatConversation.guest_token": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VisitorName(); ok {
		if err := chatconversation.VisitorNameValidator(v); err != nil {
			return &ValidationError{Name: "visitor_name", err: fmt.Errorf(`ent: validator failed for field "ChatConversation.visitor_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := chatconversation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ChatConversation.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastMessagePreview(); ok {
		if err := chatconversation.LastMessagePreviewValidator(v); err != nil {
			return &ValidationError{Name: "last_message_preview", err: fmt.Errorf(`ent: validator failed for field "ChatConversation.last_message_preview": %w`, err)}
		}
	}
	return nil
}

func (_u *ChatConversationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatconversation.Table, chatconversation.Columns, sqlgraph.NewFieldSpec(chatconversation.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GuestToken(); ok {
		_spec.SetField(chatconversation.FieldGuestToken, field.TypeString, value)
	}
	if _u.mutation.GuestTokenCleared() {
		_spec.ClearField(chatconversation.FieldGuestToken, field.TypeString)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(chatconversation.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(chatconversation.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(chatconversation.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.VisitorName(); ok {
		_spec.SetField(chatconversation.FieldVisitorName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(chatconversation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AdminUnreadCount(); ok {
		_spec.SetField(chatconversation.FieldAdminUnreadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAdminUnreadCount(); ok {
		_spec.AddField(chatconversation.FieldAdminUnreadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastMessageAt(); ok {
		_spec.SetField(chatconversation.FieldLastMessageAt, field.TypeTime, value)
	}
	if _u.mutation.LastMessageAtCleared() {
		_spec.ClearField(chatconversation.FieldLastMessageAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastMessagePreview(); ok {
		_spec.SetField(chatconversation.FieldLastMessagePreview, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(chatconversation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatconversation.MessagesTable,
			Columns: []string{chatconversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatconversation.MessagesTable,
			Columns: []string{chatconversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatconversation.MessagesTable,
			Columns: []string{chatconversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatconversation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChatConversationUpdateOne is the builder for updating a single ChatConversation entity.
type ChatConversationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChatConversationMutation
}

// SetGuestToken sets the "guest_token" field.
func (_u *ChatConversationUpdateOne) SetGuestToken(v string) *ChatConversationUpdateOne {
	_u.mutation.SetGuestToken(v)
	return _u
}

// SetNillableGuestToken sets the "guest_token" field if the given value is not nil.
func (_u *ChatConversationUpdateOne) SetNillableGuestToken(v *string) *ChatConversationUpdateOne {
	if v != nil {
		_u.SetGuestToken(*v)
	}
	return _u
}

// ClearGuestToken clears the value of the "guest_token" field.
func (_u *ChatConversationUpdateOne) ClearGuestToken() *ChatConversationUpdateOne {
	_u.mutation.ClearGuestToken()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ChatConversationUpdateOne) SetUserID(v int64) *ChatConversationUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ChatConversationUpdateOne) SetNillableUserID(v *int64) *ChatConversationUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ChatConversationUpdateOne) AddUserID(v int64) *ChatConversationUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *ChatConversationUpdateOne) ClearUserID() *ChatConversationUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetVisitorName sets the "visitor_name" field.
func (_u *ChatConversationUpdateOne) SetVisitorName(v string) *ChatConversationUpdateOne {
	_u.mutation.SetVisitorName(v)
	return _u
}

// SetNillableVisitorName sets the "visitor_name" field if the given value is not nil.
func (_u *ChatConversationUpdateOne) SetNillableVisitorName(v *string) *ChatConversationUpdateOne {
	if v != nil {
		_u.SetVisitorName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ChatConversationUpdateOne) SetStatus(v string) *ChatConversationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ChatConversationUpdateOne) SetNillableStatus(v *string) *ChatConversationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAdminUnreadCount sets the "admin_unread_count" field.
func (_u *ChatConversationUpdateOne) SetAdminUnreadCount(v int) *ChatConversationUpdateOne {
	_u.mutation.ResetAdminUnreadCount()
	_u.mutation.SetAdminUnreadCount(v)
	return _u
}

// SetNillableAdminUnreadCount sets the "admin_unread_count" field if the given value is not nil.
func (_u *ChatConversationUpdateOne) SetNillableAdminUnreadCount(v *int) *ChatConversationUpdateOne {
	if v != nil {
		_u.SetAdminUnreadCount(*v)
	}
	return _u
}

// AddAdminUnreadCount adds value to the "admin_unread_count" field.
func (_u *ChatConversationUpdateOne) AddAdminUnreadCount(v int) *ChatConversationUpdateOne {
	_u.mutation.AddAdminUnreadCount(v)
	return _u
}

// SetLastMessageAt sets the "last_message_at" field.
func (_u *ChatConversationUpdateOne) SetLastMessageAt(v time.Time) *ChatConversationUpdateOne {
	_u.mutation.SetLastMessageAt(v)
	return _u
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_u *ChatConversationUpdateOne) SetNillableLastMessageAt(v *time.Time) *ChatConversationUpdateOne {
	if v != nil {
		_u.SetLastMessageAt(*v)
	}
	return _u
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (_u *ChatConversationUpdateOne) ClearLastMessageAt() *ChatConversationUpdateOne {
	_u.mutation.ClearLastMessageAt()
	return _u
}

// SetLastMessagePreview sets the "last_message_preview" field.
func (_u *ChatConversationUpdateOne) SetLastMessagePreview(v string) *ChatConversationUpdateOne {
	_u.mutation.SetLastMessagePreview(v)
	return _u
}

// SetNillableLastMessagePreview sets the "last_message_preview" field if the given value is not nil.
func (_u *ChatConversationUpdateOne) SetNillableLastMessagePreview(v *string) *ChatConversationUpdateOne {
	if v != nil {
		_u.SetLastMessagePreview(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChatConversationUpdateOne) SetUpdatedAt(v time.Time) *ChatConversationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddMessageIDs adds the "messages" edge to the ChatMessage entity by IDs.
func (_u *ChatConversationUpdateOne) AddMessageIDs(ids ...int64) *ChatConversationUpdateOne {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the ChatMessage entity.
func (_u *ChatConversationUpdateOne) AddMessages(v ...*ChatMessage) *ChatConversationUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the ChatConversationMutation object of the builder.
func (_u *ChatConversationUpdateOne) Mutation() *ChatConversationMutation {
	return _u.mutation
}

// ClearMessages clears all "messages" edges to the ChatMessage entity.
func (_u *ChatConversationUpdateOne) ClearMessages() *ChatConversationUpdateOne {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to ChatMessage entities by IDs.
func (_u *ChatConversationUpdateOne) RemoveMessageIDs(ids ...int64) *ChatConversationUpdateOne {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to ChatMessage entities.
func (_u *ChatConversationUpdateOne) RemoveMessages(v ...*ChatMessage) *ChatConversationUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Where appends a list predicates to the ChatConversationUpdate builder.
func (_u *ChatConversationUpdateOne) Where(ps ...predicate.ChatConversation) *ChatConversationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChatConversationUpdateOne) Select(field string, fields ...string) *ChatConversationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChatConversation entity.
func (_u *ChatConversationUpdateOne) Save(ctx context.Context) (*ChatConversation, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatConversationUpdateOne) SaveX(ctx context.Context) *ChatConversation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChatConversationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatConversationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChatConversationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := chatconversation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatConversationUpdateOne) check() error {
	if v, ok := _u.mutation.GuestToken(); ok {
		if err := chatconversation.GuestTokenValidator(v); err != nil {
			return &ValidationError{Name: "guest_token", err: fmt.Errorf(`ent: validator failed for field "ChatConversation.guest_token": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VisitorName(); ok {
		if err := chatconversation.VisitorNameValidator(v); err != nil {
			return &ValidationError{Name: "visitor_name", err: fmt.Errorf(`ent: validator failed for field "ChatConversation.visitor_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := chatconversation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ChatConversation.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastMessagePreview(); ok {
		if err := chatconversation.LastMessagePreviewValidator(v); err != nil {
			return &ValidationError{Name: "last_message_preview", err: fmt.Errorf(`ent: validator failed for field "ChatConversation.last_message_preview": %w`, err)}
		}
	}
	return nil
}

func (_u *ChatConversationUpdateOne) sqlSave(ctx context.Context) (_node *ChatConversation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatconversation.Table, chatconversation.Columns, sqlgraph.NewFieldSpec(chatconversation.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChatConversation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chatconversation.FieldID)
		for _, f := range fields {
			if !chatconversation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chatconversation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GuestToken(); ok {
		_spec.SetField(chatconversation.FieldGuestToken, field.TypeString, value)
	}
	if _u.mutation.GuestTokenCleared() {
		_spec.ClearField(chatconversation.FieldGuestToken, field.TypeString)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(chatconversation.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(chatconversation.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(chatconversation.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.VisitorName(); ok {
		_spec.SetField(chatconversation.FieldVisitorName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(chatconversation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AdminUnreadCount(); ok {
		_spec.SetField(chatconversation.FieldAdminUnreadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAdminUnreadCount(); ok {
		_spec.AddField(chatconversation.FieldAdminUnreadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastMessageAt(); ok {
		_spec.SetField(chatconversation.FieldLastMessageAt, field.TypeTime, value)
	}
	if _u.mutation.LastMessageAtCleared() {
		_spec.ClearField(chatconversation.FieldLastMessageAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastMessagePreview(); ok {
		_spec.SetField(chatconversation.FieldLastMessagePreview, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(chatconversation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatconversation.MessagesTable,
			Columns: []string{chatconversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatconversation.MessagesTable,
			Columns: []string{chatconversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatconversation.MessagesTable,
			Columns: []string{chatconversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ChatConversation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatconversation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
