// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/chatconversation"
	"github.com/Wei-Shaw/sub2api/ent/chatmessage"
)

// ChatConversationCreate is the builder for creating a ChatConversation entity.
type ChatConversationCreate struct {
	config
	mutation *ChatConversationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetGuestToken sets the "guest_token" field.
func (_c *ChatConversationCreate) SetGuestToken(v string) *ChatConversationCreate {
	_c.mutation.SetGuestToken(v)
	return _c
}

// SetNillableGuestToken sets the "guest_token" field if the given value is not nil.
func (_c *ChatConversationCreate) SetNillableGuestToken(v *string) *ChatConversationCreate {
	if v != nil {
		_c.SetGuestToken(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ChatConversationCreate) SetUserID(v int64) *ChatConversationCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *ChatConversationCreate) SetNillableUserID(v *int64) *ChatConversationCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetVisitorName sets the "visitor_name" field.
func (_c *ChatConversationCreate) SetVisitorName(v string) *ChatConversationCreate {
	_c.mutation.SetVisitorName(v)
	return _c
}

// SetNillableVisitorName sets the "visitor_name" field if the given value is not nil.
func (_c *ChatConversationCreate) SetNillableVisitorName(v *string) *ChatConversationCreate {
	if v != nil {
		_c.SetVisitorName(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ChatConversationCreate) SetStatus(v string) *ChatConversationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ChatConversationCreate) SetNillableStatus(v *string) *ChatConversationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAdminUnreadCount sets the "admin_unread_count" field.
func (_c *ChatConversationCreate) SetAdminUnreadCount(v int) *ChatConversationCreate {
	_c.mutation.SetAdminUnreadCount(v)
	return _c
}

// SetNillableAdminUnreadCount sets the "admin_unread_count" field if the given value is not nil.
func (_c *ChatConversationCreate) SetNillableAdminUnreadCount(v *int) *ChatConversationCreate {
	if v != nil {
		_c.SetAdminUnreadCount(*v)
	}
	return _c
}

// SetLastMessageAt sets the "last_message_at" field.
func (_c *ChatConversationCreate) SetLastMessageAt(v time.Time) *ChatConversationCreate {
	_c.mutation.SetLastMessageAt(v)
	return _c
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_c *ChatConversationCreate) SetNillableLastMessageAt(v *time.Time) *ChatConversationCreate {
	if v != nil {
		_c.SetLastMessageAt(*v)
	}
	return _c
}

// SetLastMessagePreview sets the "last_message_preview" field.
func (_c *ChatConversationCreate) SetLastMessagePreview(v string) *ChatConversationCreate {
	_c.mutation.SetLastMessagePreview(v)
	return _c
}

// SetNillableLastMessagePreview sets the "last_message_preview" field if the given value is not nil.
func (_c *ChatConversationCreate) SetNillableLastMessagePreview(v *string) *ChatConversationCreate {
	if v != nil {
		_c.SetLastMessagePreview(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChatConversationCreate) SetCreatedAt(v time.Time) *ChatConversationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChatConversationCreate) SetNillableCreatedAt(v *time.Time) *ChatConversationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChatConversationCreate) SetUpdatedAt(v time.Time) *ChatConversationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChatConversationCreate) SetNillableUpdatedAt(v *time.Time) *ChatConversationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddMessageIDs adds the "messages" edge to the ChatMessage entity by IDs.
func (_c *ChatConversationCreate) AddMessageIDs(ids ...int64) *ChatConversationCreate {
	_c.mutation.AddMessageIDs(ids...)
	return _c
}

// AddMessages adds the "messages" edges to the ChatMessage entity.
func (_c *ChatConversationCreate) AddMessages(v ...*ChatMessage) *ChatConversationCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMessageIDs(ids...)
}

// Mutation returns the ChatConversationMutation object of the builder.
func (_c *ChatConversationCreate) Mutation() *ChatConversationMutation {
	return _c.mutation
}

// Save creates the ChatConversation in the database.
func (_c *ChatConversationCreate) Save(ctx context.Context) (*ChatConversation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChatConversationCreate) SaveX(ctx context.Context) *ChatConversation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatConversationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatConversationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChatConversationCreate) defaults() {
	if _, ok := _c.mutation.VisitorName(); !ok {
		v := chatconversation.DefaultVisitorName
		_c.mutation.SetVisitorName(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := chatconversation.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.AdminUnreadCount(); !ok {
		v := chatconversation.DefaultAdminUnreadCount
		_c.mutation.SetAdminUnreadCount(v)
	}
	if _, ok := _c.mutation.LastMessagePreview(); !ok {
		v := chatconversation.DefaultLastMessagePreview
		_c.mutation.SetLastMessagePreview(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := chatconversation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := chatconversation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChatConversationCreate) check() error {
	if v, ok := _c.mutation.GuestToken(); ok {
		if err := chatconversation.GuestTokenValidator(v); err != nil {
			return &ValidationError{Name: "guest_token", err: fmt.Errorf(`ent: validator failed for field "ChatConversation.guest_token": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VisitorName(); !ok {
		return &ValidationError{Name: "visitor_name", err: errors.New(`ent: missing required field "ChatConversation.visitor_name"`)}
	}
	if v, ok := _c.mutation.VisitorName(); ok {
		if err := chatconversation.VisitorNameValidator(v); err != nil {
			return &ValidationError{Name: "visitor_name", err: fmt.Errorf(`ent: validator failed for field "ChatConversation.visitor_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ChatConversation.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := chatconversation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ChatConversation.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AdminUnreadCount(); !ok {
		return &ValidationError{Name: "admin_unread_count", err: errors.New(`ent: missing required field "ChatConversation.admin_unread_count"`)}
	}
	if _, ok := _c.mutation.LastMessagePreview(); !ok {
		return &ValidationError{Name: "last_message_preview", err: errors.New(`ent: missing required field "ChatConversation.last_message_preview"`)}
	}
	if v, ok := _c.mutation.LastMessagePreview(); ok {
		if err := chatconversation.LastMessagePreviewValidator(v); err != nil {
			return &ValidationError{Name: "last_message_preview", err: fmt.Errorf(`ent: validator failed for field "ChatConversation.last_message_preview": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChatConversation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ChatConversation.updated_at"`)}
	}
	return nil
}

func (_c *ChatConversationCreate) sqlSave(ctx context.Context) (*ChatConversation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChatConversationCreate) createSpec() (*ChatConversation, *sqlgraph.CreateSpec) {
	var (
		_node = &ChatConversation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chatconversation.Table, sqlgraph.NewFieldSpec(chatconversation.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.GuestToken(); ok {
		_spec.SetField(chatconversation.FieldGuestToken, field.TypeString, value)
		_node.GuestToken = &value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(chatconversation.FieldUserID, field.TypeInt64, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.VisitorName(); ok {
		_spec.SetField(chatconversation.FieldVisitorName, field.TypeString, value)
		_node.VisitorName = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(chatconversation.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AdminUnreadCount(); ok {
		_spec.SetField(chatconversation.FieldAdminUnreadCount, field.TypeInt, value)
		_node.AdminUnreadCount = value
	}
	if value, ok := _c.mutation.LastMessageAt(); ok {
		_spec.SetField(chatconversation.FieldLastMessageAt, field.TypeTime, value)
		_node.LastMessageAt = &value
	}
	if value, ok := _c.mutation.LastMessagePreview(); ok {
		_spec.SetField(chatconversation.FieldLastMessagePreview, field.TypeString, value)
		_node.LastMessagePreview = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(chatconversation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(chatconversation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatconversation.MessagesTable,
			Columns: []string{chatconversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChatConversation.Create().
//		SetGuestToken(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChatConversationUpsert) {
//			SetGuestToken(v+v).
//		}).
//		Exec(ctx)
func (_c *ChatConversationCreate) OnConflict(opts ...sql.ConflictOption) *ChatConversationUpsertOne {
	_c.conflict = opts
	return &ChatConversationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChatConversation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChatConversationCreate) OnConflictColumns(columns ...string) *ChatConversationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChatConversationUpsertOne{
		create: _c,
	}
}

type (
	// ChatConversationUpsertOne is the builder for "upsert"-ing
	//  one ChatConversation node.
	ChatConversationUpsertOne struct {
		create *ChatConversationCreate
	}

	// ChatConversationUpsert is the "OnConflict" setter.
	ChatConversationUpsert struct {
		*sql.UpdateSet
	}
)

// SetGuestToken sets the "guest_token" field.
func (u *ChatConversationUpsert) SetGuestToken(v string) *ChatConversationUpsert {
	u.Set(chatconversation.FieldGuestToken, v)
	return u
}

// UpdateGuestToken sets the "guest_token" field to the value that was provided on create.
func (u *ChatConversationUpsert) UpdateGuestToken() *ChatConversationUpsert {
	u.SetExcluded(chatconversation.FieldGuestToken)
	return u
}

// ClearGuestToken clears the value of the "guest_token" field.
func (u *ChatConversationUpsert) ClearGuestToken() *ChatConversationUpsert {
	u.SetNull(chatconversation.FieldGuestToken)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ChatConversationUpsert) SetUserID(v int64) *ChatConversationUpsert {
	u.Set(chatconversation.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ChatConversationUpsert) UpdateUserID() *ChatConversationUpsert {
	u.SetExcluded(chatconversation.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *ChatConversationUpsert) AddUserID(v int64) *ChatConversationUpsert {
	u.Add(chatconversation.FieldUserID, v)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *ChatConversationUpsert) ClearUserID() *ChatConversationUpsert {
	u.SetNull(chatconversation.FieldUserID)
	return u
}

// SetVisitorName sets the "visitor_name" field.
func (u *ChatConversationUpsert) SetVisitorName(v string) *ChatConversationUpsert {
	u.Set(chatconversation.FieldVisitorName, v)
	return u
}

// UpdateVisitorName sets the "visitor_name" field to the value that was provided on create.
func (u *ChatConversationUpsert) UpdateVisitorName() *ChatConversationUpsert {
	u.SetExcluded(chatconversation.FieldVisitorName)
	return u
}

// SetStatus sets the "status" field.
func (u *ChatConversationUpsert) SetStatus(v string) *ChatConversationUpsert {
	u.Set(chatconversation.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChatConversationUpsert) UpdateStatus() *ChatConversationUpsert {
	u.SetExcluded(chatconversation.FieldStatus)
	return u
}

// SetAdminUnreadCount sets the "admin_unread_count" field.
func (u *ChatConversationUpsert) SetAdminUnreadCount(v int) *ChatConversationUpsert {
	u.Set(chatconversation.FieldAdminUnreadCount, v)
	return u
}

// UpdateAdminUnreadCount sets the "admin_unread_count" field to the value that was provided on create.
func (u *ChatConversationUpsert) UpdateAdminUnreadCount() *ChatConversationUpsert {
	u.SetExcluded(chatconversation.FieldAdminUnreadCount)
	return u
}

// AddAdminUnreadCount adds v to the "admin_unread_count" field.
func (u *ChatConversationUpsert) AddAdminUnreadCount(v int) *ChatConversationUpsert {
	u.Add(chatconversation.FieldAdminUnreadCount, v)
	return u
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *ChatConversationUpsert) SetLastMessageAt(v time.Time) *ChatConversationUpsert {
	u.Set(chatconversation.FieldLastMessageAt, v)
	return u
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *ChatConversationUpsert) UpdateLastMessageAt() *ChatConversationUpsert {
	u.SetExcluded(chatconversation.FieldLastMessageAt)
	return u
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (u *ChatConversationUpsert) ClearLastMessageAt() *ChatConversationUpsert {
	u.SetNull(chatconversation.FieldLastMessageAt)
	return u
}

// SetLastMessagePreview sets the "last_message_preview" field.
func (u *ChatConversationUpsert) SetLastMessagePreview(v string) *ChatConversationUpsert {
	u.Set(chatconversation.FieldLastMessagePreview, v)
	return u
}

// UpdateLastMessagePreview sets the "last_message_preview" field to the value that was provided on create.
func (u *ChatConversationUpsert) UpdateLastMessagePreview() *ChatConversationUpsert {
	u.SetExcluded(chatconversation.FieldLastMessagePreview)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChatConversationUpsert) SetUpdatedAt(v time.Time) *ChatConversationUpsert {
	u.Set(chatconversation.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChatConversationUpsert) UpdateUpdatedAt() *ChatConversationUpsert {
	u.SetExcluded(chatconversation.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ChatConversation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChatConversationUpsertOne) UpdateNewValues() *ChatConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(chatconversation.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChatConversation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChatConversationUpsertOne) Ignore() *ChatConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChatConversationUpsertOne) DoNothing() *ChatConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChatConversationCreate.OnConflict
// documentation for more info.
func (u *ChatConversationUpsertOne) Update(set func(*ChatConversationUpsert)) *ChatConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChatConversationUpsert{UpdateSet: update})
	}))
	return u
}

// SetGuestToken sets the "guest_token" field.
func (u *ChatConversationUpsertOne) SetGuestToken(v string) *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetGuestToken(v)
	})
}

// UpdateGuestToken sets the "guest_token" field to the value that was provided on create.
func (u *ChatConversationUpsertOne) UpdateGuestToken() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateGuestToken()
	})
}

// ClearGuestToken clears the value of the "guest_token" field.
func (u *ChatConversationUpsertOne) ClearGuestToken() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.ClearGuestToken()
	})
}

// SetUserID sets the "user_id" field.
func (u *ChatConversationUpsertOne) SetUserID(v int64) *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *ChatConversationUpsertOne) AddUserID(v int64) *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ChatConversationUpsertOne) UpdateUserID() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *ChatConversationUpsertOne) ClearUserID() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.ClearUserID()
	})
}

// SetVisitorName sets the "visitor_name" field.
func (u *ChatConversationUpsertOne) SetVisitorName(v string) *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetVisitorName(v)
	})
}

// UpdateVisitorName sets the "visitor_name" field to the value that was provided on create.
func (u *ChatConversationUpsertOne) UpdateVisitorName() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateVisitorName()
	})
}

// SetStatus sets the "status" field.
func (u *ChatConversationUpsertOne) SetStatus(v string) *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChatConversationUpsertOne) UpdateStatus() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateStatus()
	})
}

// SetAdminUnreadCount sets the "admin_unread_count" field.
func (u *ChatConversationUpsertOne) SetAdminUnreadCount(v int) *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetAdminUnreadCount(v)
	})
}

// AddAdminUnreadCount adds v to the "admin_unread_count" field.
func (u *ChatConversationUpsertOne) AddAdminUnreadCount(v int) *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.AddAdminUnreadCount(v)
	})
}

// UpdateAdminUnreadCount sets the "admin_unread_count" field to the value that was provided on create.
func (u *ChatConversationUpsertOne) UpdateAdminUnreadCount() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateAdminUnreadCount()
	})
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *ChatConversationUpsertOne) SetLastMessageAt(v time.Time) *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetLastMessageAt(v)
	})
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *ChatConversationUpsertOne) UpdateLastMessageAt() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateLastMessageAt()
	})
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (u *ChatConversationUpsertOne) ClearLastMessageAt() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.ClearLastMessageAt()
	})
}

// SetLastMessagePreview sets the "last_message_preview" field.
func (u *ChatConversationUpsertOne) SetLastMessagePreview(v string) *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetLastMessagePreview(v)
	})
}

// UpdateLastMessagePreview sets the "last_message_preview" field to the value that was provided on create.
func (u *ChatConversationUpsertOne) UpdateLastMessagePreview() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateLastMessagePreview()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChatConversationUpsertOne) SetUpdatedAt(v time.Time) *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChatConversationUpsertOne) UpdateUpdatedAt() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ChatConversationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChatConversationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChatConversationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChatConversationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChatConversationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChatConversationCreateBulk is the builder for creating many ChatConversation entities in bulk.
type ChatConversationCreateBulk struct {
	config
	err      error
	builders []*ChatConversationCreate
	conflict []sql.ConflictOption
}

// Save creates the ChatConversation entities in the database.
func (_c *ChatConversationCreateBulk) Save(ctx context.Context) ([]*ChatConversation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChatConversation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatConversationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChatConversationCreateBulk) SaveX(ctx context.Context) []*ChatConversation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatConversationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatConversationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChatConversation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChatConversationUpsert) {
//			SetGuestToken(v+v).
//		}).
//		Exec(ctx)
func (_c *ChatConversationCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChatConversationUpsertBulk {
	_c.conflict = opts
	return &ChatConversationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChatConversation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChatConversationCreateBulk) OnConflictColumns(columns ...string) *ChatConversationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChatConversationUpsertBulk{
		create: _c,
	}
}

// ChatConversationUpsertBulk is the builder for "upsert"-ing
// a bulk of ChatConversation nodes.
type ChatConversationUpsertBulk struct {
	create *ChatConversationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ChatConversation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChatConversationUpsertBulk) UpdateNewValues() *ChatConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(chatconversation.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChatConversation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChatConversationUpsertBulk) Ignore() *ChatConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChatConversationUpsertBulk) DoNothing() *ChatConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChatConversationCreateBulk.OnConflict
// documentation for more info.
func (u *ChatConversationUpsertBulk) Update(set func(*ChatConversationUpsert)) *ChatConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChatConversationUpsert{UpdateSet: update})
	}))
	return u
}

// SetGuestToken sets the "guest_token" field.
func (u *ChatConversationUpsertBulk) SetGuestToken(v string) *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetGuestToken(v)
	})
}

// UpdateGuestToken sets the "guest_token" field to the value that was provided on create.
func (u *ChatConversationUpsertBulk) UpdateGuestToken() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateGuestToken()
	})
}

// ClearGuestToken clears the value of the "guest_token" field.
func (u *ChatConversationUpsertBulk) ClearGuestToken() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.ClearGuestToken()
	})
}

// SetUserID sets the "user_id" field.
func (u *ChatConversationUpsertBulk) SetUserID(v int64) *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *ChatConversationUpsertBulk) AddUserID(v int64) *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ChatConversationUpsertBulk) UpdateUserID() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *ChatConversationUpsertBulk) ClearUserID() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.ClearUserID()
	})
}

// SetVisitorName sets the "visitor_name" field.
func (u *ChatConversationUpsertBulk) SetVisitorName(v string) *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetVisitorName(v)
	})
}

// UpdateVisitorName sets the "visitor_name" field to the value that was provided on create.
func (u *ChatConversationUpsertBulk) UpdateVisitorName() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateVisitorName()
	})
}

// SetStatus sets the "status" field.
func (u *ChatConversationUpsertBulk) SetStatus(v string) *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChatConversationUpsertBulk) UpdateStatus() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateStatus()
	})
}

// SetAdminUnreadCount sets the "admin_unread_count" field.
func (u *ChatConversationUpsertBulk) SetAdminUnreadCount(v int) *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetAdminUnreadCount(v)
	})
}

// AddAdminUnreadCount adds v to the "admin_unread_count" field.
func (u *ChatConversationUpsertBulk) AddAdminUnreadCount(v int) *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.AddAdminUnreadCount(v)
	})
}

// UpdateAdminUnreadCount sets the "admin_unread_count" field to the value that was provided on create.
func (u *ChatConversationUpsertBulk) UpdateAdminUnreadCount() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateAdminUnreadCount()
	})
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *ChatConversationUpsertBulk) SetLastMessageAt(v time.Time) *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetLastMessageAt(v)
	})
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *ChatConversationUpsertBulk) UpdateLastMessageAt() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateLastMessageAt()
	})
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (u *ChatConversationUpsertBulk) ClearLastMessageAt() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.ClearLastMessageAt()
	})
}

// SetLastMessagePreview sets the "last_message_preview" field.
func (u *ChatConversationUpsertBulk) SetLastMessagePreview(v string) *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetLastMessagePreview(v)
	})
}

// UpdateLastMessagePreview sets the "last_message_preview" field to the value that was provided on create.
func (u *ChatConversationUpsertBulk) UpdateLastMessagePreview() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateLastMessagePreview()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChatConversationUpsertBulk) SetUpdatedAt(v time.Time) *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChatConversationUpsertBulk) UpdateUpdatedAt() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ChatConversationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChatConversationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChatConversationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChatConversationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
