// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/failovergroupevent"
)

// FailoverGroupEvent is the model entity for the FailoverGroupEvent schema.
type FailoverGroupEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 虚拟分组 ID
	VirtualGroupID int64 `json:"virtual_group_id,omitempty"`
	// 切换前的 active 成员 ID
	FromMemberID *int64 `json:"from_member_id,omitempty"`
	// 切换后的 active 成员 ID
	ToMemberID *int64 `json:"to_member_id,omitempty"`
	// 切换原因：soft_demote/probe_recovered/health_reconcile/manual_pin/manual_unpin/manual_unpin_expired/bootstrap/no_members_available/config_change
	Reason string `json:"reason,omitempty"`
	// 触发人：系统触发为 NULL，否则为管理员 user id
	TriggeredBy *int64 `json:"triggered_by,omitempty"`
	// 可选备注
	Note *string `json:"note,omitempty"`
	// OccurredAt holds the value of the "occurred_at" field.
	OccurredAt   time.Time `json:"occurred_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FailoverGroupEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case failovergroupevent.FieldID, failovergroupevent.FieldVirtualGroupID, failovergroupevent.FieldFromMemberID, failovergroupevent.FieldToMemberID, failovergroupevent.FieldTriggeredBy:
			values[i] = new(sql.NullInt64)
		case failovergroupevent.FieldReason, failovergroupevent.FieldNote:
			values[i] = new(sql.NullString)
		case failovergroupevent.FieldOccurredAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FailoverGroupEvent fields.
func (_m *FailoverGroupEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case failovergroupevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case failovergroupevent.FieldVirtualGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field virtual_group_id", values[i])
			} else if value.Valid {
				_m.VirtualGroupID = value.Int64
			}
		case failovergroupevent.FieldFromMemberID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field from_member_id", values[i])
			} else if value.Valid {
				_m.FromMemberID = new(int64)
				*_m.FromMemberID = value.Int64
			}
		case failovergroupevent.FieldToMemberID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field to_member_id", values[i])
			} else if value.Valid {
				_m.ToMemberID = new(int64)
				*_m.ToMemberID = value.Int64
			}
		case failovergroupevent.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case failovergroupevent.FieldTriggeredBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field triggered_by", values[i])
			} else if value.Valid {
				_m.TriggeredBy = new(int64)
				*_m.TriggeredBy = value.Int64
			}
		case failovergroupevent.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = new(string)
				*_m.Note = value.String
			}
		case failovergroupevent.FieldOccurredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field occurred_at", values[i])
			} else if value.Valid {
				_m.OccurredAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FailoverGroupEvent.
// This includes values selected through modifiers, order, etc.
func (_m *FailoverGroupEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this FailoverGroupEvent.
// Note that you need to call FailoverGroupEvent.Unwrap() before calling this method if this FailoverGroupEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FailoverGroupEvent) Update() *FailoverGroupEventUpdateOne {
	return NewFailoverGroupEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FailoverGroupEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FailoverGroupEvent) Unwrap() *FailoverGroupEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FailoverGroupEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FailoverGroupEvent) String() string {
	var builder strings.Builder
	builder.WriteString("FailoverGroupEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("virtual_group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.VirtualGroupID))
	builder.WriteString(", ")
	if v := _m.FromMemberID; v != nil {
		builder.WriteString("from_member_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ToMemberID; v != nil {
		builder.WriteString("to_member_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	if v := _m.TriggeredBy; v != nil {
		builder.WriteString("triggered_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Note; v != nil {
		builder.WriteString("note=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("occurred_at=")
	builder.WriteString(_m.OccurredAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// FailoverGroupEvents is a parsable slice of FailoverGroupEvent.
type FailoverGroupEvents []*FailoverGroupEvent
