// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/rechargeorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// RechargeOrder is the model entity for the RechargeOrder schema.
type RechargeOrder struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 充值订单号
	OrderNo string `json:"order_no,omitempty"`
	// 支付平台订单号
	TradeNo *string `json:"trade_no,omitempty"`
	// 用户ID
	UserID int64 `json:"user_id,omitempty"`
	// 用户实际支付金额
	Amount float64 `json:"amount,omitempty"`
	// 实际到账余额
	CreditAmount float64 `json:"credit_amount,omitempty"`
	// 倍率快照
	Multiplier float64 `json:"multiplier,omitempty"`
	// 订单状态: pending|paid|expired|refunded
	Status string `json:"status,omitempty"`
	// 支付方式: alipay|wxpay
	PayType *string `json:"pay_type,omitempty"`
	// 支付时间
	PaidAt *time.Time `json:"paid_at,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 过期时间
	ExpiredAt *time.Time `json:"expired_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RechargeOrderQuery when eager-loading is set.
	Edges        RechargeOrderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RechargeOrderEdges holds the relations/edges for other nodes in the graph.
type RechargeOrderEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RechargeOrderEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RechargeOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rechargeorder.FieldAmount, rechargeorder.FieldCreditAmount, rechargeorder.FieldMultiplier:
			values[i] = new(sql.NullFloat64)
		case rechargeorder.FieldID, rechargeorder.FieldUserID:
			values[i] = new(sql.NullInt64)
		case rechargeorder.FieldOrderNo, rechargeorder.FieldTradeNo, rechargeorder.FieldStatus, rechargeorder.FieldPayType:
			values[i] = new(sql.NullString)
		case rechargeorder.FieldPaidAt, rechargeorder.FieldCreatedAt, rechargeorder.FieldUpdatedAt, rechargeorder.FieldExpiredAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RechargeOrder fields.
func (_m *RechargeOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rechargeorder.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case rechargeorder.FieldOrderNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order_no", values[i])
			} else if value.Valid {
				_m.OrderNo = value.String
			}
		case rechargeorder.FieldTradeNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trade_no", values[i])
			} else if value.Valid {
				_m.TradeNo = new(string)
				*_m.TradeNo = value.String
			}
		case rechargeorder.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case rechargeorder.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case rechargeorder.FieldCreditAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field credit_amount", values[i])
			} else if value.Valid {
				_m.CreditAmount = value.Float64
			}
		case rechargeorder.FieldMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field multiplier", values[i])
			} else if value.Valid {
				_m.Multiplier = value.Float64
			}
		case rechargeorder.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case rechargeorder.FieldPayType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pay_type", values[i])
			} else if value.Valid {
				_m.PayType = new(string)
				*_m.PayType = value.String
			}
		case rechargeorder.FieldPaidAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field paid_at", values[i])
			} else if value.Valid {
				_m.PaidAt = new(time.Time)
				*_m.PaidAt = value.Time
			}
		case rechargeorder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case rechargeorder.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case rechargeorder.FieldExpiredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expired_at", values[i])
			} else if value.Valid {
				_m.ExpiredAt = new(time.Time)
				*_m.ExpiredAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RechargeOrder.
// This includes values selected through modifiers, order, etc.
func (_m *RechargeOrder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the RechargeOrder entity.
func (_m *RechargeOrder) QueryUser() *UserQuery {
	return NewRechargeOrderClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this RechargeOrder.
// Note that you need to call RechargeOrder.Unwrap() before calling this method if this RechargeOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RechargeOrder) Update() *RechargeOrderUpdateOne {
	return NewRechargeOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RechargeOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RechargeOrder) Unwrap() *RechargeOrder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RechargeOrder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RechargeOrder) String() string {
	var builder strings.Builder
	builder.WriteString("RechargeOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("order_no=")
	builder.WriteString(_m.OrderNo)
	builder.WriteString(", ")
	if v := _m.TradeNo; v != nil {
		builder.WriteString("trade_no=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("credit_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreditAmount))
	builder.WriteString(", ")
	builder.WriteString("multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.Multiplier))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.PayType; v != nil {
		builder.WriteString("pay_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PaidAt; v != nil {
		builder.WriteString("paid_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ExpiredAt; v != nil {
		builder.WriteString("expired_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// RechargeOrders is a parsable slice of RechargeOrder.
type RechargeOrders []*RechargeOrder
