// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/rechargeorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// RechargeOrderUpdate is the builder for updating RechargeOrder entities.
type RechargeOrderUpdate struct {
	config
	hooks    []Hook
	mutation *RechargeOrderMutation
}

// Where appends a list predicates to the RechargeOrderUpdate builder.
func (_u *RechargeOrderUpdate) Where(ps ...predicate.RechargeOrder) *RechargeOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrderNo sets the "order_no" field.
func (_u *RechargeOrderUpdate) SetOrderNo(v string) *RechargeOrderUpdate {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillableOrderNo(v *string) *RechargeOrderUpdate {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetTradeNo sets the "trade_no" field.
func (_u *RechargeOrderUpdate) SetTradeNo(v string) *RechargeOrderUpdate {
	_u.mutation.SetTradeNo(v)
	return _u
}

// SetNillableTradeNo sets the "trade_no" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillableTradeNo(v *string) *RechargeOrderUpdate {
	if v != nil {
		_u.SetTradeNo(*v)
	}
	return _u
}

// ClearTradeNo clears the value of the "trade_no" field.
func (_u *RechargeOrderUpdate) ClearTradeNo() *RechargeOrderUpdate {
	_u.mutation.ClearTradeNo()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RechargeOrderUpdate) SetUserID(v int64) *RechargeOrderUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillableUserID(v *int64) *RechargeOrderUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *RechargeOrderUpdate) SetAmount(v float64) *RechargeOrderUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillableAmount(v *float64) *RechargeOrderUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *RechargeOrderUpdate) AddAmount(v float64) *RechargeOrderUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCreditAmount sets the "credit_amount" field.
func (_u *RechargeOrderUpdate) SetCreditAmount(v float64) *RechargeOrderUpdate {
	_u.mutation.ResetCreditAmount()
	_u.mutation.SetCreditAmount(v)
	return _u
}

// SetNillableCreditAmount sets the "credit_amount" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillableCreditAmount(v *float64) *RechargeOrderUpdate {
	if v != nil {
		_u.SetCreditAmount(*v)
	}
	return _u
}

// AddCreditAmount adds value to the "credit_amount" field.
func (_u *RechargeOrderUpdate) AddCreditAmount(v float64) *RechargeOrderUpdate {
	_u.mutation.AddCreditAmount(v)
	return _u
}

// SetMultiplier sets the "multiplier" field.
func (_u *RechargeOrderUpdate) SetMultiplier(v float64) *RechargeOrderUpdate {
	_u.mutation.ResetMultiplier()
	_u.mutation.SetMultiplier(v)
	return _u
}

// SetNillableMultiplier sets the "multiplier" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillableMultiplier(v *float64) *RechargeOrderUpdate {
	if v != nil {
		_u.SetMultiplier(*v)
	}
	return _u
}

// AddMultiplier adds value to the "multiplier" field.
func (_u *RechargeOrderUpdate) AddMultiplier(v float64) *RechargeOrderUpdate {
	_u.mutation.AddMultiplier(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *RechargeOrderUpdate) SetStatus(v string) *RechargeOrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillableStatus(v *string) *RechargeOrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPayType sets the "pay_type" field.
func (_u *RechargeOrderUpdate) SetPayType(v string) *RechargeOrderUpdate {
	_u.mutation.SetPayType(v)
	return _u
}

// SetNillablePayType sets the "pay_type" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillablePayType(v *string) *RechargeOrderUpdate {
	if v != nil {
		_u.SetPayType(*v)
	}
	return _u
}

// ClearPayType clears the value of the "pay_type" field.
func (_u *RechargeOrderUpdate) ClearPayType() *RechargeOrderUpdate {
	_u.mutation.ClearPayType()
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *RechargeOrderUpdate) SetPaidAt(v time.Time) *RechargeOrderUpdate {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillablePaidAt(v *time.Time) *RechargeOrderUpdate {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *RechargeOrderUpdate) ClearPaidAt() *RechargeOrderUpdate {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RechargeOrderUpdate) SetUpdatedAt(v time.Time) *RechargeOrderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExpiredAt sets the "expired_at" field.
func (_u *RechargeOrderUpdate) SetExpiredAt(v time.Time) *RechargeOrderUpdate {
	_u.mutation.SetExpiredAt(v)
	return _u
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillableExpiredAt(v *time.Time) *RechargeOrderUpdate {
	if v != nil {
		_u.SetExpiredAt(*v)
	}
	return _u
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (_u *RechargeOrderUpdate) ClearExpiredAt() *RechargeOrderUpdate {
	_u.mutation.ClearExpiredAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *RechargeOrderUpdate) SetUser(v *User) *RechargeOrderUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the RechargeOrderMutation object of the builder.
func (_u *RechargeOrderUpdate) Mutation() *RechargeOrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *RechargeOrderUpdate) ClearUser() *RechargeOrderUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RechargeOrderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RechargeOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RechargeOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RechargeOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RechargeOrderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rechargeorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RechargeOrderUpdate) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := rechargeorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TradeNo(); ok {
		if err := rechargeorder.TradeNoValidator(v); err != nil {
			return &ValidationError{Name: "trade_no", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.trade_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := rechargeorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayType(); ok {
		if err := rechargeorder.PayTypeValidator(v); err != nil {
			return &ValidationError{Name: "pay_type", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.pay_type": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RechargeOrder.user"`)
	}
	return nil
}

func (_u *RechargeOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rechargeorder.Table, rechargeorder.Columns, sqlgraph.NewFieldSpec(rechargeorder.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(rechargeorder.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.TradeNo(); ok {
		_spec.SetField(rechargeorder.FieldTradeNo, field.TypeString, value)
	}
	if _u.mutation.TradeNoCleared() {
		_spec.ClearField(rechargeorder.FieldTradeNo, field.TypeString)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(rechargeorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(rechargeorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreditAmount(); ok {
		_spec.SetField(rechargeorder.FieldCreditAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreditAmount(); ok {
		_spec.AddField(rechargeorder.FieldCreditAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Multiplier(); ok {
		_spec.SetField(rechargeorder.FieldMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMultiplier(); ok {
		_spec.AddField(rechargeorder.FieldMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(rechargeorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayType(); ok {
		_spec.SetField(rechargeorder.FieldPayType, field.TypeString, value)
	}
	if _u.mutation.PayTypeCleared() {
		_spec.ClearField(rechargeorder.FieldPayType, field.TypeString)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(rechargeorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(rechargeorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rechargeorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiredAt(); ok {
		_spec.SetField(rechargeorder.FieldExpiredAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiredAtCleared() {
		_spec.ClearField(rechargeorder.FieldExpiredAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rechargeorder.UserTable,
			Columns: []string{rechargeorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rechargeorder.UserTable,
			Columns: []string{rechargeorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rechargeorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RechargeOrderUpdateOne is the builder for updating a single RechargeOrder entity.
type RechargeOrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RechargeOrderMutation
}

// SetOrderNo sets the "order_no" field.
func (_u *RechargeOrderUpdateOne) SetOrderNo(v string) *RechargeOrderUpdateOne {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillableOrderNo(v *string) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetTradeNo sets the "trade_no" field.
func (_u *RechargeOrderUpdateOne) SetTradeNo(v string) *RechargeOrderUpdateOne {
	_u.mutation.SetTradeNo(v)
	return _u
}

// SetNillableTradeNo sets the "trade_no" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillableTradeNo(v *string) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetTradeNo(*v)
	}
	return _u
}

// ClearTradeNo clears the value of the "trade_no" field.
func (_u *RechargeOrderUpdateOne) ClearTradeNo() *RechargeOrderUpdateOne {
	_u.mutation.ClearTradeNo()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RechargeOrderUpdateOne) SetUserID(v int64) *RechargeOrderUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillableUserID(v *int64) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *RechargeOrderUpdateOne) SetAmount(v float64) *RechargeOrderUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillableAmount(v *float64) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *RechargeOrderUpdateOne) AddAmount(v float64) *RechargeOrderUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCreditAmount sets the "credit_amount" field.
func (_u *RechargeOrderUpdateOne) SetCreditAmount(v float64) *RechargeOrderUpdateOne {
	_u.mutation.ResetCreditAmount()
	_u.mutation.SetCreditAmount(v)
	return _u
}

// SetNillableCreditAmount sets the "credit_amount" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillableCreditAmount(v *float64) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetCreditAmount(*v)
	}
	return _u
}

// AddCreditAmount adds value to the "credit_amount" field.
func (_u *RechargeOrderUpdateOne) AddCreditAmount(v float64) *RechargeOrderUpdateOne {
	_u.mutation.AddCreditAmount(v)
	return _u
}

// SetMultiplier sets the "multiplier" field.
func (_u *RechargeOrderUpdateOne) SetMultiplier(v float64) *RechargeOrderUpdateOne {
	_u.mutation.ResetMultiplier()
	_u.mutation.SetMultiplier(v)
	return _u
}

// SetNillableMultiplier sets the "multiplier" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillableMultiplier(v *float64) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetMultiplier(*v)
	}
	return _u
}

// AddMultiplier adds value to the "multiplier" field.
func (_u *RechargeOrderUpdateOne) AddMultiplier(v float64) *RechargeOrderUpdateOne {
	_u.mutation.AddMultiplier(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *RechargeOrderUpdateOne) SetStatus(v string) *RechargeOrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillableStatus(v *string) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPayType sets the "pay_type" field.
func (_u *RechargeOrderUpdateOne) SetPayType(v string) *RechargeOrderUpdateOne {
	_u.mutation.SetPayType(v)
	return _u
}

// SetNillablePayType sets the "pay_type" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillablePayType(v *string) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetPayType(*v)
	}
	return _u
}

// ClearPayType clears the value of the "pay_type" field.
func (_u *RechargeOrderUpdateOne) ClearPayType() *RechargeOrderUpdateOne {
	_u.mutation.ClearPayType()
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *RechargeOrderUpdateOne) SetPaidAt(v time.Time) *RechargeOrderUpdateOne {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillablePaidAt(v *time.Time) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *RechargeOrderUpdateOne) ClearPaidAt() *RechargeOrderUpdateOne {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RechargeOrderUpdateOne) SetUpdatedAt(v time.Time) *RechargeOrderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExpiredAt sets the "expired_at" field.
func (_u *RechargeOrderUpdateOne) SetExpiredAt(v time.Time) *RechargeOrderUpdateOne {
	_u.mutation.SetExpiredAt(v)
	return _u
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillableExpiredAt(v *time.Time) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetExpiredAt(*v)
	}
	return _u
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (_u *RechargeOrderUpdateOne) ClearExpiredAt() *RechargeOrderUpdateOne {
	_u.mutation.ClearExpiredAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *RechargeOrderUpdateOne) SetUser(v *User) *RechargeOrderUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the RechargeOrderMutation object of the builder.
func (_u *RechargeOrderUpdateOne) Mutation() *RechargeOrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *RechargeOrderUpdateOne) ClearUser() *RechargeOrderUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the RechargeOrderUpdate builder.
func (_u *RechargeOrderUpdateOne) Where(ps ...predicate.RechargeOrder) *RechargeOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RechargeOrderUpdateOne) Select(field string, fields ...string) *RechargeOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RechargeOrder entity.
func (_u *RechargeOrderUpdateOne) Save(ctx context.Context) (*RechargeOrder, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RechargeOrderUpdateOne) SaveX(ctx context.Context) *RechargeOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RechargeOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RechargeOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RechargeOrderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rechargeorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RechargeOrderUpdateOne) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := rechargeorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TradeNo(); ok {
		if err := rechargeorder.TradeNoValidator(v); err != nil {
			return &ValidationError{Name: "trade_no", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.trade_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := rechargeorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayType(); ok {
		if err := rechargeorder.PayTypeValidator(v); err != nil {
			return &ValidationError{Name: "pay_type", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.pay_type": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RechargeOrder.user"`)
	}
	return nil
}

func (_u *RechargeOrderUpdateOne) sqlSave(ctx context.Context) (_node *RechargeOrder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rechargeorder.Table, rechargeorder.Columns, sqlgraph.NewFieldSpec(rechargeorder.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RechargeOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rechargeorder.FieldID)
		for _, f := range fields {
			if !rechargeorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rechargeorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(rechargeorder.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.TradeNo(); ok {
		_spec.SetField(rechargeorder.FieldTradeNo, field.TypeString, value)
	}
	if _u.mutation.TradeNoCleared() {
		_spec.ClearField(rechargeorder.FieldTradeNo, field.TypeString)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(rechargeorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(rechargeorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreditAmount(); ok {
		_spec.SetField(rechargeorder.FieldCreditAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreditAmount(); ok {
		_spec.AddField(rechargeorder.FieldCreditAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Multiplier(); ok {
		_spec.SetField(rechargeorder.FieldMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMultiplier(); ok {
		_spec.AddField(rechargeorder.FieldMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(rechargeorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayType(); ok {
		_spec.SetField(rechargeorder.FieldPayType, field.TypeString, value)
	}
	if _u.mutation.PayTypeCleared() {
		_spec.ClearField(rechargeorder.FieldPayType, field.TypeString)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(rechargeorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(rechargeorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rechargeorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiredAt(); ok {
		_spec.SetField(rechargeorder.FieldExpiredAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiredAtCleared() {
		_spec.ClearField(rechargeorder.FieldExpiredAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rechargeorder.UserTable,
			Columns: []string{rechargeorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rechargeorder.UserTable,
			Columns: []string{rechargeorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RechargeOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rechargeorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
