// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/order"
	"github.com/Wei-Shaw/sub2api/ent/referralreward"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ReferralReward is the model entity for the ReferralReward schema.
type ReferralReward struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 邀请人ID
	ReferrerID int64 `json:"referrer_id,omitempty"`
	// 被邀请人ID（每个被邀请人只能触发一次奖励）
	InviteeID int64 `json:"invitee_id,omitempty"`
	// 触发奖励的订单ID
	TriggerOrderID int64 `json:"trigger_order_id,omitempty"`
	// 邀请人获得的奖励金额
	ReferrerReward float64 `json:"referrer_reward,omitempty"`
	// 被邀请人获得的奖励金额
	InviteeReward float64 `json:"invitee_reward,omitempty"`
	// 跳过邀请人奖励的原因（如：邀请人已被封禁）
	SkipReferrerReason *string `json:"skip_referrer_reason,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ReferralRewardQuery when eager-loading is set.
	Edges        ReferralRewardEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ReferralRewardEdges holds the relations/edges for other nodes in the graph.
type ReferralRewardEdges struct {
	// Referrer holds the value of the referrer edge.
	Referrer *User `json:"referrer,omitempty"`
	// Invitee holds the value of the invitee edge.
	Invitee *User `json:"invitee,omitempty"`
	// TriggerOrder holds the value of the trigger_order edge.
	TriggerOrder *Order `json:"trigger_order,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ReferrerOrErr returns the Referrer value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReferralRewardEdges) ReferrerOrErr() (*User, error) {
	if e.Referrer != nil {
		return e.Referrer, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "referrer"}
}

// InviteeOrErr returns the Invitee value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReferralRewardEdges) InviteeOrErr() (*User, error) {
	if e.Invitee != nil {
		return e.Invitee, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "invitee"}
}

// TriggerOrderOrErr returns the TriggerOrder value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReferralRewardEdges) TriggerOrderOrErr() (*Order, error) {
	if e.TriggerOrder != nil {
		return e.TriggerOrder, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: order.Label}
	}
	return nil, &NotLoadedError{edge: "trigger_order"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReferralReward) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case referralreward.FieldReferrerReward, referralreward.FieldInviteeReward:
			values[i] = new(sql.NullFloat64)
		case referralreward.FieldID, referralreward.FieldReferrerID, referralreward.FieldInviteeID, referralreward.FieldTriggerOrderID:
			values[i] = new(sql.NullInt64)
		case referralreward.FieldSkipReferrerReason:
			values[i] = new(sql.NullString)
		case referralreward.FieldCreatedAt, referralreward.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReferralReward fields.
func (_m *ReferralReward) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case referralreward.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case referralreward.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case referralreward.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case referralreward.FieldReferrerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field referrer_id", values[i])
			} else if value.Valid {
				_m.ReferrerID = value.Int64
			}
		case referralreward.FieldInviteeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field invitee_id", values[i])
			} else if value.Valid {
				_m.InviteeID = value.Int64
			}
		case referralreward.FieldTriggerOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_order_id", values[i])
			} else if value.Valid {
				_m.TriggerOrderID = value.Int64
			}
		case referralreward.FieldReferrerReward:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field referrer_reward", values[i])
			} else if value.Valid {
				_m.ReferrerReward = value.Float64
			}
		case referralreward.FieldInviteeReward:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field invitee_reward", values[i])
			} else if value.Valid {
				_m.InviteeReward = value.Float64
			}
		case referralreward.FieldSkipReferrerReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field skip_referrer_reason", values[i])
			} else if value.Valid {
				_m.SkipReferrerReason = new(string)
				*_m.SkipReferrerReason = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReferralReward.
// This includes values selected through modifiers, order, etc.
func (_m *ReferralReward) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryReferrer queries the "referrer" edge of the ReferralReward entity.
func (_m *ReferralReward) QueryReferrer() *UserQuery {
	return NewReferralRewardClient(_m.config).QueryReferrer(_m)
}

// QueryInvitee queries the "invitee" edge of the ReferralReward entity.
func (_m *ReferralReward) QueryInvitee() *UserQuery {
	return NewReferralRewardClient(_m.config).QueryInvitee(_m)
}

// QueryTriggerOrder queries the "trigger_order" edge of the ReferralReward entity.
func (_m *ReferralReward) QueryTriggerOrder() *OrderQuery {
	return NewReferralRewardClient(_m.config).QueryTriggerOrder(_m)
}

// Update returns a builder for updating this ReferralReward.
// Note that you need to call ReferralReward.Unwrap() before calling this method if this ReferralReward
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ReferralReward) Update() *ReferralRewardUpdateOne {
	return NewReferralRewardClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ReferralReward entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ReferralReward) Unwrap() *ReferralReward {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReferralReward is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ReferralReward) String() string {
	var builder strings.Builder
	builder.WriteString("ReferralReward(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("referrer_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReferrerID))
	builder.WriteString(", ")
	builder.WriteString("invitee_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InviteeID))
	builder.WriteString(", ")
	builder.WriteString("trigger_order_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TriggerOrderID))
	builder.WriteString(", ")
	builder.WriteString("referrer_reward=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReferrerReward))
	builder.WriteString(", ")
	builder.WriteString("invitee_reward=")
	builder.WriteString(fmt.Sprintf("%v", _m.InviteeReward))
	builder.WriteString(", ")
	if v := _m.SkipReferrerReason; v != nil {
		builder.WriteString("skip_referrer_reason=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// ReferralRewards is a parsable slice of ReferralReward.
type ReferralRewards []*ReferralReward
