// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/resellersetting"
)

// ResellerSettingCreate is the builder for creating a ResellerSetting entity.
type ResellerSettingCreate struct {
	config
	mutation *ResellerSettingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetResellerID sets the "reseller_id" field.
func (_c *ResellerSettingCreate) SetResellerID(v int64) *ResellerSettingCreate {
	_c.mutation.SetResellerID(v)
	return _c
}

// SetKey sets the "key" field.
func (_c *ResellerSettingCreate) SetKey(v string) *ResellerSettingCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *ResellerSettingCreate) SetValue(v string) *ResellerSettingCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_c *ResellerSettingCreate) SetNillableValue(v *string) *ResellerSettingCreate {
	if v != nil {
		_c.SetValue(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ResellerSettingCreate) SetCreatedAt(v time.Time) *ResellerSettingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ResellerSettingCreate) SetNillableCreatedAt(v *time.Time) *ResellerSettingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ResellerSettingCreate) SetUpdatedAt(v time.Time) *ResellerSettingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ResellerSettingCreate) SetNillableUpdatedAt(v *time.Time) *ResellerSettingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ResellerSettingMutation object of the builder.
func (_c *ResellerSettingCreate) Mutation() *ResellerSettingMutation {
	return _c.mutation
}

// Save creates the ResellerSetting in the database.
func (_c *ResellerSettingCreate) Save(ctx context.Context) (*ResellerSetting, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ResellerSettingCreate) SaveX(ctx context.Context) *ResellerSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResellerSettingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResellerSettingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ResellerSettingCreate) defaults() {
	if _, ok := _c.mutation.Value(); !ok {
		v := resellersetting.DefaultValue
		_c.mutation.SetValue(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := resellersetting.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := resellersetting.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ResellerSettingCreate) check() error {
	if _, ok := _c.mutation.ResellerID(); !ok {
		return &ValidationError{Name: "reseller_id", err: errors.New(`ent: missing required field "ResellerSetting.reseller_id"`)}
	}
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "ResellerSetting.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := resellersetting.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "ResellerSetting.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "ResellerSetting.value"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ResellerSetting.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ResellerSetting.updated_at"`)}
	}
	return nil
}

func (_c *ResellerSettingCreate) sqlSave(ctx context.Context) (*ResellerSetting, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ResellerSettingCreate) createSpec() (*ResellerSetting, *sqlgraph.CreateSpec) {
	var (
		_node = &ResellerSetting{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(resellersetting.Table, sqlgraph.NewFieldSpec(resellersetting.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ResellerID(); ok {
		_spec.SetField(resellersetting.FieldResellerID, field.TypeInt64, value)
		_node.ResellerID = value
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(resellersetting.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(resellersetting.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(resellersetting.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(resellersetting.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResellerSetting.Create().
//		SetResellerID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResellerSettingUpsert) {
//			SetResellerID(v+v).
//		}).
//		Exec(ctx)
func (_c *ResellerSettingCreate) OnConflict(opts ...sql.ConflictOption) *ResellerSettingUpsertOne {
	_c.conflict = opts
	return &ResellerSettingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResellerSetting.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResellerSettingCreate) OnConflictColumns(columns ...string) *ResellerSettingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResellerSettingUpsertOne{
		create: _c,
	}
}

type (
	// ResellerSettingUpsertOne is the builder for "upsert"-ing
	//  one ResellerSetting node.
	ResellerSettingUpsertOne struct {
		create *ResellerSettingCreate
	}

	// ResellerSettingUpsert is the "OnConflict" setter.
	ResellerSettingUpsert struct {
		*sql.UpdateSet
	}
)

// SetResellerID sets the "reseller_id" field.
func (u *ResellerSettingUpsert) SetResellerID(v int64) *ResellerSettingUpsert {
	u.Set(resellersetting.FieldResellerID, v)
	return u
}

// UpdateResellerID sets the "reseller_id" field to the value that was provided on create.
func (u *ResellerSettingUpsert) UpdateResellerID() *ResellerSettingUpsert {
	u.SetExcluded(resellersetting.FieldResellerID)
	return u
}

// AddResellerID adds v to the "reseller_id" field.
func (u *ResellerSettingUpsert) AddResellerID(v int64) *ResellerSettingUpsert {
	u.Add(resellersetting.FieldResellerID, v)
	return u
}

// SetKey sets the "key" field.
func (u *ResellerSettingUpsert) SetKey(v string) *ResellerSettingUpsert {
	u.Set(resellersetting.FieldKey, v)
	return u
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *ResellerSettingUpsert) UpdateKey() *ResellerSettingUpsert {
	u.SetExcluded(resellersetting.FieldKey)
	return u
}

// SetValue sets the "value" field.
func (u *ResellerSettingUpsert) SetValue(v string) *ResellerSettingUpsert {
	u.Set(resellersetting.FieldValue, v)
	return u
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *ResellerSettingUpsert) UpdateValue() *ResellerSettingUpsert {
	u.SetExcluded(resellersetting.FieldValue)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ResellerSettingUpsert) SetUpdatedAt(v time.Time) *ResellerSettingUpsert {
	u.Set(resellersetting.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResellerSettingUpsert) UpdateUpdatedAt() *ResellerSettingUpsert {
	u.SetExcluded(resellersetting.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ResellerSetting.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ResellerSettingUpsertOne) UpdateNewValues() *ResellerSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(resellersetting.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResellerSetting.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ResellerSettingUpsertOne) Ignore() *ResellerSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResellerSettingUpsertOne) DoNothing() *ResellerSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResellerSettingCreate.OnConflict
// documentation for more info.
func (u *ResellerSettingUpsertOne) Update(set func(*ResellerSettingUpsert)) *ResellerSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResellerSettingUpsert{UpdateSet: update})
	}))
	return u
}

// SetResellerID sets the "reseller_id" field.
func (u *ResellerSettingUpsertOne) SetResellerID(v int64) *ResellerSettingUpsertOne {
	return u.Update(func(s *ResellerSettingUpsert) {
		s.SetResellerID(v)
	})
}

// AddResellerID adds v to the "reseller_id" field.
func (u *ResellerSettingUpsertOne) AddResellerID(v int64) *ResellerSettingUpsertOne {
	return u.Update(func(s *ResellerSettingUpsert) {
		s.AddResellerID(v)
	})
}

// UpdateResellerID sets the "reseller_id" field to the value that was provided on create.
func (u *ResellerSettingUpsertOne) UpdateResellerID() *ResellerSettingUpsertOne {
	return u.Update(func(s *ResellerSettingUpsert) {
		s.UpdateResellerID()
	})
}

// SetKey sets the "key" field.
func (u *ResellerSettingUpsertOne) SetKey(v string) *ResellerSettingUpsertOne {
	return u.Update(func(s *ResellerSettingUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *ResellerSettingUpsertOne) UpdateKey() *ResellerSettingUpsertOne {
	return u.Update(func(s *ResellerSettingUpsert) {
		s.UpdateKey()
	})
}

// SetValue sets the "value" field.
func (u *ResellerSettingUpsertOne) SetValue(v string) *ResellerSettingUpsertOne {
	return u.Update(func(s *ResellerSettingUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *ResellerSettingUpsertOne) UpdateValue() *ResellerSettingUpsertOne {
	return u.Update(func(s *ResellerSettingUpsert) {
		s.UpdateValue()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ResellerSettingUpsertOne) SetUpdatedAt(v time.Time) *ResellerSettingUpsertOne {
	return u.Update(func(s *ResellerSettingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResellerSettingUpsertOne) UpdateUpdatedAt() *ResellerSettingUpsertOne {
	return u.Update(func(s *ResellerSettingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ResellerSettingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResellerSettingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResellerSettingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ResellerSettingUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ResellerSettingUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ResellerSettingCreateBulk is the builder for creating many ResellerSetting entities in bulk.
type ResellerSettingCreateBulk struct {
	config
	err      error
	builders []*ResellerSettingCreate
	conflict []sql.ConflictOption
}

// Save creates the ResellerSetting entities in the database.
func (_c *ResellerSettingCreateBulk) Save(ctx context.Context) ([]*ResellerSetting, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ResellerSetting, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResellerSettingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ResellerSettingCreateBulk) SaveX(ctx context.Context) []*ResellerSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResellerSettingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResellerSettingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResellerSetting.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResellerSettingUpsert) {
//			SetResellerID(v+v).
//		}).
//		Exec(ctx)
func (_c *ResellerSettingCreateBulk) OnConflict(opts ...sql.ConflictOption) *ResellerSettingUpsertBulk {
	_c.conflict = opts
	return &ResellerSettingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResellerSetting.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResellerSettingCreateBulk) OnConflictColumns(columns ...string) *ResellerSettingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResellerSettingUpsertBulk{
		create: _c,
	}
}

// ResellerSettingUpsertBulk is the builder for "upsert"-ing
// a bulk of ResellerSetting nodes.
type ResellerSettingUpsertBulk struct {
	create *ResellerSettingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ResellerSetting.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ResellerSettingUpsertBulk) UpdateNewValues() *ResellerSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(resellersetting.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResellerSetting.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ResellerSettingUpsertBulk) Ignore() *ResellerSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResellerSettingUpsertBulk) DoNothing() *ResellerSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResellerSettingCreateBulk.OnConflict
// documentation for more info.
func (u *ResellerSettingUpsertBulk) Update(set func(*ResellerSettingUpsert)) *ResellerSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResellerSettingUpsert{UpdateSet: update})
	}))
	return u
}

// SetResellerID sets the "reseller_id" field.
func (u *ResellerSettingUpsertBulk) SetResellerID(v int64) *ResellerSettingUpsertBulk {
	return u.Update(func(s *ResellerSettingUpsert) {
		s.SetResellerID(v)
	})
}

// AddResellerID adds v to the "reseller_id" field.
func (u *ResellerSettingUpsertBulk) AddResellerID(v int64) *ResellerSettingUpsertBulk {
	return u.Update(func(s *ResellerSettingUpsert) {
		s.AddResellerID(v)
	})
}

// UpdateResellerID sets the "reseller_id" field to the value that was provided on create.
func (u *ResellerSettingUpsertBulk) UpdateResellerID() *ResellerSettingUpsertBulk {
	return u.Update(func(s *ResellerSettingUpsert) {
		s.UpdateResellerID()
	})
}

// SetKey sets the "key" field.
func (u *ResellerSettingUpsertBulk) SetKey(v string) *ResellerSettingUpsertBulk {
	return u.Update(func(s *ResellerSettingUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *ResellerSettingUpsertBulk) UpdateKey() *ResellerSettingUpsertBulk {
	return u.Update(func(s *ResellerSettingUpsert) {
		s.UpdateKey()
	})
}

// SetValue sets the "value" field.
func (u *ResellerSettingUpsertBulk) SetValue(v string) *ResellerSettingUpsertBulk {
	return u.Update(func(s *ResellerSettingUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *ResellerSettingUpsertBulk) UpdateValue() *ResellerSettingUpsertBulk {
	return u.Update(func(s *ResellerSettingUpsert) {
		s.UpdateValue()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ResellerSettingUpsertBulk) SetUpdatedAt(v time.Time) *ResellerSettingUpsertBulk {
	return u.Update(func(s *ResellerSettingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResellerSettingUpsertBulk) UpdateUpdatedAt() *ResellerSettingUpsertBulk {
	return u.Update(func(s *ResellerSettingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ResellerSettingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ResellerSettingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResellerSettingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResellerSettingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
