// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/resellerapitoken"
)

// ResellerAPIToken is the model entity for the ResellerAPIToken schema.
type ResellerAPIToken struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 分销商用户 ID
	ResellerID int64 `json:"reseller_id,omitempty"`
	// 令牌用途备注
	Name string `json:"name,omitempty"`
	// 明文前缀，用于 UI 展示，如 rst-1a2b
	TokenPrefix string `json:"token_prefix,omitempty"`
	// SHA-256(token) 十六进制；明文不落库
	TokenHash string `json:"token_hash,omitempty"`
	// active / revoked
	Status string `json:"status,omitempty"`
	// 最近一次使用时间
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	// 过期时间，NULL 表示永不过期
	ExpiresAt    *time.Time `json:"expires_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ResellerAPIToken) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case resellerapitoken.FieldID, resellerapitoken.FieldResellerID:
			values[i] = new(sql.NullInt64)
		case resellerapitoken.FieldName, resellerapitoken.FieldTokenPrefix, resellerapitoken.FieldTokenHash, resellerapitoken.FieldStatus:
			values[i] = new(sql.NullString)
		case resellerapitoken.FieldCreatedAt, resellerapitoken.FieldUpdatedAt, resellerapitoken.FieldLastUsedAt, resellerapitoken.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ResellerAPIToken fields.
func (_m *ResellerAPIToken) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case resellerapitoken.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case resellerapitoken.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case resellerapitoken.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case resellerapitoken.FieldResellerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reseller_id", values[i])
			} else if value.Valid {
				_m.ResellerID = value.Int64
			}
		case resellerapitoken.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case resellerapitoken.FieldTokenPrefix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_prefix", values[i])
			} else if value.Valid {
				_m.TokenPrefix = value.String
			}
		case resellerapitoken.FieldTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_hash", values[i])
			} else if value.Valid {
				_m.TokenHash = value.String
			}
		case resellerapitoken.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case resellerapitoken.FieldLastUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_used_at", values[i])
			} else if value.Valid {
				_m.LastUsedAt = new(time.Time)
				*_m.LastUsedAt = value.Time
			}
		case resellerapitoken.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ResellerAPIToken.
// This includes values selected through modifiers, order, etc.
func (_m *ResellerAPIToken) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ResellerAPIToken.
// Note that you need to call ResellerAPIToken.Unwrap() before calling this method if this ResellerAPIToken
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ResellerAPIToken) Update() *ResellerAPITokenUpdateOne {
	return NewResellerAPITokenClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ResellerAPIToken entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ResellerAPIToken) Unwrap() *ResellerAPIToken {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ResellerAPIToken is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ResellerAPIToken) String() string {
	var builder strings.Builder
	builder.WriteString("ResellerAPIToken(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("reseller_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResellerID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("token_prefix=")
	builder.WriteString(_m.TokenPrefix)
	builder.WriteString(", ")
	builder.WriteString("token_hash=")
	builder.WriteString(_m.TokenHash)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.LastUsedAt; v != nil {
		builder.WriteString("last_used_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ResellerAPITokens is a parsable slice of ResellerAPIToken.
type ResellerAPITokens []*ResellerAPIToken
