// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/resellerdomain"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ResellerDomainUpdate is the builder for updating ResellerDomain entities.
type ResellerDomainUpdate struct {
	config
	hooks    []Hook
	mutation *ResellerDomainMutation
}

// Where appends a list predicates to the ResellerDomainUpdate builder.
func (_u *ResellerDomainUpdate) Where(ps ...predicate.ResellerDomain) *ResellerDomainUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResellerDomainUpdate) SetUpdatedAt(v time.Time) *ResellerDomainUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ResellerDomainUpdate) SetDeletedAt(v time.Time) *ResellerDomainUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ResellerDomainUpdate) SetNillableDeletedAt(v *time.Time) *ResellerDomainUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ResellerDomainUpdate) ClearDeletedAt() *ResellerDomainUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetResellerID sets the "reseller_id" field.
func (_u *ResellerDomainUpdate) SetResellerID(v int64) *ResellerDomainUpdate {
	_u.mutation.SetResellerID(v)
	return _u
}

// SetNillableResellerID sets the "reseller_id" field if the given value is not nil.
func (_u *ResellerDomainUpdate) SetNillableResellerID(v *int64) *ResellerDomainUpdate {
	if v != nil {
		_u.SetResellerID(*v)
	}
	return _u
}

// SetDomain sets the "domain" field.
func (_u *ResellerDomainUpdate) SetDomain(v string) *ResellerDomainUpdate {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *ResellerDomainUpdate) SetNillableDomain(v *string) *ResellerDomainUpdate {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// SetSiteName sets the "site_name" field.
func (_u *ResellerDomainUpdate) SetSiteName(v string) *ResellerDomainUpdate {
	_u.mutation.SetSiteName(v)
	return _u
}

// SetNillableSiteName sets the "site_name" field if the given value is not nil.
func (_u *ResellerDomainUpdate) SetNillableSiteName(v *string) *ResellerDomainUpdate {
	if v != nil {
		_u.SetSiteName(*v)
	}
	return _u
}

// SetSiteLogo sets the "site_logo" field.
func (_u *ResellerDomainUpdate) SetSiteLogo(v string) *ResellerDomainUpdate {
	_u.mutation.SetSiteLogo(v)
	return _u
}

// SetNillableSiteLogo sets the "site_logo" field if the given value is not nil.
func (_u *ResellerDomainUpdate) SetNillableSiteLogo(v *string) *ResellerDomainUpdate {
	if v != nil {
		_u.SetSiteLogo(*v)
	}
	return _u
}

// SetBrandColor sets the "brand_color" field.
func (_u *ResellerDomainUpdate) SetBrandColor(v string) *ResellerDomainUpdate {
	_u.mutation.SetBrandColor(v)
	return _u
}

// SetNillableBrandColor sets the "brand_color" field if the given value is not nil.
func (_u *ResellerDomainUpdate) SetNillableBrandColor(v *string) *ResellerDomainUpdate {
	if v != nil {
		_u.SetBrandColor(*v)
	}
	return _u
}

// SetCustomCSS sets the "custom_css" field.
func (_u *ResellerDomainUpdate) SetCustomCSS(v string) *ResellerDomainUpdate {
	_u.mutation.SetCustomCSS(v)
	return _u
}

// SetNillableCustomCSS sets the "custom_css" field if the given value is not nil.
func (_u *ResellerDomainUpdate) SetNillableCustomCSS(v *string) *ResellerDomainUpdate {
	if v != nil {
		_u.SetCustomCSS(*v)
	}
	return _u
}

// SetSubtitle sets the "subtitle" field.
func (_u *ResellerDomainUpdate) SetSubtitle(v string) *ResellerDomainUpdate {
	_u.mutation.SetSubtitle(v)
	return _u
}

// SetNillableSubtitle sets the "subtitle" field if the given value is not nil.
func (_u *ResellerDomainUpdate) SetNillableSubtitle(v *string) *ResellerDomainUpdate {
	if v != nil {
		_u.SetSubtitle(*v)
	}
	return _u
}

// SetHomeContent sets the "home_content" field.
func (_u *ResellerDomainUpdate) SetHomeContent(v string) *ResellerDomainUpdate {
	_u.mutation.SetHomeContent(v)
	return _u
}

// SetNillableHomeContent sets the "home_content" field if the given value is not nil.
func (_u *ResellerDomainUpdate) SetNillableHomeContent(v *string) *ResellerDomainUpdate {
	if v != nil {
		_u.SetHomeContent(*v)
	}
	return _u
}

// SetHomeTemplate sets the "home_template" field.
func (_u *ResellerDomainUpdate) SetHomeTemplate(v string) *ResellerDomainUpdate {
	_u.mutation.SetHomeTemplate(v)
	return _u
}

// SetNillableHomeTemplate sets the "home_template" field if the given value is not nil.
func (_u *ResellerDomainUpdate) SetNillableHomeTemplate(v *string) *ResellerDomainUpdate {
	if v != nil {
		_u.SetHomeTemplate(*v)
	}
	return _u
}

// SetDocURL sets the "doc_url" field.
func (_u *ResellerDomainUpdate) SetDocURL(v string) *ResellerDomainUpdate {
	_u.mutation.SetDocURL(v)
	return _u
}

// SetNillableDocURL sets the "doc_url" field if the given value is not nil.
func (_u *ResellerDomainUpdate) SetNillableDocURL(v *string) *ResellerDomainUpdate {
	if v != nil {
		_u.SetDocURL(*v)
	}
	return _u
}

// SetPurchaseEnabled sets the "purchase_enabled" field.
func (_u *ResellerDomainUpdate) SetPurchaseEnabled(v bool) *ResellerDomainUpdate {
	_u.mutation.SetPurchaseEnabled(v)
	return _u
}

// SetNillablePurchaseEnabled sets the "purchase_enabled" field if the given value is not nil.
func (_u *ResellerDomainUpdate) SetNillablePurchaseEnabled(v *bool) *ResellerDomainUpdate {
	if v != nil {
		_u.SetPurchaseEnabled(*v)
	}
	return _u
}

// SetPurchaseURL sets the "purchase_url" field.
func (_u *ResellerDomainUpdate) SetPurchaseURL(v string) *ResellerDomainUpdate {
	_u.mutation.SetPurchaseURL(v)
	return _u
}

// SetNillablePurchaseURL sets the "purchase_url" field if the given value is not nil.
func (_u *ResellerDomainUpdate) SetNillablePurchaseURL(v *string) *ResellerDomainUpdate {
	if v != nil {
		_u.SetPurchaseURL(*v)
	}
	return _u
}

// SetDefaultLocale sets the "default_locale" field.
func (_u *ResellerDomainUpdate) SetDefaultLocale(v string) *ResellerDomainUpdate {
	_u.mutation.SetDefaultLocale(v)
	return _u
}

// SetNillableDefaultLocale sets the "default_locale" field if the given value is not nil.
func (_u *ResellerDomainUpdate) SetNillableDefaultLocale(v *string) *ResellerDomainUpdate {
	if v != nil {
		_u.SetDefaultLocale(*v)
	}
	return _u
}

// SetSeoTitle sets the "seo_title" field.
func (_u *ResellerDomainUpdate) SetSeoTitle(v string) *ResellerDomainUpdate {
	_u.mutation.SetSeoTitle(v)
	return _u
}

// SetNillableSeoTitle sets the "seo_title" field if the given value is not nil.
func (_u *ResellerDomainUpdate) SetNillableSeoTitle(v *string) *ResellerDomainUpdate {
	if v != nil {
		_u.SetSeoTitle(*v)
	}
	return _u
}

// SetSeoDescription sets the "seo_description" field.
func (_u *ResellerDomainUpdate) SetSeoDescription(v string) *ResellerDomainUpdate {
	_u.mutation.SetSeoDescription(v)
	return _u
}

// SetNillableSeoDescription sets the "seo_description" field if the given value is not nil.
func (_u *ResellerDomainUpdate) SetNillableSeoDescription(v *string) *ResellerDomainUpdate {
	if v != nil {
		_u.SetSeoDescription(*v)
	}
	return _u
}

// SetSeoKeywords sets the "seo_keywords" field.
func (_u *ResellerDomainUpdate) SetSeoKeywords(v string) *ResellerDomainUpdate {
	_u.mutation.SetSeoKeywords(v)
	return _u
}

// SetNillableSeoKeywords sets the "seo_keywords" field if the given value is not nil.
func (_u *ResellerDomainUpdate) SetNillableSeoKeywords(v *string) *ResellerDomainUpdate {
	if v != nil {
		_u.SetSeoKeywords(*v)
	}
	return _u
}

// SetLoginRedirect sets the "login_redirect" field.
func (_u *ResellerDomainUpdate) SetLoginRedirect(v string) *ResellerDomainUpdate {
	_u.mutation.SetLoginRedirect(v)
	return _u
}

// SetNillableLoginRedirect sets the "login_redirect" field if the given value is not nil.
func (_u *ResellerDomainUpdate) SetNillableLoginRedirect(v *string) *ResellerDomainUpdate {
	if v != nil {
		_u.SetLoginRedirect(*v)
	}
	return _u
}

// SetVerifyToken sets the "verify_token" field.
func (_u *ResellerDomainUpdate) SetVerifyToken(v string) *ResellerDomainUpdate {
	_u.mutation.SetVerifyToken(v)
	return _u
}

// SetNillableVerifyToken sets the "verify_token" field if the given value is not nil.
func (_u *ResellerDomainUpdate) SetNillableVerifyToken(v *string) *ResellerDomainUpdate {
	if v != nil {
		_u.SetVerifyToken(*v)
	}
	return _u
}

// SetVerified sets the "verified" field.
func (_u *ResellerDomainUpdate) SetVerified(v bool) *ResellerDomainUpdate {
	_u.mutation.SetVerified(v)
	return _u
}

// SetNillableVerified sets the "verified" field if the given value is not nil.
func (_u *ResellerDomainUpdate) SetNillableVerified(v *bool) *ResellerDomainUpdate {
	if v != nil {
		_u.SetVerified(*v)
	}
	return _u
}

// SetVerifiedAt sets the "verified_at" field.
func (_u *ResellerDomainUpdate) SetVerifiedAt(v time.Time) *ResellerDomainUpdate {
	_u.mutation.SetVerifiedAt(v)
	return _u
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (_u *ResellerDomainUpdate) SetNillableVerifiedAt(v *time.Time) *ResellerDomainUpdate {
	if v != nil {
		_u.SetVerifiedAt(*v)
	}
	return _u
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (_u *ResellerDomainUpdate) ClearVerifiedAt() *ResellerDomainUpdate {
	_u.mutation.ClearVerifiedAt()
	return _u
}

// SetReseller sets the "reseller" edge to the User entity.
func (_u *ResellerDomainUpdate) SetReseller(v *User) *ResellerDomainUpdate {
	return _u.SetResellerID(v.ID)
}

// Mutation returns the ResellerDomainMutation object of the builder.
func (_u *ResellerDomainUpdate) Mutation() *ResellerDomainMutation {
	return _u.mutation
}

// ClearReseller clears the "reseller" edge to the User entity.
func (_u *ResellerDomainUpdate) ClearReseller() *ResellerDomainUpdate {
	_u.mutation.ClearReseller()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ResellerDomainUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResellerDomainUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ResellerDomainUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResellerDomainUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResellerDomainUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if resellerdomain.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized resellerdomain.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := resellerdomain.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResellerDomainUpdate) check() error {
	if v, ok := _u.mutation.Domain(); ok {
		if err := resellerdomain.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.domain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SiteName(); ok {
		if err := resellerdomain.SiteNameValidator(v); err != nil {
			return &ValidationError{Name: "site_name", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.site_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BrandColor(); ok {
		if err := resellerdomain.BrandColorValidator(v); err != nil {
			return &ValidationError{Name: "brand_color", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.brand_color": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subtitle(); ok {
		if err := resellerdomain.SubtitleValidator(v); err != nil {
			return &ValidationError{Name: "subtitle", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.subtitle": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HomeTemplate(); ok {
		if err := resellerdomain.HomeTemplateValidator(v); err != nil {
			return &ValidationError{Name: "home_template", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.home_template": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DocURL(); ok {
		if err := resellerdomain.DocURLValidator(v); err != nil {
			return &ValidationError{Name: "doc_url", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.doc_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PurchaseURL(); ok {
		if err := resellerdomain.PurchaseURLValidator(v); err != nil {
			return &ValidationError{Name: "purchase_url", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.purchase_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultLocale(); ok {
		if err := resellerdomain.DefaultLocaleValidator(v); err != nil {
			return &ValidationError{Name: "default_locale", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.default_locale": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SeoTitle(); ok {
		if err := resellerdomain.SeoTitleValidator(v); err != nil {
			return &ValidationError{Name: "seo_title", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.seo_title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SeoKeywords(); ok {
		if err := resellerdomain.SeoKeywordsValidator(v); err != nil {
			return &ValidationError{Name: "seo_keywords", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.seo_keywords": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LoginRedirect(); ok {
		if err := resellerdomain.LoginRedirectValidator(v); err != nil {
			return &ValidationError{Name: "login_redirect", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.login_redirect": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VerifyToken(); ok {
		if err := resellerdomain.VerifyTokenValidator(v); err != nil {
			return &ValidationError{Name: "verify_token", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.verify_token": %w`, err)}
		}
	}
	if _u.mutation.ResellerCleared() && len(_u.mutation.ResellerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ResellerDomain.reseller"`)
	}
	return nil
}

func (_u *ResellerDomainUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resellerdomain.Table, resellerdomain.Columns, sqlgraph.NewFieldSpec(resellerdomain.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(resellerdomain.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(resellerdomain.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(resellerdomain.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(resellerdomain.FieldDomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.SiteName(); ok {
		_spec.SetField(resellerdomain.FieldSiteName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SiteLogo(); ok {
		_spec.SetField(resellerdomain.FieldSiteLogo, field.TypeString, value)
	}
	if value, ok := _u.mutation.BrandColor(); ok {
		_spec.SetField(resellerdomain.FieldBrandColor, field.TypeString, value)
	}
	if value, ok := _u.mutation.CustomCSS(); ok {
		_spec.SetField(resellerdomain.FieldCustomCSS, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subtitle(); ok {
		_spec.SetField(resellerdomain.FieldSubtitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.HomeContent(); ok {
		_spec.SetField(resellerdomain.FieldHomeContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.HomeTemplate(); ok {
		_spec.SetField(resellerdomain.FieldHomeTemplate, field.TypeString, value)
	}
	if value, ok := _u.mutation.DocURL(); ok {
		_spec.SetField(resellerdomain.FieldDocURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.PurchaseEnabled(); ok {
		_spec.SetField(resellerdomain.FieldPurchaseEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PurchaseURL(); ok {
		_spec.SetField(resellerdomain.FieldPurchaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultLocale(); ok {
		_spec.SetField(resellerdomain.FieldDefaultLocale, field.TypeString, value)
	}
	if value, ok := _u.mutation.SeoTitle(); ok {
		_spec.SetField(resellerdomain.FieldSeoTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.SeoDescription(); ok {
		_spec.SetField(resellerdomain.FieldSeoDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.SeoKeywords(); ok {
		_spec.SetField(resellerdomain.FieldSeoKeywords, field.TypeString, value)
	}
	if value, ok := _u.mutation.LoginRedirect(); ok {
		_spec.SetField(resellerdomain.FieldLoginRedirect, field.TypeString, value)
	}
	if value, ok := _u.mutation.VerifyToken(); ok {
		_spec.SetField(resellerdomain.FieldVerifyToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Verified(); ok {
		_spec.SetField(resellerdomain.FieldVerified, field.TypeBool, value)
	}
	if value, ok := _u.mutation.VerifiedAt(); ok {
		_spec.SetField(resellerdomain.FieldVerifiedAt, field.TypeTime, value)
	}
	if _u.mutation.VerifiedAtCleared() {
		_spec.ClearField(resellerdomain.FieldVerifiedAt, field.TypeTime)
	}
	if _u.mutation.ResellerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resellerdomain.ResellerTable,
			Columns: []string{resellerdomain.ResellerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResellerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resellerdomain.ResellerTable,
			Columns: []string{resellerdomain.ResellerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resellerdomain.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ResellerDomainUpdateOne is the builder for updating a single ResellerDomain entity.
type ResellerDomainUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ResellerDomainMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResellerDomainUpdateOne) SetUpdatedAt(v time.Time) *ResellerDomainUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ResellerDomainUpdateOne) SetDeletedAt(v time.Time) *ResellerDomainUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ResellerDomainUpdateOne) SetNillableDeletedAt(v *time.Time) *ResellerDomainUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ResellerDomainUpdateOne) ClearDeletedAt() *ResellerDomainUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetResellerID sets the "reseller_id" field.
func (_u *ResellerDomainUpdateOne) SetResellerID(v int64) *ResellerDomainUpdateOne {
	_u.mutation.SetResellerID(v)
	return _u
}

// SetNillableResellerID sets the "reseller_id" field if the given value is not nil.
func (_u *ResellerDomainUpdateOne) SetNillableResellerID(v *int64) *ResellerDomainUpdateOne {
	if v != nil {
		_u.SetResellerID(*v)
	}
	return _u
}

// SetDomain sets the "domain" field.
func (_u *ResellerDomainUpdateOne) SetDomain(v string) *ResellerDomainUpdateOne {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *ResellerDomainUpdateOne) SetNillableDomain(v *string) *ResellerDomainUpdateOne {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// SetSiteName sets the "site_name" field.
func (_u *ResellerDomainUpdateOne) SetSiteName(v string) *ResellerDomainUpdateOne {
	_u.mutation.SetSiteName(v)
	return _u
}

// SetNillableSiteName sets the "site_name" field if the given value is not nil.
func (_u *ResellerDomainUpdateOne) SetNillableSiteName(v *string) *ResellerDomainUpdateOne {
	if v != nil {
		_u.SetSiteName(*v)
	}
	return _u
}

// SetSiteLogo sets the "site_logo" field.
func (_u *ResellerDomainUpdateOne) SetSiteLogo(v string) *ResellerDomainUpdateOne {
	_u.mutation.SetSiteLogo(v)
	return _u
}

// SetNillableSiteLogo sets the "site_logo" field if the given value is not nil.
func (_u *ResellerDomainUpdateOne) SetNillableSiteLogo(v *string) *ResellerDomainUpdateOne {
	if v != nil {
		_u.SetSiteLogo(*v)
	}
	return _u
}

// SetBrandColor sets the "brand_color" field.
func (_u *ResellerDomainUpdateOne) SetBrandColor(v string) *ResellerDomainUpdateOne {
	_u.mutation.SetBrandColor(v)
	return _u
}

// SetNillableBrandColor sets the "brand_color" field if the given value is not nil.
func (_u *ResellerDomainUpdateOne) SetNillableBrandColor(v *string) *ResellerDomainUpdateOne {
	if v != nil {
		_u.SetBrandColor(*v)
	}
	return _u
}

// SetCustomCSS sets the "custom_css" field.
func (_u *ResellerDomainUpdateOne) SetCustomCSS(v string) *ResellerDomainUpdateOne {
	_u.mutation.SetCustomCSS(v)
	return _u
}

// SetNillableCustomCSS sets the "custom_css" field if the given value is not nil.
func (_u *ResellerDomainUpdateOne) SetNillableCustomCSS(v *string) *ResellerDomainUpdateOne {
	if v != nil {
		_u.SetCustomCSS(*v)
	}
	return _u
}

// SetSubtitle sets the "subtitle" field.
func (_u *ResellerDomainUpdateOne) SetSubtitle(v string) *ResellerDomainUpdateOne {
	_u.mutation.SetSubtitle(v)
	return _u
}

// SetNillableSubtitle sets the "subtitle" field if the given value is not nil.
func (_u *ResellerDomainUpdateOne) SetNillableSubtitle(v *string) *ResellerDomainUpdateOne {
	if v != nil {
		_u.SetSubtitle(*v)
	}
	return _u
}

// SetHomeContent sets the "home_content" field.
func (_u *ResellerDomainUpdateOne) SetHomeContent(v string) *ResellerDomainUpdateOne {
	_u.mutation.SetHomeContent(v)
	return _u
}

// SetNillableHomeContent sets the "home_content" field if the given value is not nil.
func (_u *ResellerDomainUpdateOne) SetNillableHomeContent(v *string) *ResellerDomainUpdateOne {
	if v != nil {
		_u.SetHomeContent(*v)
	}
	return _u
}

// SetHomeTemplate sets the "home_template" field.
func (_u *ResellerDomainUpdateOne) SetHomeTemplate(v string) *ResellerDomainUpdateOne {
	_u.mutation.SetHomeTemplate(v)
	return _u
}

// SetNillableHomeTemplate sets the "home_template" field if the given value is not nil.
func (_u *ResellerDomainUpdateOne) SetNillableHomeTemplate(v *string) *ResellerDomainUpdateOne {
	if v != nil {
		_u.SetHomeTemplate(*v)
	}
	return _u
}

// SetDocURL sets the "doc_url" field.
func (_u *ResellerDomainUpdateOne) SetDocURL(v string) *ResellerDomainUpdateOne {
	_u.mutation.SetDocURL(v)
	return _u
}

// SetNillableDocURL sets the "doc_url" field if the given value is not nil.
func (_u *ResellerDomainUpdateOne) SetNillableDocURL(v *string) *ResellerDomainUpdateOne {
	if v != nil {
		_u.SetDocURL(*v)
	}
	return _u
}

// SetPurchaseEnabled sets the "purchase_enabled" field.
func (_u *ResellerDomainUpdateOne) SetPurchaseEnabled(v bool) *ResellerDomainUpdateOne {
	_u.mutation.SetPurchaseEnabled(v)
	return _u
}

// SetNillablePurchaseEnabled sets the "purchase_enabled" field if the given value is not nil.
func (_u *ResellerDomainUpdateOne) SetNillablePurchaseEnabled(v *bool) *ResellerDomainUpdateOne {
	if v != nil {
		_u.SetPurchaseEnabled(*v)
	}
	return _u
}

// SetPurchaseURL sets the "purchase_url" field.
func (_u *ResellerDomainUpdateOne) SetPurchaseURL(v string) *ResellerDomainUpdateOne {
	_u.mutation.SetPurchaseURL(v)
	return _u
}

// SetNillablePurchaseURL sets the "purchase_url" field if the given value is not nil.
func (_u *ResellerDomainUpdateOne) SetNillablePurchaseURL(v *string) *ResellerDomainUpdateOne {
	if v != nil {
		_u.SetPurchaseURL(*v)
	}
	return _u
}

// SetDefaultLocale sets the "default_locale" field.
func (_u *ResellerDomainUpdateOne) SetDefaultLocale(v string) *ResellerDomainUpdateOne {
	_u.mutation.SetDefaultLocale(v)
	return _u
}

// SetNillableDefaultLocale sets the "default_locale" field if the given value is not nil.
func (_u *ResellerDomainUpdateOne) SetNillableDefaultLocale(v *string) *ResellerDomainUpdateOne {
	if v != nil {
		_u.SetDefaultLocale(*v)
	}
	return _u
}

// SetSeoTitle sets the "seo_title" field.
func (_u *ResellerDomainUpdateOne) SetSeoTitle(v string) *ResellerDomainUpdateOne {
	_u.mutation.SetSeoTitle(v)
	return _u
}

// SetNillableSeoTitle sets the "seo_title" field if the given value is not nil.
func (_u *ResellerDomainUpdateOne) SetNillableSeoTitle(v *string) *ResellerDomainUpdateOne {
	if v != nil {
		_u.SetSeoTitle(*v)
	}
	return _u
}

// SetSeoDescription sets the "seo_description" field.
func (_u *ResellerDomainUpdateOne) SetSeoDescription(v string) *ResellerDomainUpdateOne {
	_u.mutation.SetSeoDescription(v)
	return _u
}

// SetNillableSeoDescription sets the "seo_description" field if the given value is not nil.
func (_u *ResellerDomainUpdateOne) SetNillableSeoDescription(v *string) *ResellerDomainUpdateOne {
	if v != nil {
		_u.SetSeoDescription(*v)
	}
	return _u
}

// SetSeoKeywords sets the "seo_keywords" field.
func (_u *ResellerDomainUpdateOne) SetSeoKeywords(v string) *ResellerDomainUpdateOne {
	_u.mutation.SetSeoKeywords(v)
	return _u
}

// SetNillableSeoKeywords sets the "seo_keywords" field if the given value is not nil.
func (_u *ResellerDomainUpdateOne) SetNillableSeoKeywords(v *string) *ResellerDomainUpdateOne {
	if v != nil {
		_u.SetSeoKeywords(*v)
	}
	return _u
}

// SetLoginRedirect sets the "login_redirect" field.
func (_u *ResellerDomainUpdateOne) SetLoginRedirect(v string) *ResellerDomainUpdateOne {
	_u.mutation.SetLoginRedirect(v)
	return _u
}

// SetNillableLoginRedirect sets the "login_redirect" field if the given value is not nil.
func (_u *ResellerDomainUpdateOne) SetNillableLoginRedirect(v *string) *ResellerDomainUpdateOne {
	if v != nil {
		_u.SetLoginRedirect(*v)
	}
	return _u
}

// SetVerifyToken sets the "verify_token" field.
func (_u *ResellerDomainUpdateOne) SetVerifyToken(v string) *ResellerDomainUpdateOne {
	_u.mutation.SetVerifyToken(v)
	return _u
}

// SetNillableVerifyToken sets the "verify_token" field if the given value is not nil.
func (_u *ResellerDomainUpdateOne) SetNillableVerifyToken(v *string) *ResellerDomainUpdateOne {
	if v != nil {
		_u.SetVerifyToken(*v)
	}
	return _u
}

// SetVerified sets the "verified" field.
func (_u *ResellerDomainUpdateOne) SetVerified(v bool) *ResellerDomainUpdateOne {
	_u.mutation.SetVerified(v)
	return _u
}

// SetNillableVerified sets the "verified" field if the given value is not nil.
func (_u *ResellerDomainUpdateOne) SetNillableVerified(v *bool) *ResellerDomainUpdateOne {
	if v != nil {
		_u.SetVerified(*v)
	}
	return _u
}

// SetVerifiedAt sets the "verified_at" field.
func (_u *ResellerDomainUpdateOne) SetVerifiedAt(v time.Time) *ResellerDomainUpdateOne {
	_u.mutation.SetVerifiedAt(v)
	return _u
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (_u *ResellerDomainUpdateOne) SetNillableVerifiedAt(v *time.Time) *ResellerDomainUpdateOne {
	if v != nil {
		_u.SetVerifiedAt(*v)
	}
	return _u
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (_u *ResellerDomainUpdateOne) ClearVerifiedAt() *ResellerDomainUpdateOne {
	_u.mutation.ClearVerifiedAt()
	return _u
}

// SetReseller sets the "reseller" edge to the User entity.
func (_u *ResellerDomainUpdateOne) SetReseller(v *User) *ResellerDomainUpdateOne {
	return _u.SetResellerID(v.ID)
}

// Mutation returns the ResellerDomainMutation object of the builder.
func (_u *ResellerDomainUpdateOne) Mutation() *ResellerDomainMutation {
	return _u.mutation
}

// ClearReseller clears the "reseller" edge to the User entity.
func (_u *ResellerDomainUpdateOne) ClearReseller() *ResellerDomainUpdateOne {
	_u.mutation.ClearReseller()
	return _u
}

// Where appends a list predicates to the ResellerDomainUpdate builder.
func (_u *ResellerDomainUpdateOne) Where(ps ...predicate.ResellerDomain) *ResellerDomainUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ResellerDomainUpdateOne) Select(field string, fields ...string) *ResellerDomainUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ResellerDomain entity.
func (_u *ResellerDomainUpdateOne) Save(ctx context.Context) (*ResellerDomain, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResellerDomainUpdateOne) SaveX(ctx context.Context) *ResellerDomain {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ResellerDomainUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResellerDomainUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResellerDomainUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if resellerdomain.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized resellerdomain.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := resellerdomain.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResellerDomainUpdateOne) check() error {
	if v, ok := _u.mutation.Domain(); ok {
		if err := resellerdomain.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.domain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SiteName(); ok {
		if err := resellerdomain.SiteNameValidator(v); err != nil {
			return &ValidationError{Name: "site_name", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.site_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BrandColor(); ok {
		if err := resellerdomain.BrandColorValidator(v); err != nil {
			return &ValidationError{Name: "brand_color", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.brand_color": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subtitle(); ok {
		if err := resellerdomain.SubtitleValidator(v); err != nil {
			return &ValidationError{Name: "subtitle", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.subtitle": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HomeTemplate(); ok {
		if err := resellerdomain.HomeTemplateValidator(v); err != nil {
			return &ValidationError{Name: "home_template", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.home_template": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DocURL(); ok {
		if err := resellerdomain.DocURLValidator(v); err != nil {
			return &ValidationError{Name: "doc_url", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.doc_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PurchaseURL(); ok {
		if err := resellerdomain.PurchaseURLValidator(v); err != nil {
			return &ValidationError{Name: "purchase_url", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.purchase_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultLocale(); ok {
		if err := resellerdomain.DefaultLocaleValidator(v); err != nil {
			return &ValidationError{Name: "default_locale", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.default_locale": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SeoTitle(); ok {
		if err := resellerdomain.SeoTitleValidator(v); err != nil {
			return &ValidationError{Name: "seo_title", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.seo_title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SeoKeywords(); ok {
		if err := resellerdomain.SeoKeywordsValidator(v); err != nil {
			return &ValidationError{Name: "seo_keywords", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.seo_keywords": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LoginRedirect(); ok {
		if err := resellerdomain.LoginRedirectValidator(v); err != nil {
			return &ValidationError{Name: "login_redirect", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.login_redirect": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VerifyToken(); ok {
		if err := resellerdomain.VerifyTokenValidator(v); err != nil {
			return &ValidationError{Name: "verify_token", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.verify_token": %w`, err)}
		}
	}
	if _u.mutation.ResellerCleared() && len(_u.mutation.ResellerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ResellerDomain.reseller"`)
	}
	return nil
}

func (_u *ResellerDomainUpdateOne) sqlSave(ctx context.Context) (_node *ResellerDomain, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resellerdomain.Table, resellerdomain.Columns, sqlgraph.NewFieldSpec(resellerdomain.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ResellerDomain.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, resellerdomain.FieldID)
		for _, f := range fields {
			if !resellerdomain.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != resellerdomain.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(resellerdomain.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(resellerdomain.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(resellerdomain.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(resellerdomain.FieldDomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.SiteName(); ok {
		_spec.SetField(resellerdomain.FieldSiteName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SiteLogo(); ok {
		_spec.SetField(resellerdomain.FieldSiteLogo, field.TypeString, value)
	}
	if value, ok := _u.mutation.BrandColor(); ok {
		_spec.SetField(resellerdomain.FieldBrandColor, field.TypeString, value)
	}
	if value, ok := _u.mutation.CustomCSS(); ok {
		_spec.SetField(resellerdomain.FieldCustomCSS, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subtitle(); ok {
		_spec.SetField(resellerdomain.FieldSubtitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.HomeContent(); ok {
		_spec.SetField(resellerdomain.FieldHomeContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.HomeTemplate(); ok {
		_spec.SetField(resellerdomain.FieldHomeTemplate, field.TypeString, value)
	}
	if value, ok := _u.mutation.DocURL(); ok {
		_spec.SetField(resellerdomain.FieldDocURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.PurchaseEnabled(); ok {
		_spec.SetField(resellerdomain.FieldPurchaseEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PurchaseURL(); ok {
		_spec.SetField(resellerdomain.FieldPurchaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultLocale(); ok {
		_spec.SetField(resellerdomain.FieldDefaultLocale, field.TypeString, value)
	}
	if value, ok := _u.mutation.SeoTitle(); ok {
		_spec.SetField(resellerdomain.FieldSeoTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.SeoDescription(); ok {
		_spec.SetField(resellerdomain.FieldSeoDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.SeoKeywords(); ok {
		_spec.SetField(resellerdomain.FieldSeoKeywords, field.TypeString, value)
	}
	if value, ok := _u.mutation.LoginRedirect(); ok {
		_spec.SetField(resellerdomain.FieldLoginRedirect, field.TypeString, value)
	}
	if value, ok := _u.mutation.VerifyToken(); ok {
		_spec.SetField(resellerdomain.FieldVerifyToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Verified(); ok {
		_spec.SetField(resellerdomain.FieldVerified, field.TypeBool, value)
	}
	if value, ok := _u.mutation.VerifiedAt(); ok {
		_spec.SetField(resellerdomain.FieldVerifiedAt, field.TypeTime, value)
	}
	if _u.mutation.VerifiedAtCleared() {
		_spec.ClearField(resellerdomain.FieldVerifiedAt, field.TypeTime)
	}
	if _u.mutation.ResellerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resellerdomain.ResellerTable,
			Columns: []string{resellerdomain.ResellerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResellerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resellerdomain.ResellerTable,
			Columns: []string{resellerdomain.ResellerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ResellerDomain{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resellerdomain.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
