// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/resellerdomain"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ResellerDomainCreate is the builder for creating a ResellerDomain entity.
type ResellerDomainCreate struct {
	config
	mutation *ResellerDomainMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ResellerDomainCreate) SetCreatedAt(v time.Time) *ResellerDomainCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ResellerDomainCreate) SetNillableCreatedAt(v *time.Time) *ResellerDomainCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ResellerDomainCreate) SetUpdatedAt(v time.Time) *ResellerDomainCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ResellerDomainCreate) SetNillableUpdatedAt(v *time.Time) *ResellerDomainCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ResellerDomainCreate) SetDeletedAt(v time.Time) *ResellerDomainCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ResellerDomainCreate) SetNillableDeletedAt(v *time.Time) *ResellerDomainCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetResellerID sets the "reseller_id" field.
func (_c *ResellerDomainCreate) SetResellerID(v int64) *ResellerDomainCreate {
	_c.mutation.SetResellerID(v)
	return _c
}

// SetDomain sets the "domain" field.
func (_c *ResellerDomainCreate) SetDomain(v string) *ResellerDomainCreate {
	_c.mutation.SetDomain(v)
	return _c
}

// SetSiteName sets the "site_name" field.
func (_c *ResellerDomainCreate) SetSiteName(v string) *ResellerDomainCreate {
	_c.mutation.SetSiteName(v)
	return _c
}

// SetNillableSiteName sets the "site_name" field if the given value is not nil.
func (_c *ResellerDomainCreate) SetNillableSiteName(v *string) *ResellerDomainCreate {
	if v != nil {
		_c.SetSiteName(*v)
	}
	return _c
}

// SetSiteLogo sets the "site_logo" field.
func (_c *ResellerDomainCreate) SetSiteLogo(v string) *ResellerDomainCreate {
	_c.mutation.SetSiteLogo(v)
	return _c
}

// SetNillableSiteLogo sets the "site_logo" field if the given value is not nil.
func (_c *ResellerDomainCreate) SetNillableSiteLogo(v *string) *ResellerDomainCreate {
	if v != nil {
		_c.SetSiteLogo(*v)
	}
	return _c
}

// SetBrandColor sets the "brand_color" field.
func (_c *ResellerDomainCreate) SetBrandColor(v string) *ResellerDomainCreate {
	_c.mutation.SetBrandColor(v)
	return _c
}

// SetNillableBrandColor sets the "brand_color" field if the given value is not nil.
func (_c *ResellerDomainCreate) SetNillableBrandColor(v *string) *ResellerDomainCreate {
	if v != nil {
		_c.SetBrandColor(*v)
	}
	return _c
}

// SetCustomCSS sets the "custom_css" field.
func (_c *ResellerDomainCreate) SetCustomCSS(v string) *ResellerDomainCreate {
	_c.mutation.SetCustomCSS(v)
	return _c
}

// SetNillableCustomCSS sets the "custom_css" field if the given value is not nil.
func (_c *ResellerDomainCreate) SetNillableCustomCSS(v *string) *ResellerDomainCreate {
	if v != nil {
		_c.SetCustomCSS(*v)
	}
	return _c
}

// SetSubtitle sets the "subtitle" field.
func (_c *ResellerDomainCreate) SetSubtitle(v string) *ResellerDomainCreate {
	_c.mutation.SetSubtitle(v)
	return _c
}

// SetNillableSubtitle sets the "subtitle" field if the given value is not nil.
func (_c *ResellerDomainCreate) SetNillableSubtitle(v *string) *ResellerDomainCreate {
	if v != nil {
		_c.SetSubtitle(*v)
	}
	return _c
}

// SetHomeContent sets the "home_content" field.
func (_c *ResellerDomainCreate) SetHomeContent(v string) *ResellerDomainCreate {
	_c.mutation.SetHomeContent(v)
	return _c
}

// SetNillableHomeContent sets the "home_content" field if the given value is not nil.
func (_c *ResellerDomainCreate) SetNillableHomeContent(v *string) *ResellerDomainCreate {
	if v != nil {
		_c.SetHomeContent(*v)
	}
	return _c
}

// SetHomeTemplate sets the "home_template" field.
func (_c *ResellerDomainCreate) SetHomeTemplate(v string) *ResellerDomainCreate {
	_c.mutation.SetHomeTemplate(v)
	return _c
}

// SetNillableHomeTemplate sets the "home_template" field if the given value is not nil.
func (_c *ResellerDomainCreate) SetNillableHomeTemplate(v *string) *ResellerDomainCreate {
	if v != nil {
		_c.SetHomeTemplate(*v)
	}
	return _c
}

// SetDocURL sets the "doc_url" field.
func (_c *ResellerDomainCreate) SetDocURL(v string) *ResellerDomainCreate {
	_c.mutation.SetDocURL(v)
	return _c
}

// SetNillableDocURL sets the "doc_url" field if the given value is not nil.
func (_c *ResellerDomainCreate) SetNillableDocURL(v *string) *ResellerDomainCreate {
	if v != nil {
		_c.SetDocURL(*v)
	}
	return _c
}

// SetPurchaseEnabled sets the "purchase_enabled" field.
func (_c *ResellerDomainCreate) SetPurchaseEnabled(v bool) *ResellerDomainCreate {
	_c.mutation.SetPurchaseEnabled(v)
	return _c
}

// SetNillablePurchaseEnabled sets the "purchase_enabled" field if the given value is not nil.
func (_c *ResellerDomainCreate) SetNillablePurchaseEnabled(v *bool) *ResellerDomainCreate {
	if v != nil {
		_c.SetPurchaseEnabled(*v)
	}
	return _c
}

// SetPurchaseURL sets the "purchase_url" field.
func (_c *ResellerDomainCreate) SetPurchaseURL(v string) *ResellerDomainCreate {
	_c.mutation.SetPurchaseURL(v)
	return _c
}

// SetNillablePurchaseURL sets the "purchase_url" field if the given value is not nil.
func (_c *ResellerDomainCreate) SetNillablePurchaseURL(v *string) *ResellerDomainCreate {
	if v != nil {
		_c.SetPurchaseURL(*v)
	}
	return _c
}

// SetDefaultLocale sets the "default_locale" field.
func (_c *ResellerDomainCreate) SetDefaultLocale(v string) *ResellerDomainCreate {
	_c.mutation.SetDefaultLocale(v)
	return _c
}

// SetNillableDefaultLocale sets the "default_locale" field if the given value is not nil.
func (_c *ResellerDomainCreate) SetNillableDefaultLocale(v *string) *ResellerDomainCreate {
	if v != nil {
		_c.SetDefaultLocale(*v)
	}
	return _c
}

// SetSeoTitle sets the "seo_title" field.
func (_c *ResellerDomainCreate) SetSeoTitle(v string) *ResellerDomainCreate {
	_c.mutation.SetSeoTitle(v)
	return _c
}

// SetNillableSeoTitle sets the "seo_title" field if the given value is not nil.
func (_c *ResellerDomainCreate) SetNillableSeoTitle(v *string) *ResellerDomainCreate {
	if v != nil {
		_c.SetSeoTitle(*v)
	}
	return _c
}

// SetSeoDescription sets the "seo_description" field.
func (_c *ResellerDomainCreate) SetSeoDescription(v string) *ResellerDomainCreate {
	_c.mutation.SetSeoDescription(v)
	return _c
}

// SetNillableSeoDescription sets the "seo_description" field if the given value is not nil.
func (_c *ResellerDomainCreate) SetNillableSeoDescription(v *string) *ResellerDomainCreate {
	if v != nil {
		_c.SetSeoDescription(*v)
	}
	return _c
}

// SetSeoKeywords sets the "seo_keywords" field.
func (_c *ResellerDomainCreate) SetSeoKeywords(v string) *ResellerDomainCreate {
	_c.mutation.SetSeoKeywords(v)
	return _c
}

// SetNillableSeoKeywords sets the "seo_keywords" field if the given value is not nil.
func (_c *ResellerDomainCreate) SetNillableSeoKeywords(v *string) *ResellerDomainCreate {
	if v != nil {
		_c.SetSeoKeywords(*v)
	}
	return _c
}

// SetLoginRedirect sets the "login_redirect" field.
func (_c *ResellerDomainCreate) SetLoginRedirect(v string) *ResellerDomainCreate {
	_c.mutation.SetLoginRedirect(v)
	return _c
}

// SetNillableLoginRedirect sets the "login_redirect" field if the given value is not nil.
func (_c *ResellerDomainCreate) SetNillableLoginRedirect(v *string) *ResellerDomainCreate {
	if v != nil {
		_c.SetLoginRedirect(*v)
	}
	return _c
}

// SetVerifyToken sets the "verify_token" field.
func (_c *ResellerDomainCreate) SetVerifyToken(v string) *ResellerDomainCreate {
	_c.mutation.SetVerifyToken(v)
	return _c
}

// SetNillableVerifyToken sets the "verify_token" field if the given value is not nil.
func (_c *ResellerDomainCreate) SetNillableVerifyToken(v *string) *ResellerDomainCreate {
	if v != nil {
		_c.SetVerifyToken(*v)
	}
	return _c
}

// SetVerified sets the "verified" field.
func (_c *ResellerDomainCreate) SetVerified(v bool) *ResellerDomainCreate {
	_c.mutation.SetVerified(v)
	return _c
}

// SetNillableVerified sets the "verified" field if the given value is not nil.
func (_c *ResellerDomainCreate) SetNillableVerified(v *bool) *ResellerDomainCreate {
	if v != nil {
		_c.SetVerified(*v)
	}
	return _c
}

// SetVerifiedAt sets the "verified_at" field.
func (_c *ResellerDomainCreate) SetVerifiedAt(v time.Time) *ResellerDomainCreate {
	_c.mutation.SetVerifiedAt(v)
	return _c
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (_c *ResellerDomainCreate) SetNillableVerifiedAt(v *time.Time) *ResellerDomainCreate {
	if v != nil {
		_c.SetVerifiedAt(*v)
	}
	return _c
}

// SetReseller sets the "reseller" edge to the User entity.
func (_c *ResellerDomainCreate) SetReseller(v *User) *ResellerDomainCreate {
	return _c.SetResellerID(v.ID)
}

// Mutation returns the ResellerDomainMutation object of the builder.
func (_c *ResellerDomainCreate) Mutation() *ResellerDomainMutation {
	return _c.mutation
}

// Save creates the ResellerDomain in the database.
func (_c *ResellerDomainCreate) Save(ctx context.Context) (*ResellerDomain, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ResellerDomainCreate) SaveX(ctx context.Context) *ResellerDomain {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResellerDomainCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResellerDomainCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ResellerDomainCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if resellerdomain.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized resellerdomain.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := resellerdomain.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if resellerdomain.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized resellerdomain.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := resellerdomain.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.SiteName(); !ok {
		v := resellerdomain.DefaultSiteName
		_c.mutation.SetSiteName(v)
	}
	if _, ok := _c.mutation.SiteLogo(); !ok {
		v := resellerdomain.DefaultSiteLogo
		_c.mutation.SetSiteLogo(v)
	}
	if _, ok := _c.mutation.BrandColor(); !ok {
		v := resellerdomain.DefaultBrandColor
		_c.mutation.SetBrandColor(v)
	}
	if _, ok := _c.mutation.CustomCSS(); !ok {
		v := resellerdomain.DefaultCustomCSS
		_c.mutation.SetCustomCSS(v)
	}
	if _, ok := _c.mutation.Subtitle(); !ok {
		v := resellerdomain.DefaultSubtitle
		_c.mutation.SetSubtitle(v)
	}
	if _, ok := _c.mutation.HomeContent(); !ok {
		v := resellerdomain.DefaultHomeContent
		_c.mutation.SetHomeContent(v)
	}
	if _, ok := _c.mutation.HomeTemplate(); !ok {
		v := resellerdomain.DefaultHomeTemplate
		_c.mutation.SetHomeTemplate(v)
	}
	if _, ok := _c.mutation.DocURL(); !ok {
		v := resellerdomain.DefaultDocURL
		_c.mutation.SetDocURL(v)
	}
	if _, ok := _c.mutation.PurchaseEnabled(); !ok {
		v := resellerdomain.DefaultPurchaseEnabled
		_c.mutation.SetPurchaseEnabled(v)
	}
	if _, ok := _c.mutation.PurchaseURL(); !ok {
		v := resellerdomain.DefaultPurchaseURL
		_c.mutation.SetPurchaseURL(v)
	}
	if _, ok := _c.mutation.DefaultLocale(); !ok {
		v := resellerdomain.DefaultDefaultLocale
		_c.mutation.SetDefaultLocale(v)
	}
	if _, ok := _c.mutation.SeoTitle(); !ok {
		v := resellerdomain.DefaultSeoTitle
		_c.mutation.SetSeoTitle(v)
	}
	if _, ok := _c.mutation.SeoDescription(); !ok {
		v := resellerdomain.DefaultSeoDescription
		_c.mutation.SetSeoDescription(v)
	}
	if _, ok := _c.mutation.SeoKeywords(); !ok {
		v := resellerdomain.DefaultSeoKeywords
		_c.mutation.SetSeoKeywords(v)
	}
	if _, ok := _c.mutation.LoginRedirect(); !ok {
		v := resellerdomain.DefaultLoginRedirect
		_c.mutation.SetLoginRedirect(v)
	}
	if _, ok := _c.mutation.VerifyToken(); !ok {
		v := resellerdomain.DefaultVerifyToken
		_c.mutation.SetVerifyToken(v)
	}
	if _, ok := _c.mutation.Verified(); !ok {
		v := resellerdomain.DefaultVerified
		_c.mutation.SetVerified(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ResellerDomainCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ResellerDomain.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ResellerDomain.updated_at"`)}
	}
	if _, ok := _c.mutation.ResellerID(); !ok {
		return &ValidationError{Name: "reseller_id", err: errors.New(`ent: missing required field "ResellerDomain.reseller_id"`)}
	}
	if _, ok := _c.mutation.Domain(); !ok {
		return &ValidationError{Name: "domain", err: errors.New(`ent: missing required field "ResellerDomain.domain"`)}
	}
	if v, ok := _c.mutation.Domain(); ok {
		if err := resellerdomain.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.domain": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SiteName(); !ok {
		return &ValidationError{Name: "site_name", err: errors.New(`ent: missing required field "ResellerDomain.site_name"`)}
	}
	if v, ok := _c.mutation.SiteName(); ok {
		if err := resellerdomain.SiteNameValidator(v); err != nil {
			return &ValidationError{Name: "site_name", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.site_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SiteLogo(); !ok {
		return &ValidationError{Name: "site_logo", err: errors.New(`ent: missing required field "ResellerDomain.site_logo"`)}
	}
	if _, ok := _c.mutation.BrandColor(); !ok {
		return &ValidationError{Name: "brand_color", err: errors.New(`ent: missing required field "ResellerDomain.brand_color"`)}
	}
	if v, ok := _c.mutation.BrandColor(); ok {
		if err := resellerdomain.BrandColorValidator(v); err != nil {
			return &ValidationError{Name: "brand_color", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.brand_color": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CustomCSS(); !ok {
		return &ValidationError{Name: "custom_css", err: errors.New(`ent: missing required field "ResellerDomain.custom_css"`)}
	}
	if _, ok := _c.mutation.Subtitle(); !ok {
		return &ValidationError{Name: "subtitle", err: errors.New(`ent: missing required field "ResellerDomain.subtitle"`)}
	}
	if v, ok := _c.mutation.Subtitle(); ok {
		if err := resellerdomain.SubtitleValidator(v); err != nil {
			return &ValidationError{Name: "subtitle", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.subtitle": %w`, err)}
		}
	}
	if _, ok := _c.mutation.HomeContent(); !ok {
		return &ValidationError{Name: "home_content", err: errors.New(`ent: missing required field "ResellerDomain.home_content"`)}
	}
	if _, ok := _c.mutation.HomeTemplate(); !ok {
		return &ValidationError{Name: "home_template", err: errors.New(`ent: missing required field "ResellerDomain.home_template"`)}
	}
	if v, ok := _c.mutation.HomeTemplate(); ok {
		if err := resellerdomain.HomeTemplateValidator(v); err != nil {
			return &ValidationError{Name: "home_template", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.home_template": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DocURL(); !ok {
		return &ValidationError{Name: "doc_url", err: errors.New(`ent: missing required field "ResellerDomain.doc_url"`)}
	}
	if v, ok := _c.mutation.DocURL(); ok {
		if err := resellerdomain.DocURLValidator(v); err != nil {
			return &ValidationError{Name: "doc_url", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.doc_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PurchaseEnabled(); !ok {
		return &ValidationError{Name: "purchase_enabled", err: errors.New(`ent: missing required field "ResellerDomain.purchase_enabled"`)}
	}
	if _, ok := _c.mutation.PurchaseURL(); !ok {
		return &ValidationError{Name: "purchase_url", err: errors.New(`ent: missing required field "ResellerDomain.purchase_url"`)}
	}
	if v, ok := _c.mutation.PurchaseURL(); ok {
		if err := resellerdomain.PurchaseURLValidator(v); err != nil {
			return &ValidationError{Name: "purchase_url", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.purchase_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DefaultLocale(); !ok {
		return &ValidationError{Name: "default_locale", err: errors.New(`ent: missing required field "ResellerDomain.default_locale"`)}
	}
	if v, ok := _c.mutation.DefaultLocale(); ok {
		if err := resellerdomain.DefaultLocaleValidator(v); err != nil {
			return &ValidationError{Name: "default_locale", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.default_locale": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SeoTitle(); !ok {
		return &ValidationError{Name: "seo_title", err: errors.New(`ent: missing required field "ResellerDomain.seo_title"`)}
	}
	if v, ok := _c.mutation.SeoTitle(); ok {
		if err := resellerdomain.SeoTitleValidator(v); err != nil {
			return &ValidationError{Name: "seo_title", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.seo_title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SeoDescription(); !ok {
		return &ValidationError{Name: "seo_description", err: errors.New(`ent: missing required field "ResellerDomain.seo_description"`)}
	}
	if _, ok := _c.mutation.SeoKeywords(); !ok {
		return &ValidationError{Name: "seo_keywords", err: errors.New(`ent: missing required field "ResellerDomain.seo_keywords"`)}
	}
	if v, ok := _c.mutation.SeoKeywords(); ok {
		if err := resellerdomain.SeoKeywordsValidator(v); err != nil {
			return &ValidationError{Name: "seo_keywords", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.seo_keywords": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LoginRedirect(); !ok {
		return &ValidationError{Name: "login_redirect", err: errors.New(`ent: missing required field "ResellerDomain.login_redirect"`)}
	}
	if v, ok := _c.mutation.LoginRedirect(); ok {
		if err := resellerdomain.LoginRedirectValidator(v); err != nil {
			return &ValidationError{Name: "login_redirect", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.login_redirect": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VerifyToken(); !ok {
		return &ValidationError{Name: "verify_token", err: errors.New(`ent: missing required field "ResellerDomain.verify_token"`)}
	}
	if v, ok := _c.mutation.VerifyToken(); ok {
		if err := resellerdomain.VerifyTokenValidator(v); err != nil {
			return &ValidationError{Name: "verify_token", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.verify_token": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Verified(); !ok {
		return &ValidationError{Name: "verified", err: errors.New(`ent: missing required field "ResellerDomain.verified"`)}
	}
	if len(_c.mutation.ResellerIDs()) == 0 {
		return &ValidationError{Name: "reseller", err: errors.New(`ent: missing required edge "ResellerDomain.reseller"`)}
	}
	return nil
}

func (_c *ResellerDomainCreate) sqlSave(ctx context.Context) (*ResellerDomain, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ResellerDomainCreate) createSpec() (*ResellerDomain, *sqlgraph.CreateSpec) {
	var (
		_node = &ResellerDomain{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(resellerdomain.Table, sqlgraph.NewFieldSpec(resellerdomain.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(resellerdomain.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(resellerdomain.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(resellerdomain.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Domain(); ok {
		_spec.SetField(resellerdomain.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := _c.mutation.SiteName(); ok {
		_spec.SetField(resellerdomain.FieldSiteName, field.TypeString, value)
		_node.SiteName = value
	}
	if value, ok := _c.mutation.SiteLogo(); ok {
		_spec.SetField(resellerdomain.FieldSiteLogo, field.TypeString, value)
		_node.SiteLogo = value
	}
	if value, ok := _c.mutation.BrandColor(); ok {
		_spec.SetField(resellerdomain.FieldBrandColor, field.TypeString, value)
		_node.BrandColor = value
	}
	if value, ok := _c.mutation.CustomCSS(); ok {
		_spec.SetField(resellerdomain.FieldCustomCSS, field.TypeString, value)
		_node.CustomCSS = value
	}
	if value, ok := _c.mutation.Subtitle(); ok {
		_spec.SetField(resellerdomain.FieldSubtitle, field.TypeString, value)
		_node.Subtitle = value
	}
	if value, ok := _c.mutation.HomeContent(); ok {
		_spec.SetField(resellerdomain.FieldHomeContent, field.TypeString, value)
		_node.HomeContent = value
	}
	if value, ok := _c.mutation.HomeTemplate(); ok {
		_spec.SetField(resellerdomain.FieldHomeTemplate, field.TypeString, value)
		_node.HomeTemplate = value
	}
	if value, ok := _c.mutation.DocURL(); ok {
		_spec.SetField(resellerdomain.FieldDocURL, field.TypeString, value)
		_node.DocURL = value
	}
	if value, ok := _c.mutation.PurchaseEnabled(); ok {
		_spec.SetField(resellerdomain.FieldPurchaseEnabled, field.TypeBool, value)
		_node.PurchaseEnabled = value
	}
	if value, ok := _c.mutation.PurchaseURL(); ok {
		_spec.SetField(resellerdomain.FieldPurchaseURL, field.TypeString, value)
		_node.PurchaseURL = value
	}
	if value, ok := _c.mutation.DefaultLocale(); ok {
		_spec.SetField(resellerdomain.FieldDefaultLocale, field.TypeString, value)
		_node.DefaultLocale = value
	}
	if value, ok := _c.mutation.SeoTitle(); ok {
		_spec.SetField(resellerdomain.FieldSeoTitle, field.TypeString, value)
		_node.SeoTitle = value
	}
	if value, ok := _c.mutation.SeoDescription(); ok {
		_spec.SetField(resellerdomain.FieldSeoDescription, field.TypeString, value)
		_node.SeoDescription = value
	}
	if value, ok := _c.mutation.SeoKeywords(); ok {
		_spec.SetField(resellerdomain.FieldSeoKeywords, field.TypeString, value)
		_node.SeoKeywords = value
	}
	if value, ok := _c.mutation.LoginRedirect(); ok {
		_spec.SetField(resellerdomain.FieldLoginRedirect, field.TypeString, value)
		_node.LoginRedirect = value
	}
	if value, ok := _c.mutation.VerifyToken(); ok {
		_spec.SetField(resellerdomain.FieldVerifyToken, field.TypeString, value)
		_node.VerifyToken = value
	}
	if value, ok := _c.mutation.Verified(); ok {
		_spec.SetField(resellerdomain.FieldVerified, field.TypeBool, value)
		_node.Verified = value
	}
	if value, ok := _c.mutation.VerifiedAt(); ok {
		_spec.SetField(resellerdomain.FieldVerifiedAt, field.TypeTime, value)
		_node.VerifiedAt = &value
	}
	if nodes := _c.mutation.ResellerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resellerdomain.ResellerTable,
			Columns: []string{resellerdomain.ResellerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ResellerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResellerDomain.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResellerDomainUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ResellerDomainCreate) OnConflict(opts ...sql.ConflictOption) *ResellerDomainUpsertOne {
	_c.conflict = opts
	return &ResellerDomainUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResellerDomain.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResellerDomainCreate) OnConflictColumns(columns ...string) *ResellerDomainUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResellerDomainUpsertOne{
		create: _c,
	}
}

type (
	// ResellerDomainUpsertOne is the builder for "upsert"-ing
	//  one ResellerDomain node.
	ResellerDomainUpsertOne struct {
		create *ResellerDomainCreate
	}

	// ResellerDomainUpsert is the "OnConflict" setter.
	ResellerDomainUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ResellerDomainUpsert) SetUpdatedAt(v time.Time) *ResellerDomainUpsert {
	u.Set(resellerdomain.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResellerDomainUpsert) UpdateUpdatedAt() *ResellerDomainUpsert {
	u.SetExcluded(resellerdomain.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ResellerDomainUpsert) SetDeletedAt(v time.Time) *ResellerDomainUpsert {
	u.Set(resellerdomain.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ResellerDomainUpsert) UpdateDeletedAt() *ResellerDomainUpsert {
	u.SetExcluded(resellerdomain.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ResellerDomainUpsert) ClearDeletedAt() *ResellerDomainUpsert {
	u.SetNull(resellerdomain.FieldDeletedAt)
	return u
}

// SetResellerID sets the "reseller_id" field.
func (u *ResellerDomainUpsert) SetResellerID(v int64) *ResellerDomainUpsert {
	u.Set(resellerdomain.FieldResellerID, v)
	return u
}

// UpdateResellerID sets the "reseller_id" field to the value that was provided on create.
func (u *ResellerDomainUpsert) UpdateResellerID() *ResellerDomainUpsert {
	u.SetExcluded(resellerdomain.FieldResellerID)
	return u
}

// SetDomain sets the "domain" field.
func (u *ResellerDomainUpsert) SetDomain(v string) *ResellerDomainUpsert {
	u.Set(resellerdomain.FieldDomain, v)
	return u
}

// UpdateDomain sets the "domain" field to the value that was provided on create.
func (u *ResellerDomainUpsert) UpdateDomain() *ResellerDomainUpsert {
	u.SetExcluded(resellerdomain.FieldDomain)
	return u
}

// SetSiteName sets the "site_name" field.
func (u *ResellerDomainUpsert) SetSiteName(v string) *ResellerDomainUpsert {
	u.Set(resellerdomain.FieldSiteName, v)
	return u
}

// UpdateSiteName sets the "site_name" field to the value that was provided on create.
func (u *ResellerDomainUpsert) UpdateSiteName() *ResellerDomainUpsert {
	u.SetExcluded(resellerdomain.FieldSiteName)
	return u
}

// SetSiteLogo sets the "site_logo" field.
func (u *ResellerDomainUpsert) SetSiteLogo(v string) *ResellerDomainUpsert {
	u.Set(resellerdomain.FieldSiteLogo, v)
	return u
}

// UpdateSiteLogo sets the "site_logo" field to the value that was provided on create.
func (u *ResellerDomainUpsert) UpdateSiteLogo() *ResellerDomainUpsert {
	u.SetExcluded(resellerdomain.FieldSiteLogo)
	return u
}

// SetBrandColor sets the "brand_color" field.
func (u *ResellerDomainUpsert) SetBrandColor(v string) *ResellerDomainUpsert {
	u.Set(resellerdomain.FieldBrandColor, v)
	return u
}

// UpdateBrandColor sets the "brand_color" field to the value that was provided on create.
func (u *ResellerDomainUpsert) UpdateBrandColor() *ResellerDomainUpsert {
	u.SetExcluded(resellerdomain.FieldBrandColor)
	return u
}

// SetCustomCSS sets the "custom_css" field.
func (u *ResellerDomainUpsert) SetCustomCSS(v string) *ResellerDomainUpsert {
	u.Set(resellerdomain.FieldCustomCSS, v)
	return u
}

// UpdateCustomCSS sets the "custom_css" field to the value that was provided on create.
func (u *ResellerDomainUpsert) UpdateCustomCSS() *ResellerDomainUpsert {
	u.SetExcluded(resellerdomain.FieldCustomCSS)
	return u
}

// SetSubtitle sets the "subtitle" field.
func (u *ResellerDomainUpsert) SetSubtitle(v string) *ResellerDomainUpsert {
	u.Set(resellerdomain.FieldSubtitle, v)
	return u
}

// UpdateSubtitle sets the "subtitle" field to the value that was provided on create.
func (u *ResellerDomainUpsert) UpdateSubtitle() *ResellerDomainUpsert {
	u.SetExcluded(resellerdomain.FieldSubtitle)
	return u
}

// SetHomeContent sets the "home_content" field.
func (u *ResellerDomainUpsert) SetHomeContent(v string) *ResellerDomainUpsert {
	u.Set(resellerdomain.FieldHomeContent, v)
	return u
}

// UpdateHomeContent sets the "home_content" field to the value that was provided on create.
func (u *ResellerDomainUpsert) UpdateHomeContent() *ResellerDomainUpsert {
	u.SetExcluded(resellerdomain.FieldHomeContent)
	return u
}

// SetHomeTemplate sets the "home_template" field.
func (u *ResellerDomainUpsert) SetHomeTemplate(v string) *ResellerDomainUpsert {
	u.Set(resellerdomain.FieldHomeTemplate, v)
	return u
}

// UpdateHomeTemplate sets the "home_template" field to the value that was provided on create.
func (u *ResellerDomainUpsert) UpdateHomeTemplate() *ResellerDomainUpsert {
	u.SetExcluded(resellerdomain.FieldHomeTemplate)
	return u
}

// SetDocURL sets the "doc_url" field.
func (u *ResellerDomainUpsert) SetDocURL(v string) *ResellerDomainUpsert {
	u.Set(resellerdomain.FieldDocURL, v)
	return u
}

// UpdateDocURL sets the "doc_url" field to the value that was provided on create.
func (u *ResellerDomainUpsert) UpdateDocURL() *ResellerDomainUpsert {
	u.SetExcluded(resellerdomain.FieldDocURL)
	return u
}

// SetPurchaseEnabled sets the "purchase_enabled" field.
func (u *ResellerDomainUpsert) SetPurchaseEnabled(v bool) *ResellerDomainUpsert {
	u.Set(resellerdomain.FieldPurchaseEnabled, v)
	return u
}

// UpdatePurchaseEnabled sets the "purchase_enabled" field to the value that was provided on create.
func (u *ResellerDomainUpsert) UpdatePurchaseEnabled() *ResellerDomainUpsert {
	u.SetExcluded(resellerdomain.FieldPurchaseEnabled)
	return u
}

// SetPurchaseURL sets the "purchase_url" field.
func (u *ResellerDomainUpsert) SetPurchaseURL(v string) *ResellerDomainUpsert {
	u.Set(resellerdomain.FieldPurchaseURL, v)
	return u
}

// UpdatePurchaseURL sets the "purchase_url" field to the value that was provided on create.
func (u *ResellerDomainUpsert) UpdatePurchaseURL() *ResellerDomainUpsert {
	u.SetExcluded(resellerdomain.FieldPurchaseURL)
	return u
}

// SetDefaultLocale sets the "default_locale" field.
func (u *ResellerDomainUpsert) SetDefaultLocale(v string) *ResellerDomainUpsert {
	u.Set(resellerdomain.FieldDefaultLocale, v)
	return u
}

// UpdateDefaultLocale sets the "default_locale" field to the value that was provided on create.
func (u *ResellerDomainUpsert) UpdateDefaultLocale() *ResellerDomainUpsert {
	u.SetExcluded(resellerdomain.FieldDefaultLocale)
	return u
}

// SetSeoTitle sets the "seo_title" field.
func (u *ResellerDomainUpsert) SetSeoTitle(v string) *ResellerDomainUpsert {
	u.Set(resellerdomain.FieldSeoTitle, v)
	return u
}

// UpdateSeoTitle sets the "seo_title" field to the value that was provided on create.
func (u *ResellerDomainUpsert) UpdateSeoTitle() *ResellerDomainUpsert {
	u.SetExcluded(resellerdomain.FieldSeoTitle)
	return u
}

// SetSeoDescription sets the "seo_description" field.
func (u *ResellerDomainUpsert) SetSeoDescription(v string) *ResellerDomainUpsert {
	u.Set(resellerdomain.FieldSeoDescription, v)
	return u
}

// UpdateSeoDescription sets the "seo_description" field to the value that was provided on create.
func (u *ResellerDomainUpsert) UpdateSeoDescription() *ResellerDomainUpsert {
	u.SetExcluded(resellerdomain.FieldSeoDescription)
	return u
}

// SetSeoKeywords sets the "seo_keywords" field.
func (u *ResellerDomainUpsert) SetSeoKeywords(v string) *ResellerDomainUpsert {
	u.Set(resellerdomain.FieldSeoKeywords, v)
	return u
}

// UpdateSeoKeywords sets the "seo_keywords" field to the value that was provided on create.
func (u *ResellerDomainUpsert) UpdateSeoKeywords() *ResellerDomainUpsert {
	u.SetExcluded(resellerdomain.FieldSeoKeywords)
	return u
}

// SetLoginRedirect sets the "login_redirect" field.
func (u *ResellerDomainUpsert) SetLoginRedirect(v string) *ResellerDomainUpsert {
	u.Set(resellerdomain.FieldLoginRedirect, v)
	return u
}

// UpdateLoginRedirect sets the "login_redirect" field to the value that was provided on create.
func (u *ResellerDomainUpsert) UpdateLoginRedirect() *ResellerDomainUpsert {
	u.SetExcluded(resellerdomain.FieldLoginRedirect)
	return u
}

// SetVerifyToken sets the "verify_token" field.
func (u *ResellerDomainUpsert) SetVerifyToken(v string) *ResellerDomainUpsert {
	u.Set(resellerdomain.FieldVerifyToken, v)
	return u
}

// UpdateVerifyToken sets the "verify_token" field to the value that was provided on create.
func (u *ResellerDomainUpsert) UpdateVerifyToken() *ResellerDomainUpsert {
	u.SetExcluded(resellerdomain.FieldVerifyToken)
	return u
}

// SetVerified sets the "verified" field.
func (u *ResellerDomainUpsert) SetVerified(v bool) *ResellerDomainUpsert {
	u.Set(resellerdomain.FieldVerified, v)
	return u
}

// UpdateVerified sets the "verified" field to the value that was provided on create.
func (u *ResellerDomainUpsert) UpdateVerified() *ResellerDomainUpsert {
	u.SetExcluded(resellerdomain.FieldVerified)
	return u
}

// SetVerifiedAt sets the "verified_at" field.
func (u *ResellerDomainUpsert) SetVerifiedAt(v time.Time) *ResellerDomainUpsert {
	u.Set(resellerdomain.FieldVerifiedAt, v)
	return u
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *ResellerDomainUpsert) UpdateVerifiedAt() *ResellerDomainUpsert {
	u.SetExcluded(resellerdomain.FieldVerifiedAt)
	return u
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (u *ResellerDomainUpsert) ClearVerifiedAt() *ResellerDomainUpsert {
	u.SetNull(resellerdomain.FieldVerifiedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ResellerDomain.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ResellerDomainUpsertOne) UpdateNewValues() *ResellerDomainUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(resellerdomain.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResellerDomain.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ResellerDomainUpsertOne) Ignore() *ResellerDomainUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResellerDomainUpsertOne) DoNothing() *ResellerDomainUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResellerDomainCreate.OnConflict
// documentation for more info.
func (u *ResellerDomainUpsertOne) Update(set func(*ResellerDomainUpsert)) *ResellerDomainUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResellerDomainUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ResellerDomainUpsertOne) SetUpdatedAt(v time.Time) *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResellerDomainUpsertOne) UpdateUpdatedAt() *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ResellerDomainUpsertOne) SetDeletedAt(v time.Time) *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ResellerDomainUpsertOne) UpdateDeletedAt() *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ResellerDomainUpsertOne) ClearDeletedAt() *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.ClearDeletedAt()
	})
}

// SetResellerID sets the "reseller_id" field.
func (u *ResellerDomainUpsertOne) SetResellerID(v int64) *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetResellerID(v)
	})
}

// UpdateResellerID sets the "reseller_id" field to the value that was provided on create.
func (u *ResellerDomainUpsertOne) UpdateResellerID() *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateResellerID()
	})
}

// SetDomain sets the "domain" field.
func (u *ResellerDomainUpsertOne) SetDomain(v string) *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetDomain(v)
	})
}

// UpdateDomain sets the "domain" field to the value that was provided on create.
func (u *ResellerDomainUpsertOne) UpdateDomain() *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateDomain()
	})
}

// SetSiteName sets the "site_name" field.
func (u *ResellerDomainUpsertOne) SetSiteName(v string) *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetSiteName(v)
	})
}

// UpdateSiteName sets the "site_name" field to the value that was provided on create.
func (u *ResellerDomainUpsertOne) UpdateSiteName() *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateSiteName()
	})
}

// SetSiteLogo sets the "site_logo" field.
func (u *ResellerDomainUpsertOne) SetSiteLogo(v string) *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetSiteLogo(v)
	})
}

// UpdateSiteLogo sets the "site_logo" field to the value that was provided on create.
func (u *ResellerDomainUpsertOne) UpdateSiteLogo() *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateSiteLogo()
	})
}

// SetBrandColor sets the "brand_color" field.
func (u *ResellerDomainUpsertOne) SetBrandColor(v string) *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetBrandColor(v)
	})
}

// UpdateBrandColor sets the "brand_color" field to the value that was provided on create.
func (u *ResellerDomainUpsertOne) UpdateBrandColor() *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateBrandColor()
	})
}

// SetCustomCSS sets the "custom_css" field.
func (u *ResellerDomainUpsertOne) SetCustomCSS(v string) *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetCustomCSS(v)
	})
}

// UpdateCustomCSS sets the "custom_css" field to the value that was provided on create.
func (u *ResellerDomainUpsertOne) UpdateCustomCSS() *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateCustomCSS()
	})
}

// SetSubtitle sets the "subtitle" field.
func (u *ResellerDomainUpsertOne) SetSubtitle(v string) *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetSubtitle(v)
	})
}

// UpdateSubtitle sets the "subtitle" field to the value that was provided on create.
func (u *ResellerDomainUpsertOne) UpdateSubtitle() *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateSubtitle()
	})
}

// SetHomeContent sets the "home_content" field.
func (u *ResellerDomainUpsertOne) SetHomeContent(v string) *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetHomeContent(v)
	})
}

// UpdateHomeContent sets the "home_content" field to the value that was provided on create.
func (u *ResellerDomainUpsertOne) UpdateHomeContent() *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateHomeContent()
	})
}

// SetHomeTemplate sets the "home_template" field.
func (u *ResellerDomainUpsertOne) SetHomeTemplate(v string) *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetHomeTemplate(v)
	})
}

// UpdateHomeTemplate sets the "home_template" field to the value that was provided on create.
func (u *ResellerDomainUpsertOne) UpdateHomeTemplate() *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateHomeTemplate()
	})
}

// SetDocURL sets the "doc_url" field.
func (u *ResellerDomainUpsertOne) SetDocURL(v string) *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetDocURL(v)
	})
}

// UpdateDocURL sets the "doc_url" field to the value that was provided on create.
func (u *ResellerDomainUpsertOne) UpdateDocURL() *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateDocURL()
	})
}

// SetPurchaseEnabled sets the "purchase_enabled" field.
func (u *ResellerDomainUpsertOne) SetPurchaseEnabled(v bool) *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetPurchaseEnabled(v)
	})
}

// UpdatePurchaseEnabled sets the "purchase_enabled" field to the value that was provided on create.
func (u *ResellerDomainUpsertOne) UpdatePurchaseEnabled() *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdatePurchaseEnabled()
	})
}

// SetPurchaseURL sets the "purchase_url" field.
func (u *ResellerDomainUpsertOne) SetPurchaseURL(v string) *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetPurchaseURL(v)
	})
}

// UpdatePurchaseURL sets the "purchase_url" field to the value that was provided on create.
func (u *ResellerDomainUpsertOne) UpdatePurchaseURL() *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdatePurchaseURL()
	})
}

// SetDefaultLocale sets the "default_locale" field.
func (u *ResellerDomainUpsertOne) SetDefaultLocale(v string) *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetDefaultLocale(v)
	})
}

// UpdateDefaultLocale sets the "default_locale" field to the value that was provided on create.
func (u *ResellerDomainUpsertOne) UpdateDefaultLocale() *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateDefaultLocale()
	})
}

// SetSeoTitle sets the "seo_title" field.
func (u *ResellerDomainUpsertOne) SetSeoTitle(v string) *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetSeoTitle(v)
	})
}

// UpdateSeoTitle sets the "seo_title" field to the value that was provided on create.
func (u *ResellerDomainUpsertOne) UpdateSeoTitle() *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateSeoTitle()
	})
}

// SetSeoDescription sets the "seo_description" field.
func (u *ResellerDomainUpsertOne) SetSeoDescription(v string) *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetSeoDescription(v)
	})
}

// UpdateSeoDescription sets the "seo_description" field to the value that was provided on create.
func (u *ResellerDomainUpsertOne) UpdateSeoDescription() *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateSeoDescription()
	})
}

// SetSeoKeywords sets the "seo_keywords" field.
func (u *ResellerDomainUpsertOne) SetSeoKeywords(v string) *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetSeoKeywords(v)
	})
}

// UpdateSeoKeywords sets the "seo_keywords" field to the value that was provided on create.
func (u *ResellerDomainUpsertOne) UpdateSeoKeywords() *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateSeoKeywords()
	})
}

// SetLoginRedirect sets the "login_redirect" field.
func (u *ResellerDomainUpsertOne) SetLoginRedirect(v string) *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetLoginRedirect(v)
	})
}

// UpdateLoginRedirect sets the "login_redirect" field to the value that was provided on create.
func (u *ResellerDomainUpsertOne) UpdateLoginRedirect() *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateLoginRedirect()
	})
}

// SetVerifyToken sets the "verify_token" field.
func (u *ResellerDomainUpsertOne) SetVerifyToken(v string) *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetVerifyToken(v)
	})
}

// UpdateVerifyToken sets the "verify_token" field to the value that was provided on create.
func (u *ResellerDomainUpsertOne) UpdateVerifyToken() *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateVerifyToken()
	})
}

// SetVerified sets the "verified" field.
func (u *ResellerDomainUpsertOne) SetVerified(v bool) *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetVerified(v)
	})
}

// UpdateVerified sets the "verified" field to the value that was provided on create.
func (u *ResellerDomainUpsertOne) UpdateVerified() *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateVerified()
	})
}

// SetVerifiedAt sets the "verified_at" field.
func (u *ResellerDomainUpsertOne) SetVerifiedAt(v time.Time) *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetVerifiedAt(v)
	})
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *ResellerDomainUpsertOne) UpdateVerifiedAt() *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateVerifiedAt()
	})
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (u *ResellerDomainUpsertOne) ClearVerifiedAt() *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.ClearVerifiedAt()
	})
}

// Exec executes the query.
func (u *ResellerDomainUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResellerDomainCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResellerDomainUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ResellerDomainUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ResellerDomainUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ResellerDomainCreateBulk is the builder for creating many ResellerDomain entities in bulk.
type ResellerDomainCreateBulk struct {
	config
	err      error
	builders []*ResellerDomainCreate
	conflict []sql.ConflictOption
}

// Save creates the ResellerDomain entities in the database.
func (_c *ResellerDomainCreateBulk) Save(ctx context.Context) ([]*ResellerDomain, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ResellerDomain, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResellerDomainMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ResellerDomainCreateBulk) SaveX(ctx context.Context) []*ResellerDomain {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResellerDomainCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResellerDomainCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResellerDomain.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResellerDomainUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ResellerDomainCreateBulk) OnConflict(opts ...sql.ConflictOption) *ResellerDomainUpsertBulk {
	_c.conflict = opts
	return &ResellerDomainUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResellerDomain.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResellerDomainCreateBulk) OnConflictColumns(columns ...string) *ResellerDomainUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResellerDomainUpsertBulk{
		create: _c,
	}
}

// ResellerDomainUpsertBulk is the builder for "upsert"-ing
// a bulk of ResellerDomain nodes.
type ResellerDomainUpsertBulk struct {
	create *ResellerDomainCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ResellerDomain.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ResellerDomainUpsertBulk) UpdateNewValues() *ResellerDomainUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(resellerdomain.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResellerDomain.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ResellerDomainUpsertBulk) Ignore() *ResellerDomainUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResellerDomainUpsertBulk) DoNothing() *ResellerDomainUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResellerDomainCreateBulk.OnConflict
// documentation for more info.
func (u *ResellerDomainUpsertBulk) Update(set func(*ResellerDomainUpsert)) *ResellerDomainUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResellerDomainUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ResellerDomainUpsertBulk) SetUpdatedAt(v time.Time) *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResellerDomainUpsertBulk) UpdateUpdatedAt() *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ResellerDomainUpsertBulk) SetDeletedAt(v time.Time) *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ResellerDomainUpsertBulk) UpdateDeletedAt() *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ResellerDomainUpsertBulk) ClearDeletedAt() *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.ClearDeletedAt()
	})
}

// SetResellerID sets the "reseller_id" field.
func (u *ResellerDomainUpsertBulk) SetResellerID(v int64) *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetResellerID(v)
	})
}

// UpdateResellerID sets the "reseller_id" field to the value that was provided on create.
func (u *ResellerDomainUpsertBulk) UpdateResellerID() *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateResellerID()
	})
}

// SetDomain sets the "domain" field.
func (u *ResellerDomainUpsertBulk) SetDomain(v string) *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetDomain(v)
	})
}

// UpdateDomain sets the "domain" field to the value that was provided on create.
func (u *ResellerDomainUpsertBulk) UpdateDomain() *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateDomain()
	})
}

// SetSiteName sets the "site_name" field.
func (u *ResellerDomainUpsertBulk) SetSiteName(v string) *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetSiteName(v)
	})
}

// UpdateSiteName sets the "site_name" field to the value that was provided on create.
func (u *ResellerDomainUpsertBulk) UpdateSiteName() *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateSiteName()
	})
}

// SetSiteLogo sets the "site_logo" field.
func (u *ResellerDomainUpsertBulk) SetSiteLogo(v string) *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetSiteLogo(v)
	})
}

// UpdateSiteLogo sets the "site_logo" field to the value that was provided on create.
func (u *ResellerDomainUpsertBulk) UpdateSiteLogo() *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateSiteLogo()
	})
}

// SetBrandColor sets the "brand_color" field.
func (u *ResellerDomainUpsertBulk) SetBrandColor(v string) *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetBrandColor(v)
	})
}

// UpdateBrandColor sets the "brand_color" field to the value that was provided on create.
func (u *ResellerDomainUpsertBulk) UpdateBrandColor() *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateBrandColor()
	})
}

// SetCustomCSS sets the "custom_css" field.
func (u *ResellerDomainUpsertBulk) SetCustomCSS(v string) *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetCustomCSS(v)
	})
}

// UpdateCustomCSS sets the "custom_css" field to the value that was provided on create.
func (u *ResellerDomainUpsertBulk) UpdateCustomCSS() *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateCustomCSS()
	})
}

// SetSubtitle sets the "subtitle" field.
func (u *ResellerDomainUpsertBulk) SetSubtitle(v string) *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetSubtitle(v)
	})
}

// UpdateSubtitle sets the "subtitle" field to the value that was provided on create.
func (u *ResellerDomainUpsertBulk) UpdateSubtitle() *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateSubtitle()
	})
}

// SetHomeContent sets the "home_content" field.
func (u *ResellerDomainUpsertBulk) SetHomeContent(v string) *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetHomeContent(v)
	})
}

// UpdateHomeContent sets the "home_content" field to the value that was provided on create.
func (u *ResellerDomainUpsertBulk) UpdateHomeContent() *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateHomeContent()
	})
}

// SetHomeTemplate sets the "home_template" field.
func (u *ResellerDomainUpsertBulk) SetHomeTemplate(v string) *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetHomeTemplate(v)
	})
}

// UpdateHomeTemplate sets the "home_template" field to the value that was provided on create.
func (u *ResellerDomainUpsertBulk) UpdateHomeTemplate() *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateHomeTemplate()
	})
}

// SetDocURL sets the "doc_url" field.
func (u *ResellerDomainUpsertBulk) SetDocURL(v string) *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetDocURL(v)
	})
}

// UpdateDocURL sets the "doc_url" field to the value that was provided on create.
func (u *ResellerDomainUpsertBulk) UpdateDocURL() *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateDocURL()
	})
}

// SetPurchaseEnabled sets the "purchase_enabled" field.
func (u *ResellerDomainUpsertBulk) SetPurchaseEnabled(v bool) *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetPurchaseEnabled(v)
	})
}

// UpdatePurchaseEnabled sets the "purchase_enabled" field to the value that was provided on create.
func (u *ResellerDomainUpsertBulk) UpdatePurchaseEnabled() *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdatePurchaseEnabled()
	})
}

// SetPurchaseURL sets the "purchase_url" field.
func (u *ResellerDomainUpsertBulk) SetPurchaseURL(v string) *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetPurchaseURL(v)
	})
}

// UpdatePurchaseURL sets the "purchase_url" field to the value that was provided on create.
func (u *ResellerDomainUpsertBulk) UpdatePurchaseURL() *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdatePurchaseURL()
	})
}

// SetDefaultLocale sets the "default_locale" field.
func (u *ResellerDomainUpsertBulk) SetDefaultLocale(v string) *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetDefaultLocale(v)
	})
}

// UpdateDefaultLocale sets the "default_locale" field to the value that was provided on create.
func (u *ResellerDomainUpsertBulk) UpdateDefaultLocale() *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateDefaultLocale()
	})
}

// SetSeoTitle sets the "seo_title" field.
func (u *ResellerDomainUpsertBulk) SetSeoTitle(v string) *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetSeoTitle(v)
	})
}

// UpdateSeoTitle sets the "seo_title" field to the value that was provided on create.
func (u *ResellerDomainUpsertBulk) UpdateSeoTitle() *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateSeoTitle()
	})
}

// SetSeoDescription sets the "seo_description" field.
func (u *ResellerDomainUpsertBulk) SetSeoDescription(v string) *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetSeoDescription(v)
	})
}

// UpdateSeoDescription sets the "seo_description" field to the value that was provided on create.
func (u *ResellerDomainUpsertBulk) UpdateSeoDescription() *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateSeoDescription()
	})
}

// SetSeoKeywords sets the "seo_keywords" field.
func (u *ResellerDomainUpsertBulk) SetSeoKeywords(v string) *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetSeoKeywords(v)
	})
}

// UpdateSeoKeywords sets the "seo_keywords" field to the value that was provided on create.
func (u *ResellerDomainUpsertBulk) UpdateSeoKeywords() *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateSeoKeywords()
	})
}

// SetLoginRedirect sets the "login_redirect" field.
func (u *ResellerDomainUpsertBulk) SetLoginRedirect(v string) *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetLoginRedirect(v)
	})
}

// UpdateLoginRedirect sets the "login_redirect" field to the value that was provided on create.
func (u *ResellerDomainUpsertBulk) UpdateLoginRedirect() *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateLoginRedirect()
	})
}

// SetVerifyToken sets the "verify_token" field.
func (u *ResellerDomainUpsertBulk) SetVerifyToken(v string) *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetVerifyToken(v)
	})
}

// UpdateVerifyToken sets the "verify_token" field to the value that was provided on create.
func (u *ResellerDomainUpsertBulk) UpdateVerifyToken() *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateVerifyToken()
	})
}

// SetVerified sets the "verified" field.
func (u *ResellerDomainUpsertBulk) SetVerified(v bool) *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetVerified(v)
	})
}

// UpdateVerified sets the "verified" field to the value that was provided on create.
func (u *ResellerDomainUpsertBulk) UpdateVerified() *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateVerified()
	})
}

// SetVerifiedAt sets the "verified_at" field.
func (u *ResellerDomainUpsertBulk) SetVerifiedAt(v time.Time) *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetVerifiedAt(v)
	})
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *ResellerDomainUpsertBulk) UpdateVerifiedAt() *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateVerifiedAt()
	})
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (u *ResellerDomainUpsertBulk) ClearVerifiedAt() *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.ClearVerifiedAt()
	})
}

// Exec executes the query.
func (u *ResellerDomainUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ResellerDomainCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResellerDomainCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResellerDomainUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
