// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/resellerwithdrawal"
)

// ResellerWithdrawalDelete is the builder for deleting a ResellerWithdrawal entity.
type ResellerWithdrawalDelete struct {
	config
	hooks    []Hook
	mutation *ResellerWithdrawalMutation
}

// Where appends a list predicates to the ResellerWithdrawalDelete builder.
func (_d *ResellerWithdrawalDelete) Where(ps ...predicate.ResellerWithdrawal) *ResellerWithdrawalDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ResellerWithdrawalDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ResellerWithdrawalDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ResellerWithdrawalDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(resellerwithdrawal.Table, sqlgraph.NewFieldSpec(resellerwithdrawal.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ResellerWithdrawalDeleteOne is the builder for deleting a single ResellerWithdrawal entity.
type ResellerWithdrawalDeleteOne struct {
	_d *ResellerWithdrawalDelete
}

// Where appends a list predicates to the ResellerWithdrawalDelete builder.
func (_d *ResellerWithdrawalDeleteOne) Where(ps ...predicate.ResellerWithdrawal) *ResellerWithdrawalDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ResellerWithdrawalDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{resellerwithdrawal.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ResellerWithdrawalDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
