// Code generated by ent, DO NOT EDIT.

package referralreward

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the referralreward type in the database.
	Label = "referral_reward"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldReferrerID holds the string denoting the referrer_id field in the database.
	FieldReferrerID = "referrer_id"
	// FieldInviteeID holds the string denoting the invitee_id field in the database.
	FieldInviteeID = "invitee_id"
	// FieldTriggerOrderID holds the string denoting the trigger_order_id field in the database.
	FieldTriggerOrderID = "trigger_order_id"
	// FieldReferrerReward holds the string denoting the referrer_reward field in the database.
	FieldReferrerReward = "referrer_reward"
	// FieldInviteeReward holds the string denoting the invitee_reward field in the database.
	FieldInviteeReward = "invitee_reward"
	// FieldSkipReferrerReason holds the string denoting the skip_referrer_reason field in the database.
	FieldSkipReferrerReason = "skip_referrer_reason"
	// EdgeReferrer holds the string denoting the referrer edge name in mutations.
	EdgeReferrer = "referrer"
	// EdgeInvitee holds the string denoting the invitee edge name in mutations.
	EdgeInvitee = "invitee"
	// EdgeTriggerOrder holds the string denoting the trigger_order edge name in mutations.
	EdgeTriggerOrder = "trigger_order"
	// Table holds the table name of the referralreward in the database.
	Table = "referral_rewards"
	// ReferrerTable is the table that holds the referrer relation/edge.
	ReferrerTable = "referral_rewards"
	// ReferrerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ReferrerInverseTable = "users"
	// ReferrerColumn is the table column denoting the referrer relation/edge.
	ReferrerColumn = "referrer_id"
	// InviteeTable is the table that holds the invitee relation/edge.
	InviteeTable = "referral_rewards"
	// InviteeInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	InviteeInverseTable = "users"
	// InviteeColumn is the table column denoting the invitee relation/edge.
	InviteeColumn = "invitee_id"
	// TriggerOrderTable is the table that holds the trigger_order relation/edge.
	TriggerOrderTable = "referral_rewards"
	// TriggerOrderInverseTable is the table name for the Order entity.
	// It exists in this package in order to avoid circular dependency with the "order" package.
	TriggerOrderInverseTable = "orders"
	// TriggerOrderColumn is the table column denoting the trigger_order relation/edge.
	TriggerOrderColumn = "trigger_order_id"
)

// Columns holds all SQL columns for referralreward fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldReferrerID,
	FieldInviteeID,
	FieldTriggerOrderID,
	FieldReferrerReward,
	FieldInviteeReward,
	FieldSkipReferrerReason,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultReferrerReward holds the default value on creation for the "referrer_reward" field.
	DefaultReferrerReward float64
	// DefaultInviteeReward holds the default value on creation for the "invitee_reward" field.
	DefaultInviteeReward float64
	// SkipReferrerReasonValidator is a validator for the "skip_referrer_reason" field. It is called by the builders before save.
	SkipReferrerReasonValidator func(string) error
)

// OrderOption defines the ordering options for the ReferralReward queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByReferrerID orders the results by the referrer_id field.
func ByReferrerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferrerID, opts...).ToFunc()
}

// ByInviteeID orders the results by the invitee_id field.
func ByInviteeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviteeID, opts...).ToFunc()
}

// ByTriggerOrderID orders the results by the trigger_order_id field.
func ByTriggerOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerOrderID, opts...).ToFunc()
}

// ByReferrerReward orders the results by the referrer_reward field.
func ByReferrerReward(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferrerReward, opts...).ToFunc()
}

// ByInviteeReward orders the results by the invitee_reward field.
func ByInviteeReward(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviteeReward, opts...).ToFunc()
}

// BySkipReferrerReason orders the results by the skip_referrer_reason field.
func BySkipReferrerReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkipReferrerReason, opts...).ToFunc()
}

// ByReferrerField orders the results by referrer field.
func ByReferrerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReferrerStep(), sql.OrderByField(field, opts...))
	}
}

// ByInviteeField orders the results by invitee field.
func ByInviteeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInviteeStep(), sql.OrderByField(field, opts...))
	}
}

// ByTriggerOrderField orders the results by trigger_order field.
func ByTriggerOrderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTriggerOrderStep(), sql.OrderByField(field, opts...))
	}
}
func newReferrerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReferrerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ReferrerTable, ReferrerColumn),
	)
}
func newInviteeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InviteeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, InviteeTable, InviteeColumn),
	)
}
func newTriggerOrderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TriggerOrderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, TriggerOrderTable, TriggerOrderColumn),
	)
}
